### PR TITLE
Updated MyGUI to 3.4.0

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**

### CODE REVIEW

**Comment by tritonas00** [comment]
Does it fix the black screen issues with ogre 1.12 and Dx9 also?

**Comment by AnotherFoxGuy** [comment]
Since we use imgui for the main menu, that is no longer issue

**Comment by tritonas00** [comment]
yes but what about the HUD?

**Comment by AnotherFoxGuy** [comment]
MyGUI still has the issue that it doesn't render on 1.12.8

@tritonas00 Could you test this PR on Linux and see if everything still works?

**Comment by tritonas00** [comment]
Sure

**Comment by tritonas00** [comment]
I get this https://pastebin.com/30Ta1m4G (i dont think its related with this PR since its an openal issue it seems)

**Pull request merged**
