### PR TITLE
New GUI library: Dear IMGUI

### PR DESCRIPTION
**Pull request by only-a-ptr**
imgui-preview

I want to drop our current library (MyGUI) and remake everything in [Dear IMGUI](https://github.com/ocornut/imgui) because:
- Much less code! MyGUI requires terrible amount of boilerplate code to set up bindings with XML definitions. There's code generator, but you still have to deal with the code afterwards. And even if you create GUI in code, you need a lot of boilerplate for simple things like [X] close button on windows.
- Automated layout! MyGUI does have a visual editor, but no layout tools - you need to position every single widget by hand. It gets very tiresome. With IMGUI, you just say "show 3 buttons, separator, label and 2 more buttons" and it's nicely laid out for you.
- Professional looks! The GUI looks like Blender or some other professional-level software - by default! MyGUI's skin system is awful and undocumented - for years, RoR had been stuck with it's default skin, re-painted to (awful!) orange. The current skin by Max98 is orders of magnitude better, but it's still not very clean.
- The GUI is actually capable! Just look at it's GitHub page's screenshots. All complex editor/diagnostic UIs! Graphs! Plots! MyGUI isn't really capable GUI system - even a multi-column selectable table (multiplayer lobby) was tricky. With RigEditor (unfinished, circa 2014), I ultimately gave up - MyGUI was slowing me down to a complete halt.
- The GUI is fast and __fun__ to create!

For a demonstration, I remade the top menubar. The old one behaved weird and was bloated. UPDATE: Now it's complete, the vehicles menu was restored.

### CODE REVIEW

**Comment by Michael10055** [comment]
Looks much more professional and clean. 👍

**Comment by vido89** [comment]
Looks good if its worth it, well its way to go

**Comment by only-a-ptr** [comment]
rigsofrods-imgui-mainmenu

Note the font is not final - it's the built-in basic one. The IMGUI-OGRE integration has currently issues with rendering TTF fonts, I'm [solving it on the OGRE forums](http://www.ogre3d.org/forums/viewtopic.php?f=5&t=89081#p537008).

**Comment by tritonas00** [comment]
Nice!!

Will the source be integrated into RoR or it will be an external dependency?

**Comment by tritonas00** [comment]
Any tips for this error https://pastebin.com/QfepNj6J please?

Maybe a missing "include"?

**Comment by only-a-ptr** [comment]
@tritonas00 : Eh, more like missing '9' in your OGRE version (1.8) 😆 

Fixing it...

**Comment by tritonas00** [comment]
Ok compiles fine but i cant see any menu and this error many times:

`GLSL compile log: imgui/VP/GL1500:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES`

**Comment by tritonas00** [comment]
Fixed: `MESA_GL_VERSION_OVERRIDE=3.0 MESA_GLSL_VERSION_OVERRIDE=310 /opt/rigsofrods/RoR`

**Comment by only-a-ptr** [comment]
new-truckfile-debug-options

I've removed the broken "Debug Options" panel and added the truckfile debug logging options as checkboxes to the top menubar. Extra captions and tooltips included!

This GUI looks freaking awesome 😀

**Comment by tritonas00** [comment]
a bit of love for gcc also? :smile:

**Comment by Michael10055** [comment]
New skeleton view looks good, some suggestions:
- The beam color should be green again (maybe not as bright as it was previously) 
- Text could be a bit brighter white and slightly larger
- Possible for beams to be a different color depending on what type of beam it is? (for example, red for shocks, blue for hydros, etc)

**Comment by only-a-ptr** [comment]
Hi everyone.

It turns out DearIMGUI isn't just a GUI library - it can be easily used for general-purpose drawing on screen (with built-in antia-aliasing!). I figured out I could use this for all sorts of debug displays, starting with our well known "skeleton view" and going further with our "debug views", which mostly display tiny/unreadable numbers.

I re-purposed the 'K' hotkey: now it cycles between the debug views, detailed below:

## Skeleton view
I updated my previous draft - I decided to use a much darker color for beams (there's many beams, and having them bright makes the view convoluted) and very bright color for nodes.
Broken beams show thicker and red (replaces 'broken beams debugView') and hydros show brown. I'd like to have more specific coloring, but this is all that current physics data structures offer.
Beams which are locked/locking/unlocking are drawn with extra colored circle around them.
screenshot_2017-06-18_01-30-22_1

## Node details view
Here I merged 2 old 'debug views': node numbers (white text) and node mass (bright green text). Note: generated nodes (cinecam, wheels...) show '-1' which is exactly what's in the physics data. The old debugview assigned sequential numbers to these nodes, which I considered bogus.
screenshot_2017-06-18_01-30-26_1

## Beam details view
This merges 3 old debug views: beam strength (white text), beam compression (light blue text) and beam stress (bright orange text). Node numbers are drawn like above, except without mass. Note I completely dropped 'beam numbers' view because beams don't have numbers - those displayed were sequentially assigned, which I considered bogus.
screenshot_2017-06-18_01-30-35_1

**Comment by tritonas00** [comment]
Builds and works fine with ogre 1.8 also :clap:

**Comment by disloyalpick** [comment]
So I'm not sure if I might be doing something wrong, or what. But I built this PR in linux.
I have not been around linux at all for quite some time, so whatever information you need, please do not hesitate to ask for it, xD.

With that being said, the build completed successfully, but when I open RoR the GUI of the Main Menu is not shown, along with ALL the other elements of DearIMGUI . If there is something you think I may be missing, please let me know haha.
Do I have to manually build/compile DearIMGUI?

**Comment by tritonas00** [comment]
Run RoR like this: `MESA_GL_VERSION_OVERRIDE=3.0  RoR`

**Comment by disloyalpick** [comment]
Should I run that from the directory the ror executable is?

**Comment by tritonas00** [comment]
yes cd in there and `MESA_GL_VERSION_OVERRIDE=3.0 ./RoR`

**Comment by disloyalpick** [comment]
alrighty, thanks

that worked, however the skeleton view does not. I press K once. Nothing happens. I press K twice, nothing happens, then I press K the third time, and RoR crashes

Here is the bottom most of RoR.log that seems to pertain to imgui

`20:20:50: GLHardwareVertexBuffer::lock - Error: failed to Discard the buffer. Try to recreate the buffer
20:20:50: GLSL compile log: imgui/VP/GL1500:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

20:20:50: GLHardwareVertexBuffer::lock - Error: failed to Discard the buffer. Try to recreate the buffer
20:20:50: GLSL compile log: imgui/VP/GL1500:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

20:20:50: GLHardwareVertexBuffer::lock - Error: failed to Discard the buffer. Try to recreate the buffer
20:20:50: GLSL compile log: imgui/VP/GL1500:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

20:20:51: GLHardwareVertexBuffer::lock - Error: failed to Discard the buffer. Try to recreate the buffer
20:20:51: GLSL compile log: imgui/VP/GL1500:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

20:20:51: GLHardwareVertexBuffer::lock - Error: failed to Discard the buffer. Try to recreate the buffer
20:20:51: GLSL compile log: imgui/VP/GL1500:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

20:20:51: GLHardwareVertexBuffer::lock - Error: failed to Discard the buffer. Try to recreate the buffer
20:20:51: GLSL compile log: imgui/VP/GL1500:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

20:20:51: GLHardwareVertexBuffer::lock - Error: failed to Discard the buffer. Try to recreate the buffer`

**Comment by tritonas00** [comment]
try `MESA_GL_VERSION_OVERRIDE=3.0 MESA_GLSL_VERSION_OVERRIDE=310 ./RoR`

**Comment by disloyalpick** [comment]
forget my stupidity, i forgot to run that command earlier lol, but it does still crash when i press K the third time. ill try what you just posted there and see if that has any effect for crashing which im doubtful lol

**Comment by tritonas00** [comment]
or try `MESA_GL_VERSION_OVERRIDE=3.0 MESA_GLSL_VERSION_OVERRIDE=300 ./RoR`

**Comment by disloyalpick** [comment]
that one you just posted the skeleton view doesn't work but the crash when pressing K the third time is gone

**Comment by tritonas00** [comment]
hmm old mesa version probably, check the numbers on the log and try other onrs for your mesa version

**Comment by disloyalpick** [comment]
image

i think this is what you mean correct?

**Comment by tritonas00** [comment]
no try to force one of the supported GLSL version numbers from the ror log

**Comment by disloyalpick** [comment]
i got it working but not by using a GLSL version from ror.log  i just took a shot in the dark and used this


*MESA_GL_VERSION_OVERRIDE=3.0 MESA_GLSL_VERSION_OVERRIDE=330 ./RoR*

**Comment by tritonas00** [comment]
@only-a-ptr is this maybe an upstream imgui issue or a linux mesa issue?

**Comment by disloyalpick** [comment]
only some vehicles cause the crash when pressing K the third time. the Legacy DAF Semi truck does not cause it.

Gabester's 49' Ford causes it. Others probably, that I havent tested yet

**Comment by only-a-ptr** [comment]
I'm glad it's working for you.

The OGRE-IMGUI integration carries some GLSL shaders which have hardcoded version requirement to "150". I'm not sure why the author chose so, I'll ask him. My impression is that only basic shading is used and thus a much lower version should suffice.

OpenGL vs. GLSL versions: https://www.khronos.org/opengl/wiki/Core_Language_(GLSL)#OpenGL_and_GLSL_versions

**Comment by disloyalpick** [comment]
@only-a-ptr 
This is one that crashes... https://archives.rigsofrods.org/repo/gabester-vehicles/49ford.zip

This is also another one that crashes... https://archives.rigsofrods.org/repo/repofiles-1st-batch/07f3d21c7656f1d32296a041248992013d078ee2_ScaniaR560_6x2.zip

**Comment by tritonas00** [comment]
I can't reproduce the crashes here

**Comment by tritonas00** [comment]
With this PR, bajarama map crashes https://forum.rigsofrods.org/attachment.php?aid=211

Also i noticed the same Auriga and Miniredmars

**Comment by Michael10055** [comment]
I can confirm this crash happens with Auriga and Miniredmars.

**Comment by tritonas00** [comment]
https://pastebin.com/p96349pq :stuck_out_tongue_closed_eyes:

**Comment by only-a-ptr** [comment]
Fixed spawning of Bajarama and Auriga terrains. I couldn't find terrn2 version of Miniredmars.

**Comment by Michael10055** [comment]
@only-a-ptr 

https://www.rigsofrods.org/old-forum/forums/128-Terrains-objects/109425/attached-files/miniredmars.zip

**Comment by tritonas00** [comment]
Nice! Can you checkout the imgui.ini path? This file is created in pwd

I think it should go in .rigsofrods/config/

**Comment by only-a-ptr** [comment]
Allright, I'd like to get this merged. I need the new GUI in upstream so I can build upon it (a SkyX-debug panel for example 😋 )

The only remaining issues are:
* The 'imgui.ini' gets created in working directory, reported by @tritonas00  - I'll just disable saving 'imgui.ini' altogether, we don't need it. Working on it...

* @disloyalpick @tritonas00 You guys had slight trouble getting it to run, as I commented here: https://github.com/RigsOfRods/rigs-of-rods/pull/1333#issuecomment-310245578  I tried lowering the version requirement, but the lowes I got was OpenGL 3.0 (starting at OpenGL 3.2), then I started getting "this isn't supported yet" errors. Unfortunately I don't know GLSL well enough to experiment further, at least not this time around... will you guys be OK with merging it as-is?

**Comment by AnotherFoxGuy** [comment]
How many GUI elements are still using MyGUI?

**Comment by only-a-ptr** [comment]
> @AnotherFoxGuy How many GUI elements are still using MyGUI?

Almost all of them 😆 Most notably:
* The selector window
* Truck info box and the modern HUD indicators.
* The console/multiplayer chat/on-screen messages
* Race times UI / notifications
* The main menu background image

None of these would be extra hard to replace and I'm looking foward to doing it, but it'll take time which I don't have ATM. Also, MyGUI is working fine, so it's not a priority change.

**Comment by tritonas00** [comment]
https://github.com/RigsOfRods/rigs-of-rods/pull/1333/commits/e2c4df8064affb134fd3ade37ed6bf57cf2f355e works fine for me also

**Comment by only-a-ptr** [comment]
> @tritonas00 "Change map" in the Pause menu .. hangs at unloading terrain

Checking that...

**Comment by Speciesx** [comment]
Mouse cursor still not on top the imgui elements.

**Comment by only-a-ptr** [comment]
> @Speciesx Mouse cursor still not on top the imgui elements.

Oh, right.. that's because MyGUI draws that cursor, actually. I have Windows cursor enabled, so I didn't notice. IMGUI can draw cursor too, I'll check it...

**Comment by Speciesx** [comment]
Settings and Multiplayer menu doesn't work.

Skeleton view has two bugs, visible in the video.
Activate skeleton view, secure the load and switch thru the skeleton view mods.
https://youtu.be/EgLK8mUR1Vo

**Comment by only-a-ptr** [comment]
@Speciesx Those windows have been temporarily disabled IIRC, it's been a while since I started this PR. I'll remake them.

Thanks for the video, there's a lot of interesting things. I didn't even know that the skeletonview propagated to locked vehicles, but yes, there's code for it. Just to be sure I got it right:
* Problem 1 = the haywire polygons blinking across the entire plane. Looks like something wrong between DearIMGUI and OGRE, because I could not create this effect in code, even if I wanted to.
* Problem 2 = the propagation of skeletonview state from the plane to the truck is somehow random.

Can you give me download links to the plane and truck? And how do you secure the truck to the plane?

**Comment by Speciesx** [comment]
@only-a-ptr 

> Problem 1 = the haywire polygons blinking across the entire plane.
    
yes

> Problem 2 = the propagation of skeletonview state from the plane to the truck is somehow random.

Is not random, the propagation of skeletonview nearly fully broken. 
Here is how it should work. https://youtu.be/aXrPPufFvIw

> And how do you secure the truck to the plane?

With O

https://archives.rigsofrods.org/repo/repofiles-2nd-batch/An-12.zip
https://archives.rigsofrods.org/repo/repofiles-3rd-batch/d7658c474a1cbfd3376ead7a8958fab44f8372b0_Lenni-MAN-TGX-Semipack-1312UID.zip

**Comment by only-a-ptr** [comment]
Multiplayer selector is back. It doesn't work jet, just displays dummy data.
image

**Comment by tritonas00** [comment]
https://pastebin.com/EzycSYf8

**Comment by Speciesx** [comment]
Could you change the esc button behavior?
I personally would prefer, hitting esc in submenu, like multiplayer, settings, etc., should switch to mainmenu and when hitting esc in mainmenu, ror should ask close ror yes/no.

**Comment by tritonas00** [comment]
> https://pastebin.com/EzycSYf8 missing some 'include' for ogre 1.8?

https://github.com/RigsOfRods/rigs-of-rods/pull/1333/commits/5a104eb029f81f7deb810c66428ebb8824acf6d7#diff-133bc5dddb1805c9684539f6bc17ba3bR179 (&renderable)

**Comment by only-a-ptr** [comment]
@tritonas00 https://github.com/RigsOfRods/rigs-of-rods/commit/5a104eb029f81f7deb810c66428ebb8824acf6d7#diff-133bc5dddb1805c9684539f6bc17ba3bR179

That line is completely broken, I don't understand how it passed thru Travis (MSVC doesn't surprise me anymore)... Hotfix pushed.

**Comment by tritonas00** [comment]
Thanks, works!

**Comment by Speciesx** [comment]
btw. a settings button would be nice in the pause menu.

**Comment by Speciesx** [comment]
if you need ideas. :)
but the list view should be optional.
image-0022

**Comment by only-a-ptr** [comment]
> @Speciesx Could you change the esc button behavior?

Wow, you're a daring adventurer to be re-thinking such a classic feature as "the ESC killswitch" 🤣 The answer is "yes I can" and I will.

> @Speciesx btw. a settings button in the pause menu would be nice.

Believe me, I can't wait to add it. However, we need functional in-game settings in the first place. The settings panel made by Max98 back in the day only works in main menu (settings become effective on simulation start) and I'll remake it anyway because of my new concept of game settings (the GVars).

> @Speciesx if you need ideas. :)

Always do 😄  However, this concept lacks the always-ready search bar at the top, which I think is great to have.

**Comment by Speciesx** [comment]
@only-a-ptr 
> However, this concept lacks the always-ready search bar at the top, which I think is great to have.

look at top right.

**Comment by Michael10055** [comment]
I assume the password protected server detection isn't finished yet? The `[2.40-dev]_Official_Any_Test` server has a password but the server list says it doesn't:
ror_2017-10-02_19-33-56
Changing the username and password works 👍

**Comment by only-a-ptr** [comment]
@Michael10055 The serverlist JSON says there's no password: http://multiplayer.rigsofrods.org/server-list?json=true

> alt-tab to another window right after, RoR will crash. ... doesn't happen in the upstream. 

I can't open the link from work, I'll check later. Questions: rendersystem? fullscreen mode?

I'm running windowed using OpenGL on Win7, and activating another window causes DearIMGUI to stop being drawn. When I swithch back, it's visible again. Also dunno why.

**Comment by Michael10055** [comment]
Hmm.. seems like a server list issue then, as the server definitely has a password. About the alt+tab crash, I'm running in windowed mode (input grabbing set to Dynamically) and DirectX.

**Comment by tritonas00** [comment]
@only-a-ptr can you check this issue: load auriga and check the actors list

**Comment by AnotherFoxGuy** [comment]
https://github.com/RigsOfRods/rigs-of-rods/pull/1333/commits/96a6a9e8270a02176b692e2fab309ee99c705194 Breaks the message box used by [the tutorial terrain](https://github.com/AnotherFoxGuy/Content/raw/master/Tutorial.zip)
Before


After

**Comment by only-a-ptr** [comment]
> @tritonas00 load auriga and check the actors list

😮  I have no idea how that happened.

> @AnotherFoxGuy 96a6a9e Breaks the message box used by the tutorial terrain

Interesting, thanks for pointing that out.

**Comment by tritonas00** [comment]
> I have no idea how that happened.

It only happens in auriga (so far)

**Comment by only-a-ptr** [comment]
@AnotherFoxGuy I restored the MessageBox events, please re-test the TutTerrain

**Comment by only-a-ptr** [comment]
Connecting to multiplayer no longer freezes the app, but draws an animated waiting spinner instead.
image

**Comment by only-a-ptr** [comment]
Closing this in favor of https://github.com/RigsOfRods/rigs-of-rods/pull/1414 - other changes will be added in future PRs.

**Pull request closed without merging**
