### PR TITLE
[Fix] Fixed compiling with ogre 1.8

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
Fixed #789 If you want to compile with ogre 1.8

### CODE REVIEW

**Comment by tritonas00** [comment]
:+1:

**Comment by ulteq** [comment]
:+1: 

But I think we're using `ROR_USE_OGRE_1_9` to check if Ogre 1.9 is being used.

**Comment by only-a-ptr** [comment]
@ulteq It's OK like this.

**Comment by only-a-ptr** [comment]
Oops, misclicked :blush:

**Pull request merged**
