### PR TITLE
[Bugfix] Force parser to commit unfinished sections right before end

### PR DESCRIPTION
**Pull request by ulteq**
Fixes broken camerarail on Henschel train.

### CODE REVIEW

**Comment by only-a-ptr** [comment]
@ulteq I need testing instructions for this.

I applied the fixes (both my suggestion + your `end` fix, just to be sure), but I still can't work with the camerarail. Note that I never used camerarails before, all my knowledge come from here: http://www.rigsofrods.com/wiki/pages/Truck_Description_File#Camerarail

**Comment by ulteq** [comment]
@only-a-ptr Use this train: http://www.rigsofrods.com/repository/view/4340

Press 'c' until you reach the regular 3rd person camera, then press 'c' once again and your are in camera rail view.

**Comment by ulteq** [comment]
@only-a-ptr I'm sorry! I forgot to push parts of the bugfix:

https://github.com/RigsOfRods/rigs-of-rods/commit/5354fd432dd6b1726faf85cd1f807bfe5fa93fa8

**Comment by only-a-ptr** [comment]
@ulteq no problem. I'll try again on monday, I'm out of home now.

**Comment by only-a-ptr** [comment]
:+1:

**Pull request merged**
