### PR TITLE
Increased version to 0.4.5 and added the -dev tag

### PR DESCRIPTION
**Pull request by Max98**
As said here: https://github.com/RigsOfRods/rigs-of-rods/issues/112

Will not merge until you guys agree.

### CODE REVIEW

**Comment by Hiradur** [comment]
I think ROR_DEVMODE is not a good name for this. I suggest to use ROR_INDEV + a comment to explain.  
Or we include it directly in the string:
```
#define ROR_VERSION_STRING "0.4.5.0-dev"
```

**Comment by Max98** [comment]
Will do that then :P

**Comment by Max98** [comment]
@Hiradur Should I merge it like that? :P

**Comment by Max98** [comment]
I'll go on and merge it, as because I did the exact thing that Hiradur said. :P

**Pull request merged**
