### PR TITLE
[WIP] Water GFX fixes

### PR DESCRIPTION
**Pull request by only-a-ptr**
UPDATE: I added some extensive code cleanups, do NOT merge yet.

### CODE REVIEW

**Comment by tritonas00** [comment]
adding `#include <OgreTexture.h>` to Water.h fixes it

**Comment by only-a-ptr** [comment]
> @tritonas00 adding only #include <OgreTexture.h> to Water.h fixes it 😊

Meaning my revision is also working or not? If not, I guess OGRE 1.8 has the defs in different headers.

**Comment by tritonas00** [comment]
> Meaning my revision is also working or not?

nope doesn't work for me

**Comment by tritonas00** [comment]
just checked this PR again, now it works

**Comment by tritonas00** [comment]
When you set water to reflection+refraction, swim and move the camera below the waterline this happens:
2018-02-07-172543_1366x768_scrot

Notice also the cursor is reflected too. Maybe you want to fix this in this PR.

**Comment by only-a-ptr** [comment]
@tritonas00 Yes I want to fix it, though it's an old thing, I just tried v0.4.6 and it was already hapenning.

**Comment by Speciesx** [comment]
water splashes also underwater https://youtu.be/opRj8fmQTtc?t=31s

**Comment by only-a-ptr** [comment]
@Speciesx Is that new or old issue?

**Comment by Speciesx** [comment]
@only-a-ptr 
Old one like https://github.com/RigsOfRods/rigs-of-rods/issues/986
Maybe you can also fix this one too?
https://github.com/RigsOfRods/rigs-of-rods/issues/29

**Comment by only-a-ptr** [comment]
I'll see what I can do. I think I can fix the splashes, but the brightness issue looks complicated.

**Comment by only-a-ptr** [comment]
Eh, just tested with WeaselBoat on Auriga... my FPS dropped to ~3 🤢 
Profiler showed this:
obrazek
I had "Waves=Yes" in RoR.cfg. I did suspect that code to be inefficient, but this is over the top...

**Comment by Speciesx** [comment]
ror_2018_02_11_22_22_27_105
refraction has a gap above the water

refraction has pretty low resolution, even in quality mode.
https://youtu.be/EXlcGk93cEw

**Comment by only-a-ptr** [comment]
> refraction has a gap above the water

Wasn't it always there? I mean the reflection always drifts somewhat away from the object.

> refraction has pretty low resolution, even in quality mode.

It's hardcoded (comes from OGRE sample), but makes sense to make it configurable.

**Comment by tritonas00** [comment]
Looks good

**Comment by only-a-ptr** [comment]
I can't believe I've let this rot here for *T W O   Y E A R S* 🤢 
My sense of time is genuine nonsense 😳 

I compared this to upstream and found out there is nothing of value here - all the cleanups made it to upstream in the meantime and the reflection code seems to be equivalent, too, minus some experiments that didn't really work out.

Closing and examining conscience.

**Pull request closed without merging**
