### PR TITLE
✨ Introduced shocks3

### PR DESCRIPTION
**Pull request by ulteq**
Similar to `shocks2`, but the damping is now based off the compression / extension velocity.

Idea, design and truck file format by @Dohzer.

Example:
```
shocks3
;node1, node2, springin(N/m), dampin(N/m/s), slowdampin, splitin(m/s), fastdampin, springout(N/m), dampout(N/m/s), slowdampout, splitout(m/s), fastdampout, shortbound, longbound, precomp, options 
;F
40, 72, 23430, 1500, 0.5, 1.2, 0.2, 23430, 500, 0.5, 1.2, 0.2, 0.62, 0.00, 1.2, n
41, 73, 23430, 1500, 0.5, 1.2, 0.2, 23430, 500, 0.5, 1.2, 0.2, 0.62, 0.00, 1.2, n
;R
46, 55, 65000, 5800, 0.5, 1.2, 0.2, 65000, 1080, 0.5, 1.2, 0.2, 0.62, 0.00, 1.2, n
45, 54, 65000, 5800, 0.5, 1.2, 0.2, 65000, 1080, 0.5, 1.2, 0.2, 0.62, 0.00, 1.2, n
```

shocks3

### CODE REVIEW

**Comment by dohzer** [comment]
I think you might have tagged the wrong person. ;)

**Comment by ulteq** [comment]
> I think you might have tagged the wrong person. ;)

I did, sorry!

**Comment by ulteq** [comment]
> I'm afraid no amount of shocksX complexity would adress all the needs for fine-tuning the suspensions 

I'm pretty sure that there won't be any need for shocks4 in the next decade.

**Comment by dohzer** [comment]
> > I think you might have tagged the wrong person. ;)
> 
> I did, sorry!

No worries. Looks like an interesting game. Might have to give it a go! :)

**Pull request merged**
