### PR TITLE
[WIP] Basic controls editor

### PR DESCRIPTION
**Pull request by tritonas00**
Started a basic controls editor, first tab for now, `EditInputConfig` needs some more work (see comment)

kk

Closes https://github.com/RigsOfRods/rigs-of-rods/issues/1049

### CODE REVIEW

**Comment by only-a-ptr** [comment]
Ideas:
* add escape key handling to close the window instead of pausing the game underneath.
* make this window accessible from main menu, too.
* don't draw the panels by column; draw them line by line.
* create a helper function DrawLine(EV_SOMETHING) which displays one line. Use ImGui::PushID(EV_SOMETHING) to make the edits unique.
* Instead of edit boxes, I'd go for edit buttons and only display the box when actually editing

**Comment by WillMichals** [comment]
Does this pick up controller inputs as well?

**Comment by tritonas00** [comment]
Don't think so

**Comment by only-a-ptr** [comment]
Superseded by #2749

**Pull request closed without merging**
