### PR TITLE
[fix] Added utf-8 sanitization; resolves the inflamous "Bad UTF-8 continuation byte" error.

### LINKED ISSUE #237: Game crashes when opening the ingame settings
When opening the ingame settings, the game will crash. It'll just "stay" in the menu and give me this error:

http://i.imgur.com/iPj9M6H.png

Wich log should I add or just all?

### PR DESCRIPTION
**Pull request by only-a-ptr**
Added full-scale UTF-8 sanitization; no more crashes.
This resolves the inflamous "Bad UTF-8 continuation byte" error dialog. Fixes #237 #385 #664 #455 #364
Incorporated UTFCPP library: (http://utfcpp.sourceforge.net/; License: boost) and added UTF-8 sanitization to all text-file processing.

@InvalidUTF8character: YOU SHALL NOT PASS! :smile:

### CODE REVIEW

**Comment by ulteq** [comment]
Compiles fine, runs fine, looks fine. :+1: 

But I can't test if it resolves those crashes, because I've never had them.

**Comment by only-a-ptr** [comment]
@ulteq At least https://github.com/RigsOfRods/rigs-of-rods/issues/364 has to apply to you too. The truckfile contains non-utf8 characters in 'authors'.

**Comment by Hiradur** [comment]
:+1: 
:name_badge: (boring work hero badge)

**Comment by ulteq** [comment]
I'll test with #364

**Comment by only-a-ptr** [comment]
@ulteq Interesting ... check if the following error appears in your spawner log window:
```
#FF3300 ERROR #FFFFFF (Section globals)
    Line (11): author Lampe flèches -1 dolmen62
    Message: Invalid line, ignoring...
```
The exception comes from MyGUI::UString which is used internally for GUI display. If the regexes don't identify the globals-line as mismatch, the error doesn't display and hence UString never meets the invalid chars.

BTW 4K resolution is sick :smile:

**Comment by ulteq** [comment]
> check if the following error appears in your spawner log

Yes, it does.

**Comment by only-a-ptr** [comment]
> Yes, it does.
Curious. Something's different in UString on your system. :penguin:

**Comment by graysonk95** [comment]
Is there a workaround for this?

I'm stuck in an infinite loop of auto-regen>crash, auto-regen>crash, etc. 0.4.6.0-something, 0.4.7.0-RC1, and 0.4.8.0-NB-131-jdmgmuma all crash on regen with this error.
I tried manually regen'ing in 0.4.0.7, but 0.4.6-0.4.8 insist on doing their own regen, so I'm effectively locked out of all versions of 0.4 because they're all crashing for one reason or another.

**Comment by only-a-ptr** [comment]
@graysonk95 Workaround for the fix? No, it's hardwired. Workaround for the UTF-8 encoding problem? Just fix the content which causes the crash.

If 0.4.7 or older version crashes with this error, file a bug including:
 * RoR.log
 * links to test content.
 * Is there a specific terrain/truck causing this for you?
 * What's your OS/system language? Does your userdir contain special characters? Does filenames of any of your mods contain any special characters?

**Comment by graysonk95** [comment]
@only-a-ptr - The older 0.4 crashes in game because my current truck uses new features it does not like. Irrelevant to this issue.

The newer (and current) 0.4 builds crashed on cache regen seemingly for every single vehicle, RoR.log just started spitting our OGRE Exceptions for every vehicle.
I managed to fix it by removing all content in Documents\Rigs of Rods 0.4 and adding back everything in groups of about 100.
Where before 1 failed cache regen would take like 3-4 minutes, 8 smaller successful cache regens took about 15 seconds each.
I have 7GB of content installed (~800 files), so perhaps it just could not handle everything at once.
That was my workaround.

**Pull request merged**
