### PR TITLE
Fixed issues with special characters in username under MS Windows.

### PR DESCRIPTION
**Pull request by ohlidalp**
Under MS Windows, you can't use naked `fopen()` or `std::fstream` as they don't accept UTF-8 encoded paths with special characters.

As a solution, we use OGRE file system API exclusively.

Components reviewed in this audit:
* Rigs of Rods -- fixed.
* Caelum -- clean.
* PagedGeometry -- clean. There's [one fstream](https://github.com/OGRECave/ogre-pagedgeometry/blob/49d77e95d7aa402aee737c21ac2e8c56174b0e56/source/WindBatchPage.cpp#L212) but only with local path and on error.
* Ogre -- clean with one weak spot: `Ogre::Codec::encodeToFile()` - STB image codec uses `fstream`, FreeImage codec calls [FreeImage_Save()](https://sourceforge.net/p/freeimage/svn/HEAD/tree/FreeImage/trunk/Source/FreeImage/Plugin.cpp#l467) which uses fopen().
* AngelScript -- stock ScriptBuilder uses fopen(), but we override that.

### CODE REVIEW

**Comment by tritonas00** [comment]
Still doesn't load though
kk

**Comment by only-a-ptr** [comment]
o.O Well, that can only mean zziplib (which is behind Ogre::ZipArchive) can't do it. Let me see...

**Comment by tritonas00** [comment]
> o.O Well, that can only mean zziplib (which is behind Ogre::ZipArchive) can't do it. Let me see...
> 
> ... well, no: https://github.com/OGRECave/ogre/blob/master/OgreMain/src/OgreZip.cpp#L106 - the file is opened via `_openFileStream()` helper which exist specifically to resolve the windows unicode problem. I'm baffled.

Wrong code, we use 1.11.6, not latest OGRE master

**Comment by only-a-ptr** [comment]
> Wrong code, we use 1.11.6, not latest OGRE master

True, I should really 💤 instead. 😄

Well, I was right, it uses zzip (master uses assimp) https://github.com/OGRECave/ogre/blob/3fc7c8e8e95204894865576d2b45cd4606d6d262/OgreMain/src/OgreZip.cpp#L182

**Comment by tritonas00** [comment]
Well, we need to move to latest ogre then, advanced a bit https://github.com/tritonas00/rigs-of-rods/commits/ogre-13, following your steps

**Comment by tritonas00** [comment]
> > Wrong code, we use 1.11.6, not latest OGRE master
> 
> True, I should really zzz instead. smile
> 
> Well, I was right, it uses zzip (master uses assimp) https://github.com/OGRECave/ogre/blob/3fc7c8e8e95204894865576d2b45cd4606d6d262/OgreMain/src/OgreZip.cpp#L182
> 
> EDIT: Though zziplib has a complex system of custom file handlers: https://github.com/gdraheim/zziplib/blob/8e10dc825ba37b9a1c9faa684370f6271e33ecbc/zzip/zip.c#L834 ... it's possible I missed some override in OGRE.

Ogre 13 fixes it, just tried, folders/files created successfully

**Comment by ohlidalp** [comment]
Closing as obsolete - all signifficant commits from this PR already made it's way to master.

**Pull request closed without merging**
