### PR TITLE
GUI Overhaul merge

### PR DESCRIPTION
**Pull request by Max98**
Let's hope that this can be merged. 
While syncing with the upstream, I had to fix few conflicts.

So this includes ONLY the GuiOverhaul and all it's new components like the new Console, Notification box, new dashboard, new ingame settings, etc..

### CODE REVIEW

**Comment by Hiradur** [comment]
Did you fix the font problem on Linux?

**Comment by Max98** [comment]
I can't debug the problem on Linux simply because I don't have experience with GCC. It would be great if you could.

**Comment by only-a-ptr** [comment]
Excellent work, Max98!
I'll merge it as soon as I get home

**Comment by Max98** [comment]
I think that we should merge it as soon as we fix the Linux problem. I'll try to compile on Linux and see what I can do.

**Comment by Hiradur** [comment]
It crashes on startup, same as #10 you probably reverted the fix somehow and maybe others as well.
I don't think that gdb will be of much help to find the cause of the font problems. I probably won't be able to take an in-depth look before the weekend.

**Comment by Max98** [comment]
@Hiradur https://github.com/RigsOfRods/rigs-of-rods/issues/10 Yup, looks like it so. I made it so that when you enter ingame, the GUI_Menu gets init'd and when you go back to the menu, it's destroyed. For some reasons, making it invisible doesn't work (It just don't want to go invisible)

**Comment by Hiradur** [comment]
On shutdown I get this sometimes (random, for obvious reasons). I've never seen this with upstream:
```
RoR: ../nptl/pthread_mutex_lock.c:350: __pthread_mutex_lock_full: Assertion `(-(e)) != 3 || !robust' failed.
```

**Comment by Hiradur** [comment]
Alright, I found the cause for the font problem. The properties are missing. With this MyGUI_FontsEnglish.xml it's working but needs fine tuning, characters are thin and hard to read (and I think it still looks different to Windows):
```
<?xml version="1.0" encoding="UTF-8"?>
<MyGUI type="Resource" version="1.1">
	<Resource type="ResourceTrueTypeFont" name="Default">
		<Property key="Source" value="DejaVuSans.ttf"/>
		<Property key="Size" value="12"/>
		<Property key="Resolution" value="50"/>
		<Property key="Antialias" value="true"/>
		<Property key="SpaceWidth" value="4"/>
		<Property key="TabWidth" value="8"/>
		<Property key="CursorWidth" value="2"/>
		<Property key="Distance" value="7"/>
		<Property key="OffsetHeight" value="0"/>
		<Codes>
			<Code range="33 126"/>
			<Code range="1025 1105"/>
			<Code range="8470"/>
			<Code hide="1026 1039"/>
			<Code hide="1104"/>
			<Property key="Resolution" value="50"/>
		</Codes>
	</Resource>
	<Resource type="ResourceTrueTypeFont" name="DefaultBig">
		<Property key="Source" value="DejaVuSans.ttf"/>
		<Property key="Size" value="15"/>
		<Property key="Resolution" value="50"/>
		<Property key="Antialias" value="true"/>
		<Property key="SpaceWidth" value="4"/>
		<Property key="TabWidth" value="8"/>
		<Property key="CursorWidth" value="2"/>
		<Property key="Distance" value="7"/>
		<Property key="OffsetHeight" value="0"/>
		<Codes>
			<Code range="33 126"/>
			<Code range="1025 1105"/>
			<Code range="8470"/>
			<Code hide="1026 1039"/>
			<Code hide="1104"/>
		</Codes>
	</Resource>
	<Resource type="ResourceTrueTypeFont" name="DefaultSmall">
		<Property key="Source" value="DejaVuSans.ttf"/>
		<Property key="Size" value="8"/>
		<Property key="Resolution" value="50"/>
		<Property key="Antialias" value="true"/>
		<Property key="SpaceWidth" value="4"/>
		<Property key="TabWidth" value="8"/>
		<Property key="CursorWidth" value="2"/>
		<Property key="Distance" value="7"/>
		<Property key="OffsetHeight" value="0"/>
		<Codes>
			<Code range="33 126"/>
			<Code range="1025 1105"/>
			<Code range="8470"/>
			<Code hide="128"/>
			<Code hide="1026 1039"/>
			<Code hide="1104"/>
		</Codes>
	</Resource>
</MyGUI>
```

**Comment by Max98** [comment]
They got screw'd up on windows ;(
I'll take a look why tonight.

**Comment by only-a-ptr** [comment]
@Hiradur: I'm also getting random crash on shutdown, caused by collecting joystick input from OIS. Seems like OIS is destroyed too early. However, the root problem is that shutdown code is still left in RoRFrameListener and called from various places.
I'm already tired of this system and the crashes it gives everybody, so here's what I'll do:
1. Create an abstract interface class for MainThread, containing RequestShutdown() function. This will also reduce compile-time dependencies.
2. I'll port all the shutdown code to MainThread.
3. I'll replace all calls to RoRFrameListener->*shutdown*(). 

However, to perform this refactor, I absolutely need Max98's changes already merged.

**Comment by Hiradur** [comment]
> However, to perform this refactor, I absolutely need Max98's changes already merged.

I'm fine with this, the only problem is that without the properties mentioned above the font is super tiny, glitched and missing white spaces on Linux.
@Max98: I realized that there was a <Property key> in the code section of the first <Resource type> in my fix. Must have happened when I copy&pasted it. I removed it from my fix. Just so you know.

**Comment by Max98** [comment]
@Hiradur Tried again and still the same result.

screenshot_8

I'll take a look :p

**Comment by Hiradur** [comment]
It works. Font is still a little small for my taste but at least it looks correct now.

**Comment by Max98** [comment]
Oh, thanks for the idea. I'll try to make the font size changeable ingame. :p²

**Comment by Max98** [comment]
I think that we are ready for the merge.

**Comment by Max98** [comment]
So guys? @Hiradur @only-a-ptr

**Comment by Hiradur** [comment]
Push the button.

**Comment by Max98** [comment]
Done. :)

**Pull request merged**
