### PR TITLE
Incorporated skins to ModCache

### PR DESCRIPTION
**Pull request by only-a-ptr**
Each skin is now a ModCache entry. Cachefile version is 11 and you'll see preview images for skins in the cache folder.

This puts SkinZips back into play after https://github.com/RigsOfRods/rigs-of-rods/pull/2294

There will be glitches.

### CODE REVIEW

**Comment by tritonas00** [comment]
Containers skins still dont work, only the default (blue) works
http://archives.rigsofrods.net/repo/files/repofiles-2nd-batch/041225f1fb96b847c1c2bb03bb94f564054fdf1d_ISOcontainers.zip

**Comment by only-a-ptr** [comment]
All fixed.

NOTE: Container skins are buggy, there are 2 "green weathered" entries, one being actually orange.
Of course, older builds spawned the green texture by chance, whereas my code spawns orange instead 🙄

**Comment by tritonas00** [comment]
Great!
gg

**Comment by tritonas00** [comment]
Another issue found with this PR

Load a map with truck shop spawners (like nhelens) and spawn a vehicle using the truck shop spawner
Remove it, go somewhere else and spawn a vehicle again
It should spawn in the position you are currently are, but instead it spawns in the truck shop spawner

**Comment by CuriousMike56** [comment]
The issues with the Viper skinzip should now be fixed: https://forum.rigsofrods.org/resources/1996-dodge-viper-gts-coupe.88/updates

**Comment by only-a-ptr** [comment]
@tritonas00 spawn position bug fixed

**Comment by tritonas00** [comment]
will test tomorrow, but probably its fine.

**Comment by tritonas00** [comment]
Another issue, agora style huds went crazy again
Master:
before
This PR:
after

**Comment by tritonas00** [comment]
And we have a segfault loading ZIL-135 Uragan skins
```
Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
ActorSpawner::ProcessExhaust (this=this@entry=0x7fffffffd780, def=...) at /usr/include/c++/8.2.1/bits/shared_ptr_base.h:998
998	      _M_get() const noexcept
(gdb) bt
#0  ActorSpawner::ProcessExhaust (this=this@entry=0x7fffffffd780, def=...) at /usr/include/c++/8.2.1/bits/shared_ptr_base.h:998
#1  0x0000555555857e3b in ActorSpawner::SpawnActor (this=this@entry=0x7fffffffd780)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/RigSpawner_ProcessControl.cpp:346
#2  0x000055555581d51b in RoR::ActorManager::SetupActor (this=<optimized out>, actor=0x55555e589b70, rq=..., def=
    std::shared_ptr<RigDef::File> (use count 6, weak count 0) = {...})
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/BeamFactory.cpp:118
#3  0x000055555581eb54 in RoR::ActorManager::CreateActorInstance (this=this@entry=0x7fffffffe458, rq=..., 
    def=std::shared_ptr<RigDef::File> (use count 6, weak count 0) = {...}) at /usr/include/c++/8.2.1/bits/basic_string.h:936
#4  0x0000555555655800 in SimController::SpawnActorDirectly (this=0x7fffffffe430, rq=...) at /usr/include/c++/8.2.1/bits/basic_string.h:936
#5  0x00005555556606f9 in SimController::UpdateSimulation (this=0x7fffffffe430, dt=0.0101674227) at /usr/include/c++/8.2.1/bits/basic_string.h:936
#6  0x000055555566175b in SimController::EnterGameplayLoop (this=this@entry=0x7fffffffe430)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gameplay/RoRFrameListener.cpp:2257
#7  0x000055555560a48a in main (argc=<optimized out>, argv=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/main.cpp:349
```

**Comment by only-a-ptr** [comment]
@tritonas00 ZIL Uragan works now, tested with "Hello Kitty" skin

**Pull request merged**
