### PR TITLE
Script editor

### PR DESCRIPTION
**Pull request by ohlidalp**
Script writing is powerful but clumsy:
  1. edit in external editor, save to Documents\My Games\Rigs of Rods\scripts
  2. switch to RoR, either type `loadscript ...` to console or use ScriptMonitor menu to Load/Reload the script
  3. if there's an error, switch to Angelscript.log and figure the error
  4. repeat

To make scripting fun, the dev/test cycle needs to be quick and comfy. So we needed an ingame editor with a "(RE)START" button and error reporting. 

**Behold the 'script_editor.as' AngelScript editor written in AngelScript:**

obrazek

At the moment it's somewhat glitchy but the START/STOP button works perfectly. It relies entirely on `ImGui::InputTextMultiline()`, errors and syntax highlight is done by overdrawing. The numbers are: line number, line length, comment offset, num errors - most are not useful but look cool, you can disable them in the View menu.

Update: yes, the hyperlink opens the default browser (only tested on Win10).
obrazek

Update2: added `game.findResourceFileInfo()` which lists files in pre-defined resource groups. This allowed me to list up files in user's 'scripts' dir:
obrazek

### CODE REVIEW

**Comment by only-a-ptr** [comment]
I'm getting ahead of myself... but just a little. 

BTW is it weird to run a physics sandbox game just to make and use your own text editor in there? 😅 

obrazek

**Comment by AnotherFoxGuy** [comment]
I just tested this, and one crash that I found is that if you try and load a script from a terrain folder the game crashes

**Comment by only-a-ptr** [comment]
I just realized I'm not nearly done here, so I've converted this to draft.

@AnotherFoxGuy Probably an uncaught exception. I just added an exception-reporting event type, but I need to manually wrap all troublesome funcs. The `save/loadStringResource()` aren't wrapped yet.

I just added an API giving script info - I need it to make nice exception window, and also to tell which exceptions belong to who - the editor needs to catch all so it can diagnose it's guest script.
obrazek

**Comment by only-a-ptr** [comment]
If this isn't cool, IDK what is 😎 
obrazek

**Comment by only-a-ptr** [comment]
@AnotherFoxGuy I can't seem to reproduce the crash you mentioned.
obrazek

**Comment by only-a-ptr** [comment]
Latest development: :angel:script bindings of [OGRE overlay system](https://ogrecave.github.io/ogre/api/latest/_the-_core-_objects.html#Overlays) and a prototype editor script allowing you to add/edit/delete elements and export [OGRE's .overlay script files.](https://ogrecave.github.io/ogre/api/latest/_overlay-_scripts.html). Also the editor now has tabs and autosave.
image

**Comment by CuriousMike56** [comment]
Might be a silly question, but how exactly do you access the editor? I don't see any option for it in console:
image

**Review by CuriousMike56 — APPROVED** [review]
Seems to work fine, though my knowledge with scripting is quite limited. A search feature and the ability to duplicate a line (CTRL+D in Notepad++) would be nice, but those could come later.

**Comment by ohlidalp** [comment]
Shamelessly pinning an image of the latest editor version:
image

**Pull request merged**
