### PR TITLE
Added water options to 'TopMenubar/Settings' menu.

### PR DESCRIPTION
**Pull request by ohlidalp**
I tried to investigate #3137 but got nothing. So I at least analyzed the water code and added UI for tweaking HydraX water.

Both basic water with waves and HydraX water boil down to the same thing: a dynamic grid-mesh updated in code. The only major difference is how the waves are calculated: Basic uses configurable "wave trains", HydraX uses Perlin noise with adjustable params (via .hdx config file). Since both systems are in our codebase, it would make sense to unify them. To better understand how the system operates, I added the UI.

obrazek

### CODE REVIEW

**Comment by ohlidalp** [comment]
I got curious if I could change water type in-game by simply destroying the water subsystem and initing it again. Well, it works
obrazek
Also waves are now toggleable there, that was already possible before just the UI was missing.

**Comment by ohlidalp** [comment]
I've bumped this PR with one small fix. I couldn't fix the glitch but I got closer, see https://github.com/RigsOfRods/rigs-of-rods/issues/3137#issuecomment-2198713608

**Comment by CuriousMike56** [comment]
https://github.com/user-attachments/assets/bd206bed-b3f2-4e6e-8fd3-19216269e361

Switching between reflection water types often results in white, and Hydrax always crashes:

RoR_2024-08-06_01-58-00

The options remain shown when on a terrain that doesn't feature water (but doesn't do anything besides crash without error if Hydrax is selected)

Real time waves adjustment is fun though 😄

**Comment by ohlidalp** [comment]
Looks like something isn't cleaned up properly and then duplicates and breaks. Might also be Cg or Ogre bug.

**Comment by ohlidalp** [comment]
@CuriousMike56 I tried only under Dx9 and didn't see the white surfaces... but I got a lot of other glitches/crashes. I fixed switching between all modes except Hydrax which still crashes when toggled the 2nd time.

**Comment by CuriousMike56** [comment]
Looks like the white surfaces are gone now. 

Hydrax options seem to do nothing:

https://github.com/user-attachments/assets/4f2e6275-b3b8-402b-8f35-e736c2513195

Switching to Hydrax results in visual glitches:

https://github.com/user-attachments/assets/27d445fe-9592-49ed-aef7-bf77e4a9bd13

And finally, basic water visuals freeze if waves are disabled:

https://github.com/user-attachments/assets/a795d4d6-4f82-4dee-963f-f3f68356bd7d

**Comment by ohlidalp** [comment]
I fixed HydraX crashing on nd activation, but now it seems to hang when returning to menu >:/

**Comment by CuriousMike56** [comment]
It may be best to just not include Hydrax for now (or hide it behind a setting), its visuals are still busted for me:
RoR_2024-09-19_03-25-58

**Comment by ohlidalp** [comment]
Done. HydraX excluded from the top menubar dropdown. I'll continue fixing it after OGRE13+ port.
obrazek
obrazek

**Comment by CuriousMike56** [comment]
- The options appear on terrains that don't feature water, changing mode there does nothing (would be fun to enable water on these maps though)
image
- Returning to menu crashes with Hydrax enabled
- Hydrax sliders have too much range IMO, it's easy to create horrors and tank your frame rate:
RoR_2024-09-22_21-50-00
Grid complexity should max at 500, and strength/elevation at 25.

**Comment by ohlidalp** [comment]
Closing until OGRE14 port... too much garbage. There are 2 outstanding issues:
*  load map with water, return to menu and load a different map also with water, game hangs/crashes: https://discord.com/channels/136544456244461568/189904947649708032/1289036836139958352
* returning to menu with hydrax enabled still crashes https://discord.com/channels/136544456244461568/189904947649708032/1289034862056964097

**Pull request closed without merging**
