### PR TITLE
Greatest code tidy-up ever (dev-master-v4)

### PR DESCRIPTION
**Pull request by only-a-ptr**
A very long series of code cleanups and other internal improvements. See https://forum.rigsofrods.org/development-discussion/189-developer-suffering-release-block.html

Changes:
* Class `Beam` (representing a softbody object, usually a vehicle) renamed to `Actor` - for reasoning, see https://forum.rigsofrods.org/development-discussion/159-enter-codebase.html#post1281
* Class `rig_t` (previously inherited by Beam) was merged with `Actor`
* Class `BeamFactory` renamed to `ActorManager`
* Class `RigSpawner` renamed to `ActorSpawner`
* Class `RoRFrameListener` renamed to `SimController` - because it won't be implementing RoR::FrameListener for much longer, that design is legacy. See https://forum.rigsofrods.org/development-discussion/159-enter-codebase.html#post1301 - section 'my ideal concept'

Performance and functionality should not be affected. I just want these code changes in upstream so I can build upon them.

### CODE REVIEW

**Comment by tritonas00** [comment]
this is going to hurt...

**Comment by tritonas00** [comment]
Doesn't compile here: https://pastebin.com/s72fNvJt

**Comment by only-a-ptr** [comment]
I fixed nothing and added some more refactors 😄 

@Michael10055: I can't reproduce either of those issues. I tried "Arcade Controls" on/off,  but keyboard acc/brake/steering works just fine. DAF semi removes cleanly, too. Post RoR.log pls.

@tritonas00 Working on it...

**Comment by tritonas00** [comment]
Adding `struct timeval start;` just before:

https://github.com/only-a-ptr/rigs-of-rods/blob/8b1acc830d1f99af54e4ac85c144f37d554299e8/source/main/utils/Timer.h#L32
https://github.com/only-a-ptr/rigs-of-rods/blob/8b1acc830d1f99af54e4ac85c144f37d554299e8/source/main/utils/Timer.h#L56
and
https://github.com/only-a-ptr/rigs-of-rods/blob/8b1acc830d1f99af54e4ac85c144f37d554299e8/source/main/utils/Timer.h#L70

fixes the 'start' errors

**Comment by tritonas00** [comment]
replacing https://github.com/only-a-ptr/rigs-of-rods/blob/8b1acc830d1f99af54e4ac85c144f37d554299e8/source/main/physics/RigSpawner.cpp#L1563 with:

`m_actor->m_buoyance=std::unique_ptr<Buoyance>(new Buoyance (dustman.getDustPool("splash"), dustman.getDustPool("ripple")));`

fixes the error and finally i can compile this pr

**Comment by only-a-ptr** [comment]
> @tritonas00 `m_actor->m_buoyance=std::unique_ptr<Buoyance>`

There's something outdated about your compiler :smile:

> @tritonas00 `struct timeval start;`

I dunno why it compiled until now, but I'm in the process of removing Timer.h/cpp and the `BES_*` statistics altogether - it's a lot of unmaintained dirty code and the stats it would generate are useless anyway, see my forum rants on architecture. Further, there are neat libraries for this, such as https://github.com/Celtoys/Remotery and https://github.com/jonasmr/microprofile (@AnotherFoxGuy alredy works with this)

@tritonas00 Thanks for all the testing, I'll look into it on friday latest.

**Comment by Michael10055** [comment]
@only-a-ptr Keyboard steering works if I unplug my controller.
Full log:
https://pastebin.com/DKzNCs8Q

**Comment by only-a-ptr** [comment]
I rebased the branch on current upstream.

@Michael10055 I backed out the changes to InputManager - your controls should work fine now

**Comment by only-a-ptr** [comment]
I rebased the branch on current upstream.

@Michael10055 I backed out the changes to InputManager - your controls should work fine now

@tritonas00  I avoided the `std::make_unique` construct altogether, looks like it's too tricky for me: https://stackoverflow.com/questions/37995745/expected-primary-expression-before-token - you should compile just fine now.

**Comment by tritonas00** [comment]
> you should compile just fine now

Indeed, thanks! Crashes are still there though

**Comment by only-a-ptr** [comment]
I've been sick the past 2 weeks, getting better now.
I tested and fixed the DAF-semi scenario which turned out to be a major typo in vehicle management - it probably fixes more crashes than one.

**Comment by Michael10055** [comment]
That sucks, hope you get well soon.

In the meantime, tracked vehicles (such as this one https://forum.rigsofrods.org/downloads.php?do=file&id=172) are currently broken:
screenshot_2018-04-16_14-55-55_1

**Comment by only-a-ptr** [comment]
@Michael10055 I fixed the SlideNode-based tracked vehicles (modified history) and rebased everything on top of current upstream.
@AnotherFoxGuy I'll look into that next.

**Comment by only-a-ptr** [comment]
AppVeyor build seems to be broken at the moment (see https://github.com/RigsOfRods/rigs-of-rods/issues/1510) so I'm ignoring it's result and merging. Travis built fine.

**Pull request merged**
