### PR TITLE
🔧 Separate libraries from the source code

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
This fixes the issue with documentation from 3rd party libs showing up in the source code documentation (Example: https://rigs-of-rods-source-docs.netlify.app/tut4.html)

Also switched to the header-only version of moFileReader
Let me know if this causes any issues with compiling or running the game

### CODE REVIEW

**Comment by tritonas00** [comment]
```
git clone --recursive https://github.com/AnotherFoxGuy/rigs-of-rods -b external
cmake -DCMAKE_PREFIX_PATH=/home/babis/Downloads/ror-dependencies/Dependencies_Linux/ -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_PACKAGE_MANAGER=OFF -DROR_USE_GOOGLETEST=OFF -DUSE_DISCORD_RPC=OFF .
make -j6
```
Got

```
[ 15%] Building CXX object source/main/CMakeFiles/RoR.dir/audio/MumbleIntegration.cpp.o
In file included from /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/scripting/ScriptEngine.h:33,
                 from /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/main.cpp:48:
/home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/scripting/GameScript.h:31:10: fatal error: scriptdictionary/scriptdictionary.h: No such file or directory
   31 | #include <scriptdictionary/scriptdictionary.h>
   ```

**Comment by AnotherFoxGuy** [comment]
@tritonas00 I forgot to update a `target_include_directories` variable, it should be fixed now

**Comment by tritonas00** [comment]
works fine now :+1:

**Comment by only-a-ptr** [comment]
I like the looks of it, will test ASAP.

BTW who's managing the https://rigs-of-rods-source-docs.netlify.app/tut4.html site?

**Comment by AnotherFoxGuy** [comment]
> BTW who's managing the rigs-of-rods-source-docs.netlify.app site?

I do, it is being built from this branch: https://github.com/AnotherFoxGuy/rigs-of-rods/tree/deploy-docs
I update it once a month

**Review by tritonas00 — APPROVED** [review]

**Review by only-a-ptr — APPROVED** [review]
Works OK and I like the way things are organized.

However, the visual studio project files are a mess now. The "build\Rigs_of_Rods.sln" is gone, there is "build\source\main\RoR_main.sln" now. I can live with that, but it's annoying that RoR_main.sln no longer contains "zip_and_copy_resources" project. Several of my working branches have modified resources, so I run this quite frequently.

Anyway, I'm fine with merging this now and polishing later.

**Pull request merged**
