### PR TITLE
Fixed gcc warning

### PR DESCRIPTION
**Pull request by tritonas00**
Lately gcc complains:

```
[ 41%] Building CXX object source/main/CMakeFiles/RoR.dir/physics/flex/FlexMeshWheel.cpp.o
/home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/flex/FlexMeshWheel.cpp: In constructor ‘RoR::FlexMeshWheel::FlexMeshWheel(Ogre::Entity*, RoR::GfxActor*, int, int, int, int, const std::string&, const std::string&, float, bool)’:
/home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/flex/FlexMeshWheel.cpp:86:38: warning: argument 1 value ‘1844674407370955155 ’ exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
   86 |     m_indices=(unsigned short*)malloc(m_index_count*sizeof(unsigned short));
      |                                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/12.1.0/cstdlib:75,
                 from /usr/include/c++/12.1.0/ext/string_conversions.h:41,
                 from /usr/include/c++/12.1.0/bits/basic_string.h:3960,
                 from /usr/include/c++/12.1.0/string:53,
                 from /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/phc.h:25,
                 from /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/CMakeFiles/RoR.dir/cmake_pch.hxx:5,
                 from <command-line>:
/usr/include/stdlib.h:540:14: note: in a call to allocation function ‘void* malloc(size_t)’ declared here
  540 | extern void *malloc (size_t __size) __THROW __attribute_malloc__
      |              ^~~~~~
```

I don't know if this is the correct way to fix it but it suppress the warning.

### CODE REVIEW

**Review by only-a-ptr — CHANGES_REQUESTED** [review]
Nope, not correct. Your're basically clamping the flexbodywheel mesh to maximum of 65536 bytes of index buffer, which means circa 10k triangles max. That's actually a reasonable limit and the hardware prefers that, but the problem in the crash report is that somehow we tried to allocate some 30 trillion of triangles, which is nonsense, so there must be a bug earlier up the pipe.

I'd do this:
```
if (m_index_count*sizeof(unsigned short) > std::numeric_limits<unsigned short>::max())
{
  // log error and bail.
}
```

**Comment by ohlidalp** [comment]
I'm sure this isn't true anymore.

**Comment by tritonas00** [comment]
> I'm sure this isn't true anymore.

The warning still appears, on Lunix, gcc

**Comment by ohlidalp** [comment]
OK, let me try to stuff `vector<>` in there...

**Comment by ohlidalp** [comment]
@tritonas00 Try again please. GitHub won't let me request your review since it's your PR 😆

**Comment by tritonas00** [comment]
No warnings :+1:

**Pull request merged**
