### PR TITLE
🔨 CMake buildsystem overhaul 

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
Yes, it is that time of the year again to do an overhaul of the cmake buildsystem

Features:
* Unified the dependencies in one file, this makes it easier to see what versions are being used
* On-demand fallback on Conan <sup>1</sup>
* Improved support for building without Conan
* Added support for finding dependencies with pkg-config
* Removed the pmm cmake-module

<hr>

<sup>1</sup> Setting the cmake option `ROR_LIB_PREFERENCE` to `SYSTEM` will search the system first for dependencies, and then fall back on the Conan package if it hasn't been found

### CODE REVIEW

**Comment by tritonas00** [comment]
```
Consolidate compiler generated dependencies of target alrecord
[100%] Built target alrecord
[ 21%] Performing install step for 'openal'
[  0%] Built target build_version
[  8%] Built target common
[ 13%] Built target alsoft-config
[ 77%] Built target OpenAL
[ 79%] Built target uhjencoder
In file included from /home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/IlmImf/ImfHeader.h:51,
                 from /home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/FreeImage/../OpenEXR/IlmImf/ImfOutputFile.h:46,
                 from /home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/FreeImage/PluginEXR.cpp:27:
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:227:41: error: ISO C++17 does not allow dynamic exception specifications
  227 |     const Vec2 &        normalizeExc () throw (Iex::MathExc);
      |                                         ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:231:48: error: ISO C++17 does not allow dynamic exception specifications
  231 |     Vec2<T>             normalizedExc () const throw (Iex::MathExc);
      |                                                ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:439:41: error: ISO C++17 does not allow dynamic exception specifications
  439 |     const Vec3 &        normalizeExc () throw (Iex::MathExc);
      |                                         ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:443:48: error: ISO C++17 does not allow dynamic exception specifications
  443 |     Vec3<T>             normalizedExc () const throw (Iex::MathExc);
      |                                                ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:621:37: error: ISO C++17 does not allow dynamic exception specifications
  621 |     const Vec4 &    normalizeExc () throw (Iex::MathExc);
      |                                     ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:625:44: error: ISO C++17 does not allow dynamic exception specifications
  625 |     Vec4<T>         normalizedExc () const throw (Iex::MathExc);
      |                                            ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:713:30: error: ISO C++17 does not allow dynamic exception specifications
  713 | Vec2<short>::normalizeExc () throw (Iex::MathExc);
      |                              ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:722:37: error: ISO C++17 does not allow dynamic exception specifications
  722 | Vec2<short>::normalizedExc () const throw (Iex::MathExc);
      |                                     ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:737:28: error: ISO C++17 does not allow dynamic exception specifications
  737 | Vec2<int>::normalizeExc () throw (Iex::MathExc);
      |                            ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:746:35: error: ISO C++17 does not allow dynamic exception specifications
  746 | Vec2<int>::normalizedExc () const throw (Iex::MathExc);
      |                                   ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:761:30: error: ISO C++17 does not allow dynamic exception specifications
  761 | Vec3<short>::normalizeExc () throw (Iex::MathExc);
      |                              ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:770:37: error: ISO C++17 does not allow dynamic exception specifications
  770 | Vec3<short>::normalizedExc () const throw (Iex::MathExc);
      |                                     ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:785:28: error: ISO C++17 does not allow dynamic exception specifications
  785 | Vec3<int>::normalizeExc () throw (Iex::MathExc);
      |                            ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:794:35: error: ISO C++17 does not allow dynamic exception specifications
  794 | Vec3<int>::normalizedExc () const throw (Iex::MathExc);
      |                                   ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:808:30: error: ISO C++17 does not allow dynamic exception specifications
  808 | Vec4<short>::normalizeExc () throw (Iex::MathExc);
      |                              ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:817:37: error: ISO C++17 does not allow dynamic exception specifications
  817 | Vec4<short>::normalizedExc () const throw (Iex::MathExc);
      |                                     ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:832:28: error: ISO C++17 does not allow dynamic exception specifications
  832 | Vec4<int>::normalizeExc () throw (Iex::MathExc);
      |                            ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:841:35: error: ISO C++17 does not allow dynamic exception specifications
  841 | Vec4<int>::normalizedExc () const throw (Iex::MathExc);
      |                                   ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:1211:26: error: ISO C++17 does not allow dynamic exception specifications
 1211 | Vec2<T>::normalizeExc () throw (Iex::MathExc)
      |                          ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:1248:33: error: ISO C++17 does not allow dynamic exception specifications
 1248 | Vec2<T>::normalizedExc () const throw (Iex::MathExc)
      |                                 ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:1703:26: error: ISO C++17 does not allow dynamic exception specifications
 1703 | Vec3<T>::normalizeExc () throw (Iex::MathExc)
      |                          ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:1742:33: error: ISO C++17 does not allow dynamic exception specifications
 1742 | Vec3<T>::normalizedExc () const throw (Iex::MathExc)
      |                                 ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:2108:26: error: ISO C++17 does not allow dynamic exception specifications
 2108 | Vec4<T>::normalizeExc () throw (Iex::MathExc)
      |                          ^~~~~
/home/babis/Downloads/ror-dependencies/Source/ogredeps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:2149:33: error: ISO C++17 does not allow dynamic exception specifications
 2149 | Vec4<T>::normalizedExc () const throw (Iex::MathExc)
      |                                 ^~~~~
[ 81%] Built target openal-info
[ 82%] Built target uhjdecoder
```

**Comment by tritonas00** [comment]
```
git clone --recursive https://github.com/AnotherFoxGuy/rigs-of-rods -b build-sys-V3
cd rigs-of-rods
cmake -DCMAKE_PREFIX_PATH=/home/babis/Downloads/ror-dependencies/Dependencies_Linux/ -DCMAKE_BUILD_TYPE=RelWithDebInfo .
```

```
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using conan: OFF
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.7.3") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OGRE
--   static     : OFF
--   components : Bites;HLMS;MeshLodGenerator;Overlay;Paging;Property;RTShaderSystem;Terrain
--   plugins    : Plugin_CgProgramManager;Plugin_OctreeSceneManager;Plugin_ParticleFX;RenderSystem_GL;Codec_STBI;Codec_FreeImage;Codec_EXR
--   media      : /home/babis/Downloads/ror-dependencies/Dependencies_Linux/share/OGRE/Media
-- Using 'OGRE' system library (Found by find_package)
-- Checking for module 'openal >= 1.18'
--   Found openal , version 1.21.1
-- Using 'OpenAL' system library (Found by pkg_config)
-- Added inteface OpenAL::OpenAL /home/babis/Downloads/ror-dependencies/Dependencies_Linux/include;/home/babis/Downloads/ror-dependencies/Dependencies_Linux/include/AL /home/babis/Downloads/ror-dependencies/Dependencies_Linux/lib/libopenal.so
-- Checking for module 'ois >= 1.4'
--   Package 'ois', required by 'virtual:world', not found
-- Looking for OIS...
-- OIS_PREFIX_PATH changed.
-- Checking for module 'OIS'
--   Package 'OIS', required by 'virtual:world', not found
-- Found OIS: /home/babis/Downloads/ror-dependencies/Dependencies_Linux/lib/libOIS.so
-- Using 'OIS' system library (Found by find_package)
-- Found MyGUI: /home/babis/Downloads/ror-dependencies/Dependencies_Linux/include/MYGUI  
-- Using 'MyGUI' system library (Found by find_package)
-- Checking for module 'socketw >= 3.10'
--   Package 'socketw', required by 'virtual:world', not found
-- Found SocketW: /home/babis/Downloads/ror-dependencies/Dependencies_Linux/include  
-- Using 'SocketW' system library (Found by find_package)
-- Found AngelScript: /home/babis/Downloads/ror-dependencies/Dependencies_Linux/include  
-- Using 'AngelScript' system library (Found by find_package)
-- Checking for module 'libcurl >= 7.6'
--   Found libcurl , version 7.78.0
-- Using 'CURL' system library (Found by pkg_config)
-- Added inteface CURL::libcurl  /usr/lib/libcurl.so
-- Found Caelum: /home/babis/Downloads/ror-dependencies/Dependencies_Linux/include/Caelum  
-- Using 'Caelum' system library (Found by find_package)
-- Could NOT find PagedGeometry (missing: PagedGeometry_INCLUDE_DIRS PagedGeometry_LIBRARIES) 
CMake Error at cmake/DependenciesFunctions.cmake:164 (message):
  Failed to find the system package PagedGeometry
Call Stack (most recent call first):
  cmake/DependenciesConfig.cmake:66 (add_external_lib)
  CMakeLists.txt:111 (include)


-- Configuring incomplete, errors occurred!
See also "/home/babis/Downloads/ror-dependencies/rigs-of-rods/CMakeFiles/CMakeOutput.log".
See also "/home/babis/Downloads/ror-dependencies/rigs-of-rods/CMakeFiles/CMakeError.log"
```

**Comment by AnotherFoxGuy** [comment]
> Did you remove the PagedGeometry submodule?

Yes, PagedGeometry got moved back into its own package since I don't see a benefit to having it vendored

**Comment by tritonas00** [comment]
Ok then i will re add it in ror-dependencies.

**Comment by tritonas00** [comment]
OK i added it but now i get

```-- Could NOT find discord_rpc (missing: discord_rpc_INCLUDE_DIRS discord_rpc_LIBRARIES) 
CMake Error at cmake/DependenciesFunctions.cmake:164 (message):
  Failed to find the system package discord_rpc
Call Stack (most recent call first):
  cmake/DependenciesConfig.cmake:81 (add_external_lib)
  CMakeLists.txt:111 (include)
```

Shouldn't this be optional?

**Comment by AnotherFoxGuy** [comment]
It is optional, the option to disable it is now called `ROR_USE_DISCORD_RPC`

**Comment by tritonas00** [comment]
OK compiled, but it ended up with wrong `plugin.cfg` 

It should be 

`PluginFolder= /home/babis/Downloads/ror-dependencies/Dependencies_Linux/lib/OGRE`

but it was 

`PluginFolder=.`

And caelum plugin line missing

**Comment by AnotherFoxGuy** [comment]
> And caelum plugin line missing

That is because paroj dropped the Plugin API 
https://github.com/OGRECave/ogre-caelum/commit/70bebc7e28bdb92d58664378056fc9705bdbbf1c

**Comment by tritonas00** [comment]
> > And caelum plugin line missing
> 
> That is because paroj dropped the Plugin API
> [OGRECave/ogre-caelum@70bebc7](https://github.com/OGRECave/ogre-caelum/commit/70bebc7e28bdb92d58664378056fc9705bdbbf1c)

Thats an issue, user ends up with this:

screenshot_2021-08-09_15-38-21_1

Please re add the lines.

**Comment by AnotherFoxGuy** [comment]
> Please re add the `libCaelum.so` plugin lines, it worked fine so far

This should be fixed now, could you test this PR again?

**Comment by tritonas00** [comment]
Works fine now. I would wait a bit until Petr finishes his work for the release, then merge.

**Review by tritonas00 — APPROVED** [review]

**Comment by only-a-ptr** [comment]
I'm getting
```
ERROR: Unable to find 'ogre3d-pagedgeometry/1.2.1@anotherfoxguy/stable' in remotes
```
What I did:
1. Update: conan >>  1.40.2, cmake >>  3.21.3, visual studio >> 16.11.3
2. >conan remove -f *
3. >conan remote clean
4. >conan remote add conancenter https://center.conan.io
5. >cmake -S "C:\Users\Petr\source\rigs-of-rods" -B "C:\Users\Petr\builds\rigs-of-rods" -G "Visual Studio 16 2019" -A "x64"

**Comment by AnotherFoxGuy** [comment]
@only-a-ptr That issue should be fixed now, I changed the ogre3d-* conan package versions to the correct versions

**Review by only-a-ptr — APPROVED** [review]
Builds and runs fine.

**Comment by tritonas00** [comment]
@AnotherFoxGuy 

Tried with conan also on Arch, builds fine i had to manually install freeimage though because:
```
./RoR: error while loading shared libraries: libfreeimage.so.3: cannot open shared object file: No such file or directory
```
after installed it runs fine.

**Comment by only-a-ptr** [comment]
I also have an issue with the Caelum daytime slider - it moves in 5 discrete steps instead of smoothly. This is most certainly an imgui issue, not Caelum issue.

Another oddity I observed is that each tab in the Settings UI now displays a tooltip with it's name.

**Review by tritonas00 — CHANGES_REQUESTED** [review]
To clarify the caelum issue:

- It doesn't happen on master (neither conan or ror-dependencies)
- It doesn't happen with this PR and ror-dependencies
- It happens with this PR and conan

**Comment by AnotherFoxGuy** [comment]
@tritonas00 Does the same issue happens with upstream caelum and ror-dependencies?
(https://github.com/OGRECave/ogre-caelum this one)

**Comment by tritonas00** [comment]
> @tritonas00 Does the same issue happens with upstream caelum and ror-dependencies? (https://github.com/OGRECave/ogre-caelum this one)

Yes thats it, it happens with the OGRECave one, https://github.com/RigsOfRods/ogre-caelum doesnt have the issue

**Comment by tritonas00** [comment]
Caelum works fine now :+1:

**Comment by tritonas00** [comment]
Another issue, the scriptlexer patch is missing:
screenshot_2021-10-01_16-22-17_1

**Comment by AnotherFoxGuy** [comment]
>  the scriptlexer patch is missing:

That issue has been fixed here: https://github.com/AnotherFoxGuy/ror-conan-recipes/commit/a65b64c7c47a2e3953ad8253107ca45dcd3d60b4

**Comment by tritonas00** [comment]
Downloaded the gh action build, now gives:
```
FATAL ERROR: An internal error occured in Rigs of Rods.

Technical details below: 

No render system plugin available. Check your plugins.cfg

InvalidStateException: Cannot initialise - no render system has been selected. in Root::initialise at /home/runner/.conan/data/ogre3d/1.11.6.1/anotherfoxguy/stable/build/feae01c5ea595a814bc5825447abdab1e39d6062/OgreMain/src/OgreRoot.cpp (line 542)


FATAL ERROR: An internal error occured in Rigs of Rods.

Technical details below: 

InvalidStateException: Cannot initialise - no render system has been selected. in Root::initialise at /home/runner/.conan/data/ogre3d/1.11.6.1/anotherfoxguy/stable/build/feae01c5ea595a814bc5825447abdab1e39d6062/OgreMain/src/OgreRoot.cpp (line 542)
```

It used to run fine before, plugins.cfg looks ok though:
```
# Defines plugins to load

# Define plugin folder
PluginFolder=lib

# Define plugins
Plugin=Codec_FreeImage
# Plugin=RenderSystem_Direct3D9
# Plugin=RenderSystem_Direct3D11
Plugin=RenderSystem_GL
# Plugin=RenderSystem_GL3Plus
Plugin=Plugin_ParticleFX
Plugin=Plugin_OctreeSceneManager
Plugin=Plugin_CgProgramManager
Plugin=libCaelum.so
```

**Comment by tritonas00** [comment]
Works fine now:
screenshot_2021-10-06_20-49-00_1

**Pull request merged**
