### PR TITLE
Always log CURL error string

### PR DESCRIPTION
**Pull request by only-a-ptr**
At one moment the server had a certificate expired and I realized the game doesn't log anything useful in that situation. The HTTP response code remains '0' in those cases.

Seeing all the copy-pasted and mostly identical `curl_easy*()` calls, I should probably create a helper for it, but at the moment I just uniformly extended all the occurences with an error logging code.

### CODE REVIEW

**Comment by CuriousMike56** [comment]
Good time to test this as the repo API is currently broken:
`15:32:52: [RoR|Repository] Failed to retrieve repolist; Error: 'SSL peer certificate or SSH remote key was not OK'; HTTP status code: 0`
Could the error be added to the UI? Right now it just says 
image

**Comment by tritonas00** [comment]
> Good time to test this as the repo API is currently broken: `15:32:52: [RoR|Repository] Failed to retrieve repolist; Error: 'SSL peer certificate or SSH remote key was not OK'; HTTP status code: 0` Could the error be added to the UI? Right now it just says image

I don't think the player needs to know if the cert expired or any verbose info in general, thats why i texted it like that.

**Comment by Zentro** [comment]
> > Good time to test this as the repo API is currently broken: `15:32:52: [RoR|Repository] Failed to retrieve repolist; Error: 'SSL peer certificate or SSH remote key was not OK'; HTTP status code: 0` Could the error be added to the UI? Right now it just says image
> 
> I don't think the player needs to know if the cert expired or any verbose info in general, thats why i texted it like that.

I think its useful information to include. Maybe just a server error code 4xx or 5xx, just something to indicate with a bit more information when someone posts a screenshot of an issue they have.

**Comment by tritonas00** [comment]
Eitherway its just a matter of seconds to do it, all info is there.

**Comment by only-a-ptr** [comment]
Thanks for the input. I think it should at least say "Server error, ask support" instead. Some detail below in darkened text can't hurt either

**Comment by only-a-ptr** [comment]
It now displays CURL error under the title, and if HTTP code is valid, it's also displayed.
obrazek

**Pull request merged**
