### PR TITLE
Hotfixes

### PR DESCRIPTION
**Pull request by only-a-ptr**
4 unrelated UX improvements.

"Fresh" category restored to orig. formula: max 1 day since install.

### CODE REVIEW

**Review by WillyB1337 — APPROVED** [review]

**Comment by only-a-ptr** [comment]
> @tritonas00 Can you also do something about the Unsorted selector category? The count number appears correct but it actually shows all mods

Fixed. Good spot.

**Comment by tritonas00** [comment]
Great! Found another one. Load a map, open selector, select Aircraft category. Go to main menu, load map again, open selector:

kk

**Comment by only-a-ptr** [comment]
> @tritonas00 Found another one. Load a map, open selector, select Aircraft category, press Cancel. Go to main menu, load map again, open selector:

Fixed

**Review by Zentro — APPROVED** [review]

**Comment by tritonas00** [comment]
will check in the week, meanwhile please check all categories if they behave correctly, not only aircraft, others had issues too

**Comment by tritonas00** [comment]
Its good. One more thing. Open selector, select a category (Aircraft) and press the category menu again -> Fresh category from X number (5 here) went to 0.

**Comment by only-a-ptr** [comment]
> @tritonas00 One more thing. Open selector, select a category (Aircraft) and open the category menu again -> Fresh category from X number (5 here) went to 0.

Fixed, and also reverted the "Fresh" category formula to old form - see commit desc.

**Review by tritonas00 — APPROVED** [review]

**Comment by tritonas00** [comment]
Works great now :+1:

**Pull request merged**
