### PR TITLE
Added ImGuiKey_KeyPad numbers

### PR DESCRIPTION
**Pull request by tritonas00**
Trying to fix https://github.com/RigsOfRods/rigs-of-rods/issues/2699 on Windows

### CODE REVIEW

**Comment by only-a-ptr** [comment]
Thanks so much, this annoyed me for ages.
Code looks perfect but I can't test ATM.

**Comment by tritonas00** [comment]
Doens't work yet, maybe they need to be added here also https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/gui/imgui/imgui.cpp#L8261

**Comment by tritonas00** [comment]
@paroj any idea why numpad numbers dont work in imgui on Windows?

**Comment by paroj** [comment]
actually, they *do work* for me in the SampleBrowser/ ImGui sample

**Comment by tritonas00** [comment]
kk

**Pull request merged**
