### PR TITLE
✨ Introduced MurmurHash3 hashing

### PR DESCRIPTION
**Pull request by ulteq**
Much faster than SHA1. Perfect fit for content hashing (detection of duplicates, ...).

### CODE REVIEW

**Comment by paroj** [comment]
also available via Ogre::FastHash.

**Comment by ulteq** [comment]
:man_facepalming:

**Comment by ulteq** [comment]
Wait a second, FastHash is not using MMH3 or something of similar quality, is it?

Not that it would matter, but I kinda like MMH3.

**Comment by paroj** [comment]
https://github.com/OGRECave/ogre/blob/master/OgreMain/include/OgreCommon.h#L47-L50

**Comment by ulteq** [comment]
Convinced :smile:

**Pull request closed without merging**
