### PR TITLE
Full support for Unicode file paths

### PR DESCRIPTION
**Pull request by only-a-ptr**
See #2353

## Update 2020-01-27

I removed the TODO items, most of them were long obsolete, also I fixed several other things not even listed.

The coverage is still not 100% (for example Flexbody cache may still cause issues), but the rest is important enough to merge now.

## How to test

1. Set up Conan, see https://github.com/RigsOfRods/rigs-of-rods/wiki/Compile-(Linux)#installing-the-dependencies
2. Clone https://github.com/AnotherFoxGuy/conan-OGRE and modify it by adding `cmake.definitions['CMAKE_CXX_FLAGS'] = '-D_OGRE_FILESYSTEM_ARCHIVE_UNICODE'`
3. Create the modified package `conan create . demo/testing`
4. Edit RoR's conanfile.txt: change OGRE reference to `OGRE/1.11.6@demo/testing` 
5. Use CMake to configure RoR, it will invoke Conan to fetch dependencies

### CODE REVIEW

**Comment by AnotherFoxGuy** [comment]
@only-a-ptr I've updated the *How to test* steps, since it can be a lot easier to create a custom build with conan

**Comment by only-a-ptr** [comment]
Everything works for me now on Win10 x64 under username `Žluťo` 😄 

@AnotherFoxGuy Thanks for the Conan tip! Please test this PR and eventually include `_OGRE_FILESYSTEM_ARCHIVE_UNICODE` in our Conan repo.

@CuriousMike56 @tritonas00 Also test, please.

**Comment by tritonas00** [comment]
I get
```
[ 13%] Building CXX object source/main/CMakeFiles/RoR.dir/utils/PlatformUtils.cpp.o
/home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/utils/PlatformUtils.cpp: In function ‘void RoR::OpenOFStream(std::ofstream&, const char*, unsigned int)’:
/home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/utils/PlatformUtils.cpp:200:25: error: invalid conversion from ‘unsigned int’ to ‘std::ios_base::openmode’ {aka ‘std::_Ios_Openmode’} [-fpermissive]
     ofstream.open(path, mode); // We blindly expect non-MSWindows platforms to support UTF-8 paths.
                         ^~~~
In file included from /home/babis/Downloads/ror-dependencies/Dependencies_Linux/include/OGRE/OgreStdHeaders.h:30,
                 from /home/babis/Downloads/ror-dependencies/Dependencies_Linux/include/OGRE/OgrePrerequisites.h:306,
                 from /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/cotire/RoR_CXX_prefix.cxx:5,
                 from /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/cotire/RoR_CXX_prefix.hxx:4:
/usr/include/c++/8.3.0/fstream:851:48: note:   initializing argument 2 of ‘void std::basic_ofstream<_CharT, _Traits>::open(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]’
       open(const char* __s, ios_base::openmode __mode = ios_base::out)
                             ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [source/main/CMakeFiles/RoR.dir/build.make:2732: source/main/CMakeFiles/RoR.dir/utils/PlatformUtils.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:400: source/main/CMakeFiles/RoR.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by only-a-ptr** [comment]
@tritonas00 Try now

**Comment by CuriousMike56** [comment]
Will test once I can build successfully: https://forum.rigsofrods.org/threads/rigs-of-rods-wont-start-on-windows-10-complied-from-source.1795/#post-7835

**Comment by CuriousMike56** [comment]
Do I have to create a modified package now that the repo includes `_OGRE_FILESYSTEM_ARCHIVE_UNICODE`? https://github.com/AnotherFoxGuy/conan-OGRE/commit/55d95f29e27822e1d23a068c47cb0020a182b77b

**Comment by AnotherFoxGuy** [comment]
Updated the Conan package: https://github.com/AnotherFoxGuy/conan-OGRE/blob/stable/1.11/conanfile.py#L70

**Comment by only-a-ptr** [comment]
https://github.com/RigsOfRods/rigs-of-rods/pull/2373#pullrequestreview-255475514 - paroj fixed the issue within OGRE, but only for upstream (1.12.1+).
His note from Gitter chat:
> @only-a-ptr I rather did a small refactoring regarding your issue here: OGRECave/ogre#1240
There will be no further 1.11 releases, therefore a 1.11 branch does not make sense for me. If you need any patches on top of the 1.11.6 release, you will have to maintain them on your fork.

I created the branch and cherrypicked paroj's fixes:https://github.com/only-a-ptr/ogre/commits/v1.11.6-with-patches @AnotherFoxGuy Please update our conan to build from here - just until v0.4.8, then I'll finally port us to OGRE 1x upstream + SDL

**Comment by vido89** [comment]
Great work guys

**Comment by tritonas00** [comment]
> + SDL

i can feel the pain already

:laughing: :sparkles::sparkles:

**Comment by paroj** [comment]
> I created the branch and cherrypicked paroj's fixes

cherry-pick from master again. There was a debug assertion triggered by the initial revision.

**Comment by only-a-ptr** [comment]
> @paroj cherry-pick from master again. There was a debug assertion triggered by the initial revision.

Done.

**Comment by only-a-ptr** [comment]
Now that OGRE's patched we don't need the ugly RoR.log hack I made. I'll clean up this PR a bit.

**Comment by only-a-ptr** [comment]
Hi, actually, paroj fixed Unicode in OGRE for good, so the workarounds in this branch shoudn't be needed at all. I'll do one more last test and then close it.

**Comment by only-a-ptr** [comment]
Sorry for another long lag. Everything is working now.

Paroj's [OGRE patch](https://github.com/OGRECave/ogre/commit/2fa49d0ed5c3b379c40a47f8ff1e565aba94ebb8) made all my hacks obsolete. The only thing left to fix was our 'mods.cache' file.

**Comment by tritonas00** [comment]
warnings
```
/home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/resources/CacheSystem.cpp: In member function ‘bool CacheSystem::ReadCacheFileJson(rapidjson::Document&) const’:
/home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/resources/CacheSystem.cpp:219:1: warning: control reaches end of non-void function [-Wreturn-type]
  219 | }
      | ^
```
and
kk

**Comment by only-a-ptr** [comment]
@AnotherFoxGuy 🙏 RoR.log? Or anything helpful?

@tritonas00 Looks like I'm calling OGRE wrong, let me see...

**Comment by AnotherFoxGuy** [comment]
> RoR.log? Or anything helpful?

It crashes before it can write a logfile, this is the only error: 
image

**Comment by paroj** [comment]
@only-a-ptr see https://github.com/OGRECave/ogre/pull/1272

**Comment by only-a-ptr** [comment]
BUMP!

I rebased this on 2020-01 release and fixed Unicode for savegames as well and tested. We won't be 100% safe until we migrate to OGRE 1.12 which fixes ZIP paths, but this is an important step.

**Comment by only-a-ptr** [comment]
BUMP!

Ready for final test and merge. We won't be 100% safe until we migrate to OGRE 1.12x, but the patches here are signifficant enough to be merged now.

**Pull request merged**
