### PR TITLE
✨ Switched from semver to rolling releases

### LINKED ISSUE #2415: Switch from semver to rolling releases
Currently, we use the semver release format (0.38, 0.4)
I think it would be better to switch to date based, so we can release a new version when we think that it is stable enough
The reason I think it would be better is that the last "official" stable release was back in 2016 and that we now use the release candidates a stable releases 

Example of the new release format:

Old | New
---|---
0.37.126 | 2010-12
0.38.64 | 2011-10
0.4.5.0 | 2015-08
0.4.7.0 | 2016-11
0.4.8 RC5 | 2019-07

Thoughts?

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
Closes #2415

**Changes**
* CMake will now automatically generate a version number based on the date of the build
* Moved the user dir on windows to `My Games/Rigs of Rods`

### CODE REVIEW

**Comment by only-a-ptr** [comment]
Pardon the delay, I'll test tonight.

However, question remains: Merge this right now (and abandon the 0.4.8 release) or first release 0.4.8 because it's been announced for so long? I sort of prefer "right now" because the denouncement of 0.4.8 would provide publicity to the new versioning scheme.

**Comment by CuriousMike56** [comment]
Is it possible to add a message telling users about the user folder change on startup if it detects `Documents\Rigs of Rods 0.4`? Some don't use the installer (e.g. installing through Itch.io) and would be confused as to why their mods no longer appear.

**Comment by only-a-ptr** [comment]
> @CuriousMike56 add a message telling users about the user folder change on startup

Sure, I'm thinking a custom IMGUI panel in main menu. I'll create a demo tonight.

**Comment by tritonas00** [comment]
maybe you should get rid of the -dev suffix also?

**Comment by AnotherFoxGuy** [comment]
> Maybe you should get rid of the `-dev` suffix also? 

The dev suffix is there to indicate it is a development build
> Where is that come from?

https://github.com/RigsOfRods/rigs-of-rods/blob/master/cmake/GenerateVersionInfo.cmake#L91

**Comment by AnotherFoxGuy** [comment]
> @only-a-ptr I found a windows bug

This should be fixed in https://github.com/RigsOfRods/rigs-of-rods/pull/2422/commits/40806ace3d99612a2a98e583c1c1cc4e67eef3a3

> add a message telling users about the user folder change on startup

Added in https://github.com/RigsOfRods/rigs-of-rods/pull/2422/commits/ff2285b1edaa0410cbc0b1f7979799524d715758

**Comment by AnotherFoxGuy** [comment]
Ive made the message a litebit nicer and removed `std::stream`

**Pull request merged**
