### PR TITLE
Fixed Apple Clang errors

### PR DESCRIPTION
**Pull request by wegank**

### CODE REVIEW

**Comment by only-a-ptr** [comment]
@wegank Thanks for the fixes! Builds and runs fine on my machine (Win10, Visual Studio 2022), I'll wait for GCC results.

This project hasn't had an Apple/OSX maintainer for ~10 years, so I'd expect more things to be broken. I'd like to know if you got it to build completely or even run - the last person trying gave up due to our dependency on OIS.

**Comment by CuriousMike56** [comment]
Recently I decided to repurpose my 2014 Acer laptop (i5-4210U, HD4400) by installing macOS Big Sur, One of the things I've really wanted to do with it is to try to build RoR, as the last attempt was in 2016. Using Xcode 13.2.1, I was able to configure all the dependencies (using OGRE 13 as I wasn't able to get 1.11.6 built), but I got stuck after receiving compile errors. This PR does fix those errors, unfortunately RoR still fails to link due to OIS as Petr mentioned above. 
Would be amazing if someone managed to get RoR running, even if only on a Intel-based machine.
```
Undefined symbols for architecture x86_64:
  "_CGAssociateMouseAndMouseCursorPosition", referenced from:
      OIS::CocoaMouse::_initialize() in libOIS.a(CocoaMouse.o)
      -[CocoaMouseView mouseEntered:] in libOIS.a(CocoaMouse.o)
      -[CocoaMouseView mouseExited:] in libOIS.a(CocoaMouse.o)
  "_CGDisplayHideCursor", referenced from:
      -[CocoaMouseView initWithFrame:] in libOIS.a(CocoaMouse.o)
      -[CocoaMouseView mouseEntered:] in libOIS.a(CocoaMouse.o)
  "_CGDisplayMoveCursorToPoint", referenced from:
      -[CocoaMouseView initWithFrame:] in libOIS.a(CocoaMouse.o)
  "_CGDisplayShowCursor", referenced from:
      OIS::CocoaMouse::~CocoaMouse() in libOIS.a(CocoaMouse.o)
      -[CocoaMouseView mouseExited:] in libOIS.a(CocoaMouse.o)
  "_CGEventCreateKeyboardEvent", referenced from:
      OIS::CocoaKeyboard::getAsString(OIS::KeyCode) in libOIS.a(CocoaKeyboard.o)
  "_CGEventKeyboardGetUnicodeString", referenced from:
      OIS::CocoaKeyboard::getAsString(OIS::KeyCode) in libOIS.a(CocoaKeyboard.o)
  "_CGEventSourceCreate", referenced from:
      OIS::CocoaKeyboard::getAsString(OIS::KeyCode) in libOIS.a(CocoaKeyboard.o)
  "_CGMainDisplayID", referenced from:
      OIS::CocoaMouse::~CocoaMouse() in libOIS.a(CocoaMouse.o)
      -[CocoaMouseView initWithFrame:] in libOIS.a(CocoaMouse.o)
      -[CocoaMouseView mouseEntered:] in libOIS.a(CocoaMouse.o)
      -[CocoaMouseView mouseExited:] in libOIS.a(CocoaMouse.o)
  "_IOCreatePlugInInterfaceForService", referenced from:
      OIS::MacHIDManager::iterateAndOpenDevices(unsigned int) in libOIS.a(MacHIDManager.o)
  "_IODestroyPlugInInterface", referenced from:
      OIS::MacHIDManager::iterateAndOpenDevices(unsigned int) in libOIS.a(MacHIDManager.o)
  "_IOIteratorNext", referenced from:
      OIS::MacHIDManager::iterateAndOpenDevices(unsigned int) in libOIS.a(MacHIDManager.o)
  "_IOObjectRelease", referenced from:
      OIS::MacHIDManager::iterateAndOpenDevices(unsigned int) in libOIS.a(MacHIDManager.o)
  "_IORegistryEntryCreateCFProperties", referenced from:
      OIS::MacHIDManager::iterateAndOpenDevices(unsigned int) in libOIS.a(MacHIDManager.o)
  "_IOServiceGetMatchingServices", referenced from:
      OIS::MacHIDManager::lookUpDevices(int, int) in libOIS.a(MacHIDManager.o)
  "_IOServiceMatching", referenced from:
      OIS::MacHIDManager::lookUpDevices(int, int) in libOIS.a(MacHIDManager.o)
  "_OBJC_CLASS_$_NSApplication", referenced from:
      objc-class-ref in libOIS.a(CocoaInputManager.o)
  "_OBJC_CLASS_$_NSResponder", referenced from:
      _OBJC_CLASS_$_CocoaKeyboardView in libOIS.a(CocoaKeyboard.o)
  "_OBJC_CLASS_$_NSTrackingArea", referenced from:
      objc-class-ref in libOIS.a(CocoaMouse.o)
  "_OBJC_CLASS_$_NSView", referenced from:
      _OBJC_CLASS_$_CocoaMouseView in libOIS.a(CocoaMouse.o)
  "_OBJC_METACLASS_$_NSResponder", referenced from:
      _OBJC_METACLASS_$_CocoaKeyboardView in libOIS.a(CocoaKeyboard.o)
  "_OBJC_METACLASS_$_NSView", referenced from:
      _OBJC_METACLASS_$_CocoaMouseView in libOIS.a(CocoaMouse.o)
  "_kIOMasterPortDefault", referenced from:
      OIS::MacHIDManager::lookUpDevices(int, int) in libOIS.a(MacHIDManager.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by wegank** [comment]
@only-a-ptr I got it built completely, though It didn't work, with a segmentation fault on launch. I'm using OIS 1.5 from Nixpkgs.

@CuriousMike56 I packaged OGRE 1.11.6 in NixOS/nixpkgs#198487, hope this helps.

**Comment by only-a-ptr** [comment]
We've intended to swap OIS for SDL2 for a long time, but it was never pressing enough. Recently we had to downgrade OIS due to incompatibility in game controller representation. 

Paroj (OGRE1x lead) suggested we might use [https://ogrecave.github.io/ogre/api/latest/class_ogre_bites_1_1_application_context_base.html](OgreBites::ApplicationContext) which serves as base for OGRE SampleBrowser but it's designed as general purpose. It runs on multiple platforms including Apple, uses SDL and allows renderer configuration with "apply and reload" button. I'm going to take a shot at this, building on top of the OGRE13 branch.

**Comment by CuriousMike56** [comment]
I was able to get RoR built by using OIS 1.5.1, with lots of warnings
image
Attempting to launch RoR fails with
```
dyld: Library not loaded: @executable_path/../lib/MyGUIEngine.framework/Versions/3.4.2/MyGUIEngine
  Referenced from: /Users/mike/Downloads/rigs-of-rods-ogre13v2/build/bin/Release/./RoR
  Reason: image not found
zsh: abort      ./RoR
```
Doesn't seem to have created an `RoR.log` as that file isn't anywhere on the system.
I'll see if I can get MyGUI 3.4.0 built to see if that changes anything.

**Comment by wegank** [comment]
@CuriousMike56 This can be solved by removing [this](https://github.com/MyGUI/mygui/blob/master/CMake/Utils/MyGUIConfigTargets.cmake#L421-L429) in MyGUI.

**Comment by CuriousMike56** [comment]
@wegank Thanks, I updated Ogre to 13.5.3 (from 13.4.4, I started working on this in back in September) and rebuilt MyGUI 3.4.1 with those lines removed. Unfortunately RoR now just segfaults instantly:
`zsh: segmentation fault  ./RoR`
At least the code does compile now. That's definitely an improvement :+1:

**Comment by only-a-ptr** [comment]
The warnings in the screenshot are 'best practice' warnings, I see nothing hazardous there, but some of them are surprising to me.
Does XCode have a debug build? Can you get a stack trace where it segfaults?
For me on Win10 + VisualStudio 2022, OIS 1.4x always segfaults and I have to use 1.5.1

**Review by tritonas00 — APPROVED** [review]

**Pull request merged**
