### PR TITLE
Removed SkyX

### PR DESCRIPTION
**Pull request by tritonas00**
Because of https://github.com/RigsOfRods/rigs-of-rods/pull/1483#issuecomment-424407159 and it's not updated to ogre 1.11

### CODE REVIEW

**Comment by ulteq** [comment]
@Speciesx what do you think?

**Comment by Speciesx** [comment]
I'm fine with that.

**Comment by tritonas00** [comment]
SkyX segfaults with ogre 1.11:

```
[SkyX] SkyXDefault.skx loaded.

Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
0x00007ffff77a21d5 in Ogre::Bitwise::intWrite (value=65280, n=3, dest=0x55555868b000)
    at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/include/OgreBitwise.h:264
264	                    ((uint8*)dest)[2] = (uint8)((value >> 16) & 0xFF);
```
```
#0  0x00007ffff77a21d5 in Ogre::Bitwise::intWrite (value=65280, n=3, dest=0x55555868b000)
    at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/include/OgreBitwise.h:264
#1  Ogre::PixelUtil::packColour(float, float, float, float, Ogre::PixelFormat, void*) ()
    at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgrePixelFormat.cpp:485
#2  0x00005555556f9051 in SkyX::VClouds::DataManager::_updateVolTextureData(SkyX::VClouds::DataManager::Cell***, SkyX::VClouds::DataManager::VolTextureId const&, int const&, int const&, int const&) ()
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gfx/skyx/VClouds/DataManager.cpp:611
#3  0x00005555556fa11c in SkyX::VClouds::DataManager::create(int const&, int const&, int const&) ()
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gfx/skyx/VClouds/DataManager.cpp:173
#4  0x0000555555704042 in SkyX::VClouds::VClouds::create() ()
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gfx/skyx/VClouds/VClouds.cpp:82
#5  0x00005555557046a5 in SkyX::VClouds::VClouds::create (this=<optimized out>, Height=..., Radius=@0x7fffffffcc3c: 95000)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gfx/skyx/VClouds/VClouds.cpp:124
#6  0x00005555556f70e0 in SkyX::VCloudsManager::create (this=this@entry=0x5555575b62f0, radius=@0x7fffffffcd00: 95000)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gfx/skyx/VCloudsManager.cpp:85
#7  0x00005555556f47fd in SkyX::CfgFileManager::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const ()
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gfx/skyx/SkyX.h:225
#8  0x000055555567fd70 in SkyXManager::SkyXManager(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gfx/SkyXManager.cpp:43
#9  0x000055555590217a in TerrainManager::initSkySubSystem() ()
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/utils/ZeroedMemoryAllocator.h:48
#10 0x0000555555903106 in TerrainManager::LoadAndPrepareTerrain(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/terrain/TerrainManager.cpp:165
#11 0x0000555555648453 in SimController::LoadTerrain() () at /usr/include/c++/8.2.1/bits/basic_string.h:927
#12 0x0000555555649860 in SimController::SetupGameplayLoop() ()
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gameplay/RoRFrameListener.cpp:2069
#13 0x0000555555605f09 in main () at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/main.cpp:350
#14 0x00007ffff6ce5223 in __libc_start_main () from /usr/lib/libc.so.6
#15 0x000055555561ec7e in _start () at /usr/include/c++/8.2.1/bits/char_traits.h:285
```
Maybe it can be fixed so we can keep it

**Comment by tritonas00** [comment]
Fixed: https://github.com/RigsOfRods/rigs-of-rods/pull/1537/commits/a76f5695b3fd3372fa7f30757c1e3dde603985a9

**Pull request closed without merging**
