### PR TITLE
New GUI system: DearIMGUI (restart)

### PR DESCRIPTION
**Pull request by only-a-ptr**
This is a lightweight edition of https://github.com/RigsOfRods/rigs-of-rods/pull/1333, only carrying the signifficant enhancements and omitting the "nice to have" stuff. I decided to split the branch because it had become convoluted, containing both important changes that I need in upstream ASAP and various other enhancements that can actually wait.

### Features:
* **GVars - final concept**: GVars are configuration variables which are read from RoR.cfg and in the future will be editable by in-game console. This system is inspired by Quake engine's "cvars". The documentation is in the repo's wiki: https://github.com/RigsOfRods/rigs-of-rods/wiki/GVars:-global-(console)-variables and will be added to our docs when ready.
* **DearIMGUI**: New GUI library, absolute must-have for further development, see #1333 for reasoning.
* **New MP serverlist**: The old one was lacking.
* **New settings window**: The old one was firmly tied to the "pre-GVars" way of handling ror.cfg, so I just deleted it altogether and created a new window. 
* **A lot of internal improvements**: When working on the above items, I ran into a lot of other things that were feasible to update - for easier maintenance and further development.

obrazek

Please test and see if anything got broken. If not, I'll merge this into upstream and I'll add the other changes in a following PRs.

### CODE REVIEW

**Comment by Michael10055** [comment]
:+1:
I think RoR should return to the main menu if you press Escape while the settings window is open rather than exiting.

**Comment by only-a-ptr** [comment]
@Michael10055 Very good point, I recall someone already asked this for the MP selector, and I forgot... I'll create a patch.

**Comment by tritonas00** [comment]
next week i will start testing again

@only-a-ptr do you plan to complete the new gui and remove mygui for this release?

**Comment by only-a-ptr** [comment]
> @tritonas00 do you plan to complete the new gui and remove mygui for this release?

Nope, too much work left to do. Aside from the GUI, MyGUI also powers the "*.layout" dashboard HUD system. And it generally works, so there's no rush. I'll save the features for 0.4.9 😄

**Pull request merged**
