### PR TITLE
Update OutProtocol.h

### PR DESCRIPTION
**Pull request by zappadoc**
Rigs Of Rods is now supported by our game devices manager SLIMax Manager, here is an addition to extend the outgauge API with backward compatibility, some important data are missing in the current API like the max RPM of current engine, the distance traveled, the ignition/starter status, etc. so here is my 2 cents to extend it smoothly just by altered the OutProtocol header and cpp.
To activate the new OutGauge V2 structure you just have to change the OutGauge Mode to 3 (see OutProtocol.cpp).
This contribution includes a few additional data just to see if you agree with the change after that I or someone else will be able to add other telemetry data.
Cheers,
zappadoc

### CODE REVIEW

**Comment by Hiradur** [comment]
line 113 
```unsigned cha MaxGears; = unsigned char?```

Please make sure it works before submitting a pull request.

**Comment by zappadoc** [comment]
sorry again, obviously it was an unsignised char... this was more a "spontaneous" suggested change quickly done but ok next time I will review my code before submit it...
Regards

**Comment by Hiradur** [comment]
I like the idea of adding more telemetry to it but if we merged this without checking it the project wouldn't compile anymore.
Since the changes to OutProtocol.h and OutProtocol.cpp refer to the same feature you should work with them on one branch and only start one pull request.

**Comment by zappadoc** [comment]
ok I understand. I just reviewed and pushed the right code for OutProtocol.cpp.

**Comment by Aperion** [comment]
@zappadoc I'm going to close both of these pull requests for a couple of reasons.

1. There are compilation errors present in the merges
2. Request #37 cannot compile without this pull request and they need to be merged.

**Pull request closed without merging**
