### PR TITLE
Wing visuals now updated asynchronously

### LINKED ISSUE #2306: Plane wings lag behind when backspacing
While moving with backspace, plane wings will lag behind:
planewingbug
This is especially noticeable if you hold CTRL or SHIFT.

### PR DESCRIPTION
**Pull request by only-a-ptr**
Fixes #2306

Quick and dirty fix, no time left to test.

### CODE REVIEW

**Comment by tritonas00** [comment]
works fine!

**Comment by only-a-ptr** [comment]
> works fine!

Meaning the Backspace-glitch is gone, or that aircraft can still fly, too? Try everything please 😄

**Comment by tritonas00** [comment]
yes, tried 3-4 planes

**Comment by tritonas00** [comment]
ok if https://github.com/RigsOfRods/rigs-of-rods/compare/abfff45844463421329e92b28cdf9d36698d82ee..463e34911a3b8722051e19ed307adeeba3dd026f doesn't cause any harm can we have it?

**Comment by only-a-ptr** [comment]
> @ulteq ...I don't know what impact [this change](https://github.com/RigsOfRods/rigs-of-rods/compare/abfff45844463421329e92b28cdf9d36698d82ee..463e34911a3b8722051e19ed307adeeba3dd026f) has

Oh, that's just me fixing up a copypaste error. When splitting `updateVertices`, I accidentally copied the code to `updateVerticesGfx`, too. It should execute from `updateVerticesPhysics` like before.

BTW it took me a good moment to figure out where that diff came from... I had no idea GitHub can diff against previous versions of commits.

@tritonas00 Heh, I was already looking at it when you posted 😄

**Pull request merged**
