### PR TITLE
Materialflare/Skinzip/Mirror/VideoCamera fixes (v0.4.8-alpha1)

### PR DESCRIPTION
**Pull request by only-a-ptr**
# Plan

See https://github.com/RigsOfRods/rigs-of-rods/milestone/14

# Status

Everything is working and ready for merge!

Fixes: #827 #656 #83 #266 #310 #402 #506 #1072 #1198

# Known bugs

None... all fixed!

**NOTE TO TESTERS: I'm deleting outdated erorr reports to keep this PR readable**

# Funny excerpts (already fixed):

### CODE REVIEW

**Comment by tritonas00** [comment]
` [ 23%] Building CXX object source/main/CMakeFiles/RoR.dir/gameplay/RoRFrameListener.cpp.o
In file included from /home/babis/Downloads/rigsofrods-next-build/rigsofrods/src/rigs-of-rods/source/main/gameplay/RoRFrameListener.h:25:0,
                 from /home/babis/Downloads/rigsofrods-next-build/rigsofrods/src/rigs-of-rods/source/main/gameplay/RoRFrameListener.cpp:21:
/home/babis/Downloads/rigsofrods-next-build/rigsofrods/src/rigs-of-rods/source/main/gfx/Mirrors.h:46:26: error: field ‘m_texture’ has incomplete type ‘Ogre::TexturePtr’
     Ogre::TexturePtr     m_texture;`

:stuck_out_tongue:

**Comment by only-a-ptr** [comment]
@tritonas00 strangely enough it passed in Travis.
Try now.

**Comment by Speciesx** [comment]
Skidmarks cause ror crash.

**Comment by tritonas00** [comment]
@only-a-ptr i use ogre 1.8

i will retry now

**Comment by tritonas00** [comment]
Now i get:

`[ 33%] Building CXX object source/main/CMakeFiles/RoR.dir/gfx/SkyManager.cpp.o
In file included from /home/babis/Downloads/rigsofrods-next-build/rigsofrods/src/rigs-of-rods/source/main/gfx/Skidmark.cpp:21:0:
/home/babis/Downloads/rigsofrods-next-build/rigsofrods/src/rigs-of-rods/source/main/gfx/Skidmark.h:73:27: error: field ‘material’ has incomplete type ‘Ogre::MaterialPtr’
         Ogre::MaterialPtr material;`

**Comment by only-a-ptr** [comment]
@tritonas00 your compiler is pretty unforgiving
Try now

**Comment by tritonas00** [comment]
@only-a-ptr now compiles fine, thanks!

It would be nice to get rid those Wattributes warnings like:

`/home/babis/Downloads/rigsofrods-next-build/rigsofrods/src/rigs-of-rods/source/main/network/Network.h:64:15: note: attribute for ‘struct RoR::Networking::CharacterMsgAttach’ must follow the ‘struct’ keyword
/home/babis/Downloads/rigsofrods-next-build/rigsofrods/src/rigs-of-rods/source/main/network/Network.h:72:15: warning: attribute ignored in declaration of ‘struct RoR::Networking::recv_packet_t’ [-Wattributes]
 PACKED struct recv_packet_t`

i get many of those :stuck_out_tongue:

**Comment by Speciesx** [comment]
@only-a-ptr
> @Speciesx Argh! Give me a few days to get to test it.... Anyway, what map+vehicle did you test with? Can you post RoR.log or more debug info?

map N-Labs testing Facility 0.5 vehicle mv4, mz2, Drifter

**Comment by tritonas00** [comment]
Back to menu also crashes the game for me

**Comment by only-a-ptr** [comment]
Finally built and ran it yesterday. So many crashes! 😊

**Comment by Speciesx** [comment]
Skidmarks don't work.


I get this error when i try to load the same terrain again.

**Comment by only-a-ptr** [comment]
Exposed 😊

**Comment by tritonas00** [comment]
`/home/babis/Downloads/rigsofrods-next-build/rigsofrods/src/rigs-of-rods/source/main/gui/OverlayWrapper.cpp:289:93: error: ‘class Ogre::Resource’ has no member named ‘getTechnique’
     speedotexture = (MaterialManager::getSingleton().getByName("tracks/speedoneedle_mat"))->getTechnique(0)->getPass(0)->getTextureUnitState(0); // Needed for dashboard-prop`

please fix :blush:

**Comment by only-a-ptr** [comment]
Ok, I fixed all the crashes after you go ->sim->menu->sim
But it doesn't exactly work like I imagined:
screenshot_2017-02-04_21-55-44_1

**Comment by only-a-ptr** [comment]
@tritonas00 Regarding the "-Wattributes" warnings: good thing they're there! I just discovered that I embaarrasingly misunderstood how stuff works: http://stackoverflow.com/a/33438292 and most importantly that `#pragma (pack)` isn't windows-specific: https://gcc.gnu.org/onlinedocs/gcc-4.8.4/gcc/Structure-Packing-Pragmas.html :blush: 

Good thing I didn't release 0.4.7.1 yet :blush:

**Comment by tritonas00** [comment]
> EDIT @tritonas00 Fix for the Wattributes warnings: please test: #1273

Yes, this fixes all of them! :+1:

**Comment by Michael10055** [comment]
The back-to-menu glitch also affects different vehicles as well, for example:
If you spawn any vehicle (ex. Gavril Omega Ten), head back to menu, load up the same map, then spawn another vehicle (ex. Gavril MV4S) It'll contain parts of the first vehicle, which can lead to some pretty interesting results 😄 
ror_2017-02-04_18-29-34

**Comment by only-a-ptr** [comment]
I partially fixed the back-to-menu glitch: vehicles with old-style cabmesh (Agora, DAF-semi) spawn well the second time. But there's a funny glitch with wheel meshes - they just hang in there and rotate in opposite direction than the truck.
screenshot_2017-02-06_23-13-41_1

**Comment by only-a-ptr** [comment]
@tritonas00  The "[-Wattributes] PACKED struct recv_packet_t" should be gone now. Can you re-test please?

**Comment by tritonas00** [comment]
this https://github.com/RigsOfRods/rigs-of-rods/pull/1271/commits/162c6cbf3eaf3a790508a93416a2b885d1b10422 fixes the gavril issue :+1:

**Comment by tritonas00** [comment]
the wheel orientation thing is still present for this https://www.dropbox.com/s/tijcew8zr1t86w5/Betzi-tourliner.zip?dl=0

2017-02-17-194721_1366x768_scrot

**Comment by tritonas00** [comment]
can you please resolve the conflict?

`CONFLICT (modify/delete): source/main/gui/TruckHUD.cpp deleted in bc5636171de124ce09d1d74e5db526d92456f42d and modified in HEAD. Version HEAD of source/main/gui/TruckHUD.cpp left in tree.`

**Comment by only-a-ptr** [comment]
When I fix the goofy wheels, I'll also fix the conflict.

**Comment by tritonas00** [comment]
`source/main/physics/flex/FlexFactory.h`

changing
`FlexMeshWheel* FlexFactory::CreateFlexMeshWheel(`
to
`FlexMeshWheel* CreateFlexMeshWheel(`

fixes the gcc _extra qualification error_, but i dont know if it breaks anything...

**Comment by only-a-ptr** [comment]
@tritonas00 It's not in workable state at the moment.

Your fix to *extra qualification* warning is completely right, my mistake for writing it wrong.

**Comment by tritonas00** [comment]
`[ 76%] Building CXX object source/main/CMakeFiles/RoR.dir/physics/air/TurboJet.cpp.o
/home/babis/Downloads/rigsofrods-next-build/rigsofrods/src/rigs-of-rods/source/main/physics/RigSpawner.cpp: In member function ‘Ogre::MaterialPtr RigSpawner::FindOrCreateCustomizedMaterial(std::__cxx11::string)’:
/home/babis/Downloads/rigsofrods-next-build/rigsofrods/src/rigs-of-rods/source/main/physics/RigSpawner.cpp:7101:99: error: ‘class Ogre::Resource’ has no member named ‘clone’
             lookup_entry.material = Ogre::MaterialManager::getSingleton().getByName("BaseWhite")->clone(new_mat_name, true, m_custom_resource_group);
                                                                                                   ^~~~~
source/main/CMakeFiles/RoR.dir/build.make:3206: recipe for target 'source/main/CMakeFiles/RoR.dir/physics/RigSpawner.cpp.o' failed
make[2]: *** [source/main/CMakeFiles/RoR.dir/physics/RigSpawner.cpp.o] Error 1`

:blush:

**Comment by only-a-ptr** [comment]
@tritonas00 Curiously it compiled in Travis under both gcc and clang. That line of code is temporary anyway, it paints mirrors/videocams all white for the time being. I'll update it soon.

**Comment by tritonas00** [comment]
I use ogre 1.8, maybe that's why

Thanks!

**Comment by only-a-ptr** [comment]
@tritonas00 Most definitely 😄

**Comment by tritonas00** [comment]
still no love for ogre 1.8 :stuck_out_tongue_closed_eyes:

**Comment by only-a-ptr** [comment]
@tritonas00 Try now, should be OK

**Comment by tritonas00** [comment]
nope

`[ 25%] Building CXX object source/main/CMakeFiles/RoR.dir/gameplay/TorqueCurve.cpp.o
In file included from /home/babis/Downloads/rigsofrods-next-build/rigsofrods/src/rigs-of-rods/source/main/gameplay/SkinManager.cpp:23:0:
/home/babis/Downloads/rigsofrods-next-build/rigsofrods/src/rigs-of-rods/source/main/gfx/OgreSubsystem.h: In static member function ‘static Ogre::MaterialPtr RoR::OgreSubsystem::GetMaterialByName(const string&)’:
/home/babis/Downloads/rigsofrods-next-build/rigsofrods/src/rigs-of-rods/source/main/gfx/OgreSubsystem.h:81:47: error: incomplete type ‘Ogre::MaterialManager’ used in nested name specifier
         return static_cast<Ogre::MaterialPtr>(Ogre::MaterialManager::getSingleton().getByName(name));
                                               ^~~~
source/main/CMakeFiles/RoR.dir/build.make:614: recipe for target 'source/main/CMakeFiles/RoR.dir/gameplay/SkinManager.cpp.o' failed`

**Comment by only-a-ptr** [comment]
Aaaand.. wrong again. Ford SuperDuty breaks like this on 2nd session

obrazek

**Comment by only-a-ptr** [comment]
@tritonas00 I'll fix that, too

**Comment by only-a-ptr** [comment]
@tritonas00 now try it

**Comment by tritonas00** [comment]
compiles fine!

thanks!

**Comment by tritonas00** [comment]
almost every map segfaults upon loading, single terrain and auriga works :stuck_out_tongue_winking_eye:

**Comment by only-a-ptr** [comment]
@tritonas00 Just tried Romania, Oahu, Mudtrial, NeoQueterato. All working. What exactly crashed for you?

**Comment by tritonas00** [comment]
try nhelens please

**Comment by only-a-ptr** [comment]
Thanks, I'll have a look tomorrow

**Comment by only-a-ptr** [comment]
@tritonas00 Please go backwards in the commit history and find the commit which causes the breakage. It might be something which shows up only on linux or OGRE 1.8

I'll test in the evening with my laptop, but I suppose everything will work. I also asked guys on Discord to come testing, but no big response there.

**Comment by tritonas00** [comment]
Good mews, i started fresh with clean .rigsofrods dir, and ... no segfaults :simple_smile:

so probably a bad setting or something...

when do you plan to fix the skyvan issue?

**Comment by only-a-ptr** [comment]
> when do you plan to fix the skyvan issue?

When you remind me it's still present 😄 I'll check it out in the evening.

**Comment by tritonas00** [comment]
ok all seems fine with ogre 1.9, no crashes so far

yes, the skyvan issue is still present :stuck_out_tongue:

**Comment by only-a-ptr** [comment]
obrazek

Skyvan issue reproduced, working on fix...

**Comment by tritonas00** [comment]
203d213 is ok with ogre 1.8 (i will update this post when i find the bad commit)

**Comment by only-a-ptr** [comment]
@tritonas00 Bad commit causing what? The segfaults on map load? I thought you said rebuilding fixed it

**Comment by tritonas00** [comment]
this commit causes many segfaults while loading maps/vehicles with ogre 1.8

works ok with ogre 1.9

**Comment by tritonas00** [comment]
Simple test with 1.8: Clean profile, open ror, open simple terrain load agora:

404a70d ok
d7e98c4 segfault

**Comment by only-a-ptr** [comment]
@tritonas00 I'm tempted to just drop support for OGRE 1.8 altogether 😁 It's way out of date and I'll have to build it from sources to test.

No, I have a better idea... I'll explore porting to OGRE 2+; if it works well, then byebye OGRE 1.x 😀

**Comment by tritonas00** [comment]
ogre 1.9 is a bit crashy in both desktop and laptop here (intel graphics)

**Comment by only-a-ptr** [comment]
@tritonas00 OK, understood.

**Comment by tritonas00** [comment]
Ok i think i will update to ogre 1.9. Beside some vehicles that cause segfault, i get much better fps.

:simple_smile:

**Comment by only-a-ptr** [comment]
Intel chips are notorious troublemakers. I'll fix the OGRE 1.8 support.

But I wonder... could you build OGRE 2.1 from sources? I'd like to know how it will behave for you.

**Comment by tritonas00** [comment]
> could you build OGRE 2.1 from sources?

Of course, i will give it a try ASAP

> I'll fix the OGRE 1.8 support.

:heart:

**Comment by only-a-ptr** [comment]
: Of course, i will give it a try ASAP, will the latest master compile and run against it?

No chance, OGRE underwent a big overhaul for version 2.0 and even bigger for 2.1
But I intend to port to it, just as soon as I reduce the existing issue log a bit 😄

**Comment by tritonas00** [comment]
maybe this info is helpful

valgrind shows this line after the crash https://github.com/RigsOfRods/rigs-of-rods/commit/d7e98c4817eb725051507b91d9c3d882965a09ec#diff-f6d31dc04dbfa695e24ec2feb2d53499R953

full log https://pastebin.com/GqCJRi51

**Comment by only-a-ptr** [comment]
@tritonas00 I wasn't able to test with OGRE 1.8 yet, I'll keep trying.

The valgrind output is a helpful hint, but I really need a debugger output of a Debug build. Could you build as Debug and step around the offending place?

**Comment by tritonas00** [comment]
With Debug build: https://pastebin.com/2EAHqzyt

**Comment by tritonas00** [comment]
gdb:

`Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
0x000000000075730f in Ogre::SharedPtr<Ogre::Material>::operator= (this=this@entry=0x7ffffffef6c0, r=...)
    at /opt/rigsofrods/include/OGRE/OgreSharedPtr.h:119`

full output: https://pastebin.com/gBwB9RdU

**Comment by only-a-ptr** [comment]
@tritonas00 : Try now with OGRE 1.8

**Comment by tritonas00** [comment]
Sorry for the delay

Works like a charm! Thank you only-a-ptr! :heart:

**Comment by only-a-ptr** [comment]
@tritonas00 : Wow, it actually worked? Yay! I need to be more careful with [`memset()`](http://www.cplusplus.com/reference/cstring/memset/) 😊 

This is such an awesome news, I've been sick and tired of having this gigantic PR stuck here with a single last glitch... I'm taking a deep breath and clicking "merge" 😄

**Comment by tritonas00** [comment]
Ok we have some more bugs.

Bug 1

Load Simple Test Terrain and spawn Desperado
Go to Backup to menu
Reload Load Simple Test Terrain and spawn Betzi-tourliner

2017-06-02-232639_1366x768_scrot

Bug 2

Spawn Betzi-tourliner and Backup to menu -> crash
Spawn Betzi-tourliner and remove it -> crash

https://www.dropbox.com/s/wai9uytcru95d4m/Desperado.zip?dl=1
https://www.dropbox.com/s/tijcew8zr1t86w5/Betzi-tourliner.zip?dl=1

**Comment by tritonas00** [comment]
Both Betzi-tourliner crashes lead to the same gdb output: https://pastebin.com/yWTzGC2A

**Comment by tritonas00** [comment]
A bit more helpful gdb output: https://pastebin.com/vUKeTe3P

**Comment by only-a-ptr** [comment]
@tritonas00  Thanks for testing! Unfortunately, I won't be able to work on this much in the coming 2 weeks.

**Comment by only-a-ptr** [comment]
Yessss! I zapped the "Betzi tourliner" bug which was actually something I've seen before and it was giving me a headache ever since I fixed resource handling for FlexBodies.

**Comment by tritonas00** [comment]
Crashes gone! :heart_eyes:

**Comment by only-a-ptr** [comment]
Aaand... I'm merging this. It's a looong sleeve of changes that I want to finally have in upstream.

The Skyvan issue remains, but I'm making an issue ticket and putting it off 😇 https://github.com/RigsOfRods/rigs-of-rods/issues/1008#issuecomment-306905522

**Comment by tritonas00** [comment]
skyvan issue and betzi bug 1 :smile:

**Comment by disloyalpick** [comment]
I'm not sure if this is where to put it, but is there a way to change the default smoke to a gas like color exhaust smoke? I've tried everything, by putting the .material and .particle files into my vehicles zip, but I just can't get it to change the color of the exhaust. Is the black color hardcoded or something?

**Comment by only-a-ptr** [comment]
@disloyalpick No it's not the right place 😄 , let me open a new ticket for you: https://github.com/RigsOfRods/rigs-of-rods/issues/1349

**Pull request merged**
