### PR TITLE
[Bugfix] Fixes incorrect 'reset in place' alignment on some trailers/loads

### LINKED ISSUE #503: 'reset in place' aligns trailer and loads to SE
After reset (Backspace key) trailer and loads should keep their previous alignment.

### PR DESCRIPTION
**Pull request by ulteq**
Fixes #503

### CODE REVIEW

**Comment by AnotherFoxGuy** [comment]
Compiling this with vs10 throws the error 
```Beam.cpp(1311): error C2039: 'round' : is not a member of 'std'   ```
```Beam.cpp(1311): error C3861: 'round': identifier not found  ```

**Comment by only-a-ptr** [comment]
@AnotherFoxGuy : add ```#include <math>```
http://en.cppreference.com/w/cpp/numeric/math/round

**Comment by AnotherFoxGuy** [comment]
That trows the error 
```error C1083: Cannot open include file: 'math': No such file or directory```

**Comment by Hiradur** [comment]
try ```#include <cmath>```
but since round() is a c++11 feature it may be missing in VS 2010

**Comment by AnotherFoxGuy** [comment]
Nope, still throws the error 
```'round' : is not a member of 'std'   ```

**Comment by Hiradur** [comment]
It's probably missing in VS 2010 then, similar to #494 
Instead of rewriting the C++11 standard library for VS2010 you Windows guys should update your VS. :P

**Comment by mikadou** [comment]
> Instead of rewriting the C++11 standard library for VS2010 you Windows guys should update your VS. :P

:+1: +1

**Comment by only-a-ptr** [comment]
> Instead of rewriting the C++11 standard library for VS2010 you Windows guys should update your VS. :P
:+1: :smile:

**Pull request merged**
