### PR TITLE
[Feature] Overworked the reset in place feature

### PR DESCRIPTION
**Pull request by ulteq**
You can now translate and rotate the truck while pressing (and holding) the repair truck key.

This implements @Speciesx awesome idea on how to improve the reset in place feature.

Controls:
* `TRUCK_ACCELERATE` -> translate upward
* `TRUCK_BRAKE` -> translate downward
* `TRUCK_STEER_LEFT` -> rotate left
* `TRUCK_STEER_RIGHT` -> rotate right
* `CHARACTER_FORWARD` -> translate forward
* `CHARACTER_BACKWARDS` -> translate backward
* `CHARACTER_SIDESTEP_RIGHT` -> translate right
* `CHARACTER_SIDESTEP_LEFT` -> translate left

### CODE REVIEW

**Comment by tritonas00** [comment]
Just tested, great!

**Comment by Speciesx** [comment]
@ulteq 
Works great.
On some vehicles like mv4, the camera shake.

**Comment by ulteq** [comment]
> the camera shake

That's a hard one to solve.

**Comment by only-a-ptr** [comment]
The diff is hard to read, but looks good.

**Comment by ulteq** [comment]
> The diff is hard to read, but looks good.

I will restructure it before I merge.

**Comment by only-a-ptr** [comment]
Reads like a child's book now :relaxed: 

One minor request: ```int Beam::reset_requested``` => ```enum Beam::ResetRequestType{}``` + ```ResetRequestType Beam::m_reset_request``` please.

**Comment by disloyalpick** [comment]
Truck Steer Left doesn't rotate the vehicle, but does the same as holding W key.

Same for Truck Steer Right. They just translate the vehicle left and right, instead of rotating.

**Pull request merged**
