### PR TITLE
Tabs-be-gone

### PR DESCRIPTION
**Pull request by only-a-ptr**
Allright, this was a LOT of tedious manual work, but it had to be done at some point.

Changes:
* Converted all code to use spaces for all indentation/alignment.
* Removed header guard macros in favor of `#pragma once`
* Unified license blocks
* Unified file description/authorship comments
* Unified coding style, especially `if {} else {}` blocks
* Removed old commented-out code

I've split the conversion into several commits, because I hate monstercommits.

Used tools: ReSharper C++, VisualStudio "untabify selected lines", manual adjustment

### CODE REVIEW

**Comment by only-a-ptr** [comment]
UPDATE: Rebased atop 0.4.7 (with CrashRpt)

**Comment by only-a-ptr** [comment]
UPDATE2: Fixed building without USE_CRASHRPT

**Comment by ulteq** [comment]
LGTM

**Comment by only-a-ptr** [comment]
Oh bother... AppVeyor won't link for some reason

**Comment by only-a-ptr** [comment]
I have no idea why AppVeyor fails building Utils.cpp. The logs indicate the macro USE_MOFILEREADER gets ignored in Language.h included from there 😟

**Pull request merged**
