### PR TITLE
[DO NOT MERGE!] Fixes Mitsubishi L200 DI-D parsing

### PR DESCRIPTION
**Pull request by ulteq**
Issue: https://github.com/RigsOfRods/rigs-of-rods/issues/1008
Reference: http://docs.rigsofrods.org/technical/fileformat-truck/#commands

### CODE REVIEW

**Comment by only-a-ptr** [comment]
Yeah, another f*cked-up truckfile
```
Mitsubishi L200 DI-D

commands
2, 5, 0.1,  1,   2,    25, 26, i, suspension up
3, 4, 0.1,  1,   2,    25, 26, i, suspension up
8, 11, 0.1,  1,   2,    25, 26, i, suspension up
9, 10, 0.1,  1,   2,    25, 26, i, suspension up
```

The old parser would just interpret "suspension" and "up" as zeros and be happy.

Well, let's just edit our [`E_SECTIONS_COMMANDS_COMMANDS2_INERTIA_AFFECT_ENGINE_PART`](https://github.com/RigsOfRods/rigs-of-rods/blob/6dfe879d38ca9afbc135583c306823fe431b3eae/source/rig_file_input_output/RigDef_Regexes.h#L917-L922) regex to parse start/stop delay as [`E_STRING_ALNUM_HYPHENS_USCORES_ONLY`](https://github.com/RigsOfRods/rigs-of-rods/blob/6dfe879d38ca9afbc135583c306823fe431b3eae/source/rig_file_input_output/RigDef_Regexes.h#L110) instead of numbers. `OgreStringConverter` will parse it as 0 and we're done, silently ignoring the truckfile screwup.

**Comment by ulteq** [comment]
The old parser did not parse the `INERTIA_AFFECT_ENGINE_PART` for regular commands, or did it?

**Comment by only-a-ptr** [comment]
There's no such thing as "regular commands", just `commands` and `commands2`. The inertia part applied to both (since a certain version), the affectEngine part might have been `commands2`-only, I don't remember.

**Comment by ulteq** [comment]
> Well, let's just edit our E_SECTIONS_COMMANDS_COMMANDS2_INERTIA_AFFECT_ENGINE_PART regex to parse start delay as E_STRING_ALNUM_HYPHENS_USCORES_ONLY instead of numbers.

All right, then.

**Pull request closed without merging**
