### PR TITLE
[WIP] Floating skidmarks fix

### PR DESCRIPTION
**Pull request by only-a-ptr**
I'm on my way to fix the infamous "floating skidmarks" glitch, see https://github.com/RigsOfRods/rigs-of-rods/issues/539

## Status: Still broken, refactored again, needs testing.

To fix the skidmarks, I need some extra info from the collision system - did the wheel touch only ground or also a static geometry? To get the info, I need to slightly modify the collision code, so I cleaned it up for myself first. Please test if collisions are working normally.

### CODE REVIEW

**Comment by tritonas00** [comment]
I can't notice any difference

**Comment by only-a-ptr** [comment]
Is it just me or are skidmarks rather cr*ppy in the current upstream? They look decent when you drive straight (altough there are gaps in them), but when you're drifting, the result is a fuzzy mess. The trails roughly follow the trajectory of the wheel, but they have nothing to do with it's direction and angle. I also observed that drifting easily generates skidmarks which protrude up to the air (and possibly also under the ground, didn't check).

Anyway, today's revision is another refactor, aimed to get more precise 'skidding data' from the physics code. I tested and it works, and it feels like more skidmarks are made now.

**Comment by Michael10055** [comment]
Skidmarks have always been glitchy when sliding/drifting, even on 0.36.3:
screenshot_71
screenshot_70
Also since you're working on skidmarks now, would it be possible to bring back the ability for skidmarks to appear on other surfaces (such as dirt/sand)? They do on 0.36.3:
screenshot_68

**Comment by only-a-ptr** [comment]
> @Michael10055 Skidmarks have always been glitchy when sliding/drifting, even on 0.36.3

Whew, thanks! It's always such a relief to know things didn't get broken on your watch.

> @Michael10055 ... skidmarks to appear on other surfaces (such as dirt/sand)? They do on 0.36.3:

This should actually still work, can you link me to the map you tested with? The builtin skidmarks are defined in [skidmarks.cfg](https://github.com/RigsOfRods/rigs-of-rods/blob/master/resources/skeleton/config/skidmarks.cfg) and they map to terrain using groundmodel name - so a map needs to use the predefined names to display skidmarks at all.

**Comment by tritonas00** [comment]
> I'm pretty sure this comes from upstream

I can't reproduce the crash in current upstream. I tried with S10

**Comment by Michael10055** [comment]
Okay, Maybe you were right.. Just crashed when backspacing the 2014 Superduty  (Single cab version) on a build with #1314 merged, which I doubt that PR would cause the same crash.

**Pull request closed without merging**
