### PR TITLE
Restored text coloring in SelectorUI

### PR DESCRIPTION
**Pull request by only-a-ptr**
color wrap

### CODE REVIEW

**Comment by tritonas00** [comment]
Nice except one issue, if you scroll, you can see the title moving up
kk

**Comment by tritonas00** [comment]
Here is a vehicle with dark color name https://forum.rigsofrods.org/resources/hoodrat-2020.671/

**Comment by only-a-ptr** [comment]
> @tritonas00  Nice except one issue, if you scroll, you can see the title moving up

Nice spot. It turns out to be an advanced exercise with imgui internals. So far I only managed to get it clipped when outside of the sroll area, not when partially visible.

**Comment by tritonas00** [comment]
Just skip right side coloring if it is too much hassle.

**Comment by only-a-ptr** [comment]
Text clipping fixed.
I solved the black text by adding 'darkness limit' - if below, the color gets inverted.

image

**Comment by tritonas00** [comment]
Nice! Two things noticed:

- Please increase `size.x` in https://github.com/only-a-ptr/rigs-of-rods/blob/wee-colors/source/main/gui/panels/GUI_MainSelector.cpp#L180 otherwise mouse pointer needs to hover text only, to make a selection
`if (ImGui::Selectable("##dummy", &is_selected, 0, ImVec2(size.x + 100.f, size.y))) // Use invisible label + size parameter.` did the trick

- Spawn a vehicle (like desperado) and press `w` a couple of times:
kk

**Comment by only-a-ptr** [comment]
@tritonas00 both corrected

**Comment by tritonas00** [comment]
Looks good!

**Review by tritonas00 — APPROVED** [review]

**Pull request merged**
