### PR TITLE
[Bugfix] Fixes #459

### LINKED ISSUE #459: Crash in MP when another player spawns a vehicle
Compiled latest git in Archlinux and downloaded 0.4 High Quality Pack.

Tried to login in Awesome_Gaming_Mit (f4afUID-flat_mitcity) server. (http://www.rigsofrods.com/repository/download/4932)

First attempt:

>Program received signal SIGSEGV, Segmentation fault.
0x00007ffff749ed99 in Ogre::SceneNode::setVisible(bool, bool) () from /usr/lib/libOgreMain.so.1.9.0

Removed everything from packs folder, left only the map and tried again, game logins nicely.

Restored packs folder, cleaned and regen cache, logged in, but most of the players are out. While playing, one other player came in and spawned a vehicle (gavrilzeta). Game crashes.

gdb output->http://pastebin.com/qmc1WpqH
gdb bt full->http://pastebin.com/wHKaGPLZ

### PR DESCRIPTION
**Pull request by Bob-Z**
This seems to fix the multi-player crash for me.
The "access element" paragraph of this page http://www.cplusplus.com/reference/vector/vector/operator%5B%5D/ inspired me.

### CODE REVIEW

**Comment by only-a-ptr** [comment]
Thanks a lot for the contribution! Yes, the code seems suspicious.
However, I added 2 notes to the code - please attend to them.

**Comment by Hiradur** [comment]
Thanks, however for the next commit please use a commit headline like ```[Fix] Crash in Multiplayer due to OOB access``` because nobody knows of the bat what issue number 459 is. You can link to the issue in the message field of the commit.

Also, if I understood this correctly (https://github.com/RigsOfRods/rigs-of-rods/issues/174#issuecomment-167164294 ) then it's always trying to access the element with index -1 which doesn't exist of course. The question is, why does it do that and can it be prevented?

**Comment by Bob-Z** [comment]
Sorry for the commit headline. I just copied another commit message in the log. You are totally right that this is not a relevant message.

Accesing a non existent index of a std::vector with the [] operator results in undefined behaviour. In linux 64 bits it seems that undefined behavior is SIGSEGV. (Note that I have seen sometimes that, even with index set to -1, the call to flares[-1] do not crash and everything works as expected. This is the definition of undefined behavior !)

I don't like the idea of using -1 as an index in this case because -1 is cast to unsigned int in calls to [] operator or at() method. This means that accessing index -1 is accessing elements 0xFFFFFFFF, which fails the bound checking of at() method. Anyway I have seen this use of -1 in other projects so maybe it is a good practice for some reasons, I don't know...

There may be the same bug elsewhere in the code where std::vector::operator[] is used inside a try/catch block. But since it seems to happen only on 64 bits platforms, they will be slower to emerge.

**Comment by Bob-Z** [comment]
In fact for each use of std::vector::operator[] (even outside a try/catch block) we should either make sure index is in-bounds or use at() method instead (which should be a bit slower).

**Comment by ulteq** [comment]
My suggestion:

```
void Beam::setCustomLightVisible(int number, bool visible)
{
	if (number < 0)
	{
		LOG("AngelScript: Light ID (" + TOSTRING(number) + ") underflow");
		return;
	}

	if (number >= 5)
	{
		LOG("AngelScript: Light ID (" + TOSTRING(number) + ") overflow, max: 4...");
		return;
	}

	int flareID = netCustomLightArray[number];

	if (flareID >= 0 && flareID < flares.size() && flares[flareID].snode)
	{
		flares[flareID].controltoggle_status = visible;
	}
}
```

**Comment by only-a-ptr** [comment]
@Bob-Z Oops, I didn't know the ```index``` parameter receives negative input, too. Anyway that means the function has been unsafe all along.
@ulteq: That way, it still doesn't check array overflow.

My suggestion:
```
void Beam::setCustomLightVisible(int number, bool visible)
{
    if (number < 0 || number > 4)
    {
        LOG("AngelScript: Invalid Light ID (" + TOSTRING(number) + "), allowed range is (0 - 4)");
        return;
    }

    if ()
    {
        LOG("AngelScript: Light ID (" + TOSTRING(number) 
            + ") overflow, array size is: " + TOSTRING(netCustomLightArray.size()) );
        return;
    }

    int flareID = netCustomLightArray[number];

    if (flareID >= 0 && flareID < flares.size() && flares[flareID].snode)
    {
        flares[flareID].controltoggle_status = visible;
    }
}
```

**Comment by ulteq** [comment]
`netCustomLightArray` is not a std::vector.
https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/datatypes/rig_t.h#L210

**Comment by only-a-ptr** [comment]
@ulteq What?? Then how did it throw std::out_of_range for BobZ?

**Comment by Bob-Z** [comment]
Thanks for your comments. I have updated my pull request accordingly.

Anyway I have 2 more questions:
 - Is the AngelScript reference in the LOG text relevant ?
 - Why custom light number is limited to 4 ?

**Comment by mikadou** [comment]
@only-a-ptr Just curious, how is this related to c++11?

**Comment by ulteq** [comment]
@Bob-Z, you must also change this line: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/physics/Beam.cpp#L6612

**Comment by ulteq** [comment]
Since `getCustomLightVisible` can also be called from AngleScript, why not do it like that:

```
bool Beam::getCustomLightVisible(int number)
{
    if (number < 0 || number > 4)
    {
        LOG("AngelScript: Invalid Light ID (" + TOSTRING(number) + "), allowed range is (0 - 4)");
        return false;
    }

    unsigned int flareID = netCustomLightArray[number];

    return flareID < flares.size() && flares[flareID].controltoggle_status;
}
```

**Comment by Hiradur** [comment]
@tritonas00 told me he hasn't had any crash since he downgraded to Ogre 1.8. I know @only-a-ptr was unable to reproduce this crash and he's also been using Ogre 1.8. 
I tested with the 0.4.5.1 release on Windows and it crashed for me (it's using Ogre 1.8, isn't it?)
Any more input from people using Ogre 1.8?

**Comment by only-a-ptr** [comment]
@Hiradur I have nothing to add. However, this pull request definitely fixes an unsafe function, even if it doesn't fix the MP crash completely.

@Bob-Z The custom light limit of 4 is defined by RoRNet: https://github.com/RigsOfRods/rigs-of-rods/blob/86b6bc5f95b9abd937b270747b2c7e0137b65fe8/source/main/network/protocol/rornet.h#L128-L131

@mikadou BobZ's code relies on using ```size()``` and ```at()``` functions with a plain C-array. This is only possible in C++11 and further: http://www.cplusplus.com/reference/array/array/size/ http://www.cplusplus.com/reference/array/array/at/

**Comment by Bob-Z** [comment]
Please do not merge now, I will add @ulteq  modif on getCustomLightVisible for consitency.

**Comment by only-a-ptr** [comment]
@Bob-Z OK. However, that would be 4 commits for one simple change. For cleaner commit history, please create a new branch at https://github.com/Bob-Z/rigs-of-rods/commit/b7b9810f189b3837c14bd46cd6052b92c6eb3f12 and prepare a single clean commit to be merged.

**Pull request closed without merging**
