### PR TITLE
Sandstorm HDR sky and brightness control

### PR DESCRIPTION
**Pull request by tritonas00**
This improves the default Sandstorm sky and lighting. Also increased default ambient light color from 0.3 to 0.5, do prevent very dark spots.

gg

Textures taken from https://polyhaven.com/a/kloofendal_48d_partly_cloudy_puresky

### CODE REVIEW

**Comment by CuriousMike56** [comment]
Sky is too dark for me:
screenshot_2023-06-12_13-37-31_1
screenshot_2023-06-12_13-38-51_1
No difference with shadows on/off.

**Comment by tritonas00** [comment]
Yep, i didn't change the default values, just added the slider for it. I will boost the default values a bit. The slider works on DirectX?

**Comment by CuriousMike56** [comment]
> Yep, i didn't change the default values, just added the slider for it. I will boost the default values a bit. The slider works on DirectX?

Slider works but only changes the terrain brightness. Sky itself remains dark on all terrains I tested.

**Comment by tritonas00** [comment]
What happens if you change this https://github.com/tritonas00/rigs-of-rods/blob/hdr-sky/resources/materials/ror.material#L1913 to `off`?

**Review by only-a-ptr — APPROVED** [review]
Works great on Win10 (dx9 / GL)

**Comment by CuriousMike56** [comment]
👍

**Comment by only-a-ptr** [comment]
obrazek
Brightness slider works fine under Win10 + DirectX9.
The scale needs to be longer though: current max looks like partly covered sun, it should be full sun.

**Comment by tritonas00** [comment]
https://github.com/RigsOfRods/rigs-of-rods/pull/3100

**Pull request closed without merging**
