### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by only-a-ptr**
I'm on a fixing spree.
More to come...

### CODE REVIEW

**Comment by Hiradur** [comment]
Apparently you built against an old version of MyGUI. You have to replace toValue() with getValue() in GUIInputManager.cpp

see:
https://github.com/RigsOfRods/rigs-of-rods/commit/591474df4d4432cbbea4f0389ef5eb2bde49f1bf

**Comment by only-a-ptr** [comment]
@Hiradur I'm building against RoR-Deps26 as-is. I didn't notice we partially obsoleted it.

Do we have updated build instructions? TBH I lost track of our developer resources.

**Comment by Hiradur** [comment]
There are no up to date instructions for Windows. You can see the required versions of libraries here: http://www.rigsofrods.com/wiki/pages/Compiling_Sources_under_Linux#Library_and_Software_versions_required_to_compile_Rigs_of_Rods

I think @Max98 wanted to upload a new Windows dep archive.

current errors:
```
[0m[100%] [32mBuilding CXX object source/main/main_sim/CMakeFiles/RoR.dir/MainThread.cpp.o
[0m/home/travis/build/RigsOfRods/rigs-of-rods/source/main/main_sim/MainThread.cpp:113:21: error: #if with no expression
 #if ROR_USE_OGRE_1_9

                     ^
/home/travis/build/RigsOfRods/rigs-of-rods/source/main/main_sim/MainThread.cpp:131:21: error: #if with no expression
 #if ROR_USE_OGRE_1_9

                     ^
/home/travis/build/RigsOfRods/rigs-of-rods/source/main/main_sim/MainThread.cpp: In member function â€˜void RoR::MainThread::Go()â€™:
/home/travis/build/RigsOfRods/rigs-of-rods/source/main/main_sim/MainThread.cpp:650:9: error: â€˜overlay_systemâ€™ was not declared in this scope
  delete overlay_system;

         ^
make[2]: *** [source/main/main_sim/CMakeFiles/RoR.dir/MainThread.cpp.o] Error 1
```

Sorry, but Travis screws up the characters for some reason

For the first one: You should use #ifdef ROR_USE_OGRE_1_9
For overlay_system: should be fixed when you use #ifdef ROR_USE_OGRE_1_9

**Comment by Hiradur** [comment]
Looks good, do you want to merge it now or add more fixes?

**Comment by only-a-ptr** [comment]
@Hiradur I'll definitely fix some more. There are them high-priority :)

**Comment by only-a-ptr** [comment]
@Hiradur I've paused the bugfixing due to my Lua-Powertrain project. Feel free to merge this.

**Pull request merged**
