### PR TITLE
Repository Manager

### PR DESCRIPTION
**Pull request by tritonas00**
An in game repository manager, thanks to the new upcoming API provided by @Zentro and the help of @only-a-ptr. Three view modes are available, categories, searching, sorting and the basic functionality of installing/updating and removing mods, in the `mods` folder.

kk1
kk2
kk3
kk4

### Limitations

Currently the panel will detect/(re)install/update/remove mods **only** in the `mods` directory. We may refine in the future.

Closes https://github.com/RigsOfRods/rigs-of-rods/issues/2450
Closes https://github.com/RigsOfRods/rigs-of-rods/issues/229

### CODE REVIEW

**Comment by cryham** [comment]
Wow looks great.
I wanted to ask something. Sorry if off topic, but:
the only thing that I miss in here (and on forum browser) is a license info like e.g. GPL, CC-BY-SA, etc.

I guess it is safe to assume that except for just 3 things (that are GPLed in https://github.com/RigsOfRods/content repo), all else has no license what-so-ever right? Meaning anybody can only download it and use in RoR right?
And likely nothing will happen change here, because that would require contacting authors (likely some left years ago) and ask them to specify and release their content with a license, like CC or so. Also BTW some cars have textures with logos etc, which is not legal to use anyway.

**Comment by tritonas00** [comment]
> Wow looks great. I wanted to ask something. Sorry if off topic, but: the only thing that I miss in here (and on forum/resources browser) is a license info like e.g. GPL, CC-BY-SA, etc.
> 
> I guess it is safe to assume that except for just 3 things (that are GPLed in https://github.com/RigsOfRods/content repo), all else has no license what-so-ever right? Meaning anybody can only download it and use in RoR right? And likely nothing will change here, because that would require contacting authors (likely some left years ago) and asking them to specify and release their content with a license, like CC or so, and them agreeing. Also BTW some cars have textures with logos etc, which is not legal to use anyway or probably textures made from non-CC stuff etc which makes CC licensing impossible too.

We will add this info in the panel

**Review by only-a-ptr — APPROVED** [review]
I fixed a few details I noticed and I think it's perfect now.

**Comment by tritonas00** [comment]
> improved download speed/rem. time calc

welp now its off for me, both speed and remaining time
kk

my max download speed in 2MB/sec, `speed/10` shows it correctly, i guess it depends on the connection

maybe we should just remove them and leave only downloaded MB of full filesize MB

**Comment by only-a-ptr** [comment]
> welp now its off for me, both speed and remaining time

Thanks for the CURL link, I took another shot and I'm pretty confident it works right now. In both cases I coded & tested using jumpy wi-fi on train :)

> maybe we should just remove speed and leave only downloaded MB of full filesize MB + a better remaining time and call it a day

Agreed. If you're still not happy with it, just erase my commit or do whatever edit you like, then merge this.

**Comment by tritonas00** [comment]
Yep, still problems with. Lets go KISS

kk

**Comment by bippy89** [comment]
wheres the download

**Comment by only-a-ptr** [comment]
> @bippy89 wheres the download

https://www.rigsofrods.org/download

**Pull request merged**
