### PR TITLE
Separate BeamData.h into smaller header files

### PR DESCRIPTION
**Pull request by Aperion**
This separates the most commonly used parts of BeamData.h into separate headers.  I've included the new headers in BeamData.h to avoid breaking existing code.

### CODE REVIEW

**Comment by Max98** [comment]
Did you sync your local with upstream before doing this? Because this define is missing:

>//skidmarks v2
>bool isSkiding;

**Comment by Aperion** [comment]
OMG. I merged that about 3+ times tringt o get the commits sorted out. can't beleive I missed  that in the one I pushed :( I will fix real quick

**Comment by Max98** [comment]
hehe :P
Also, it would be great if next time you could use the Commit style, so in the Upstream, all commits will be clear: http://www.rigsofrods.com/wiki/pages/Commit_style

**Comment by Aperion** [comment]
I'll try to remember. Go ahead and close, I'll redo tomorrow. Night!

**Comment by Max98** [comment]
Alright, Goodluck! :P

**Pull request closed without merging**
