### PR TITLE
OGRE 1.9, MyGUI 3.2.2 upgrade

### LINKED ISSUE #156: MyGUI 3.2.2 not supported
Compilation of latest git snapshot fails with the following error:
```
[ 67%] Building CXX object source/main/main_sim/CMakeFiles/RoR.dir/__/gui/GUIInputManager.cpp.o
/home/artem/AUR/rigsofrods-git/src/rigs-of-rods/source/main/gui/GUIInputManager.cpp: В функции-члене «virtual bool GUIInputManager::keyPressed(const OIS::KeyEvent&)»:
/home/artem/AUR/rigsofrods-git/src/rigs-of-rods/source/main/gui/GUIInputManager.cpp:226:22: ошибка: «struct MyGUI::KeyCode» has no member named «toValue»
  int scan_code = key.toValue();
                      ^
source/main/main_sim/CMakeFiles/RoR.dir/build.make:3435: ошибка выполнения рецепта для цели «source/main/main_sim/CMakeFiles/RoR.dir/__/gui/GUIInputManager.cpp.o»
make[2]: *** [source/main/main_sim/CMakeFiles/RoR.dir/__/gui/GUIInputManager.cpp.o] Ошибка 1
CMakeFiles/Makefile2:111: ошибка выполнения рецепта для цели «source/main/main_sim/CMakeFiles/RoR.dir/all»
make[1]: *** [source/main/main_sim/CMakeFiles/RoR.dir/all] Ошибка 2
Makefile:75: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2
```

Using MyGUI 3.2.2 compiled against OGRE 1.8 on Arch Linux x86-64.

https://aur.archlinux.org/packages/my/mygui-ogre1.8/PKGBUILD
https://aur.archlinux.org/packages/ri/rigsofrods-git/PKGBUILD

### PR DESCRIPTION
**Pull request by skybon**
This is a large patchset that enables OGRE 1.9.0 and MyGUI 3.2.2 support for Rigs of Rods. Extensive work in tens of files had to be done in order to make it work. Hopefully building RoR will become even easier on modern operating systems.

Big thank you to @Max98, this work is based on his efforts.

Highlights:
* Builds against and runs on OGRE 1.9.0.
* Ditto about MyGUI 3.2.2.
* A lot of includes fixed, uses angular brackets now.
* Removed several files copy-pasted from OGRE base distribution.
* Uses custom upgraded builds of Caelum and PagedGeometry available in RigsOfRods org repos.

Known issues:
* Segfaults on exit. This is caused by problems with OgreOverlay deletion at the end of ```MainThread::Go()```. Not a major issue (does not obstruct gameplay), currently under investigation.

Fixes #156

### CODE REVIEW

**Comment by Speciesx** [comment]
Will you also provide new dependencies? The current ror-dependencies-26 is 3 years old.

**Comment by Max98** [comment]
@Speciesx I'll be in charge for that.

**Comment by Speciesx** [comment]
Why you change the ror Website and Wiki to rigsofrods.github.io? I thought this is only a developer preview.

**Comment by tritonas00** [comment]
Nice! Compiled and run fine!

**Comment by fidoj** [comment]
compiled and worked ok, tested trains, loads, cranes. vehicles

**Pull request merged**
