### PR TITLE
🔧 Moved pagedgeometry into the source tree

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
See #1468  
Because we currently have Skyx and Hydrax is the source tree, I think is odd to have only one external ogre-plugin

### CODE REVIEW

**Comment by tritonas00** [comment]
i use ogre 1.8 and pagedgeometry 1.8 branch https://github.com/RigsOfRods/ogre-pagedgeometry/tree/Ogre-1.8, will this work? 

will test asap

**Comment by tritonas00** [comment]
yep, doesn't work here: https://pastebin.com/aE7wYReJ

**Comment by AnotherFoxGuy** [comment]
@tritonas00 It should be fixed now

**Comment by tritonas00** [comment]
still the same error

**Comment by tritonas00** [comment]
ok now i get: https://pastebin.com/uqsnAWcc

**Comment by tritonas00** [comment]
now at 50% i get: https://pastebin.com/uqsnAWcc

**Comment by AnotherFoxGuy** [comment]
@tritonas00 Coud you try running ```git reset --hard 749603db14981a076d346696aee16c4f7af9e418``` before builing?

**Comment by tritonas00** [comment]
this goes me back to m_reflection_rtt_texture error in water.ccp (fix is in https://github.com/RigsOfRods/rigs-of-rods/pull/1461)

**Comment by tritonas00** [comment]
maybe its a simple statement error? (error: expected ‘;’ before ‘if’)

https://pastebin.com/wU7DBBB3

**Comment by AnotherFoxGuy** [comment]
I forgot a few semi-colons, it should be fixed now

**Comment by tritonas00** [comment]
one staticCast left in GrassLoader.ccp :smiley: https://pastebin.com/kw6EAR5V

**Comment by tritonas00** [comment]
now in WindBatchedGeometry.cpp https://pastebin.com/quNt2C5i

**Comment by tritonas00** [comment]
it works, thank you! :heart:

**Comment by Speciesx** [comment]
>Because we currently have Skyx and Hydrax is the source tree, I think is odd to have only one external ogre-plugin

But https://github.com/OGRECave/ogre-pagedgeometry still more or less maintained, Skyx and Hydrax not.

**Comment by tritonas00** [comment]
well, this makes linux packaging a bit easier, one dependency less

**Comment by paroj** [comment]
alternatively, you can add stuff as git submodules instead of copying it. For e.g. in https://github.com/OGRECave/ogre-imgui imgui is referenced that way.
At this you point to specific commits which allows updating everything in lock step.

**Comment by tritonas00** [comment]
@AnotherFoxGuy @only-a-ptr @ulteq 

Since pagedgeometry is going into ror's source tree, like skyx and imgui, whould be nice to add caleum also?

So after ogre 1.11 update, humble users who just want to compile and play ror will have much less dependencies to deal with:

- sync pagedgeometry from ogrecave and integrate it to source
- sync caleum from ogrecave and integrate it to source
- fix skyx with ogre 1.11 or completely remove it if its dead 
- completely replace mygui with imgui

then ror will only need: angelscript wxgtk ogre and socketw

just a thought

**Comment by only-a-ptr** [comment]
Time has passed and conditions have changed:
* SkyX is not doing so well - poor source code (I looked), bad player response (supposedly bad visual appearence, I didn't check).
* Caelum is doing great - it was recently [adopted by OGRECave](https://github.com/OGRECave/ogre-caelum) and updated to OGRE.11. I looked in the sources and they're way superior to SkyX's. It still uses the zombie-tech Cg shaders, but porting them is a question of time, I looked at it and they're short and self-contained, it should be a straightforward task.
* PagedGeometry was also adopted by OGRECave: https://github.com/OGRECave/ogre-pagedgeometry

Thus I propose a new approach:
* Ditch SkyX from codebase
* Attach OGRECave/Caelum as Git submodule and get it's shaders ported to modern tech.
* Attach OGRECave/PagedGeometry as Git submodule

**Comment by AnotherFoxGuy** [comment]
I already started adding the OGRE plugins as Git submodules, I will create a branch for it later this week

**Comment by AnotherFoxGuy** [comment]
Branch created: https://github.com/AnotherFoxGuy/rigs-of-rods/tree/ogre-submodules

**Pull request closed without merging**
