### PR TITLE
Don't process incoming network data when paused

### PR DESCRIPTION
**Pull request by tritonas00**
Fixes crash when we are in paused menu and new clients come in/out. Data processing resumes when unpaused.

### CODE REVIEW

**Comment by only-a-ptr** [comment]
Since when is pausing possible in MP?

**Comment by tritonas00** [comment]
eeh, a long time i think

**Comment by only-a-ptr** [comment]
It's still weird. And even weirder with this change - the player will "pause" other players 😮

**Comment by tritonas00** [comment]
i paused player one (presses escape), moved and spawned a car in player two
scene in player one updated as soon as exited pause menu again

but i will test more

**Comment by tritonas00** [comment]
> the player will "pause" other players

tested again. the player pause himself to other players, as expected, other players continue normally

**Comment by tritonas00** [comment]
https://github.com/RigsOfRods/rigs-of-rods/pull/2658

**Pull request closed without merging**
