### PR TITLE
Fixes

### LINKED ISSUE #2430: Default aircraft lights don't work anymore on 0.4.8
On the 0.4.7 version, every aircraft had default red and green navigation lights as well as flashing white strobe lights, but since I updated to 0.4.8, I figured out that these don't work anymore on any aircraft. You can try it on the default an12 : only the red flashing lights (these were added by the author I think) will turn on. Tell me how I can help more if needed

### PR DESCRIPTION
**Pull request by only-a-ptr**
Fixes #2430

Problem: Beacon props generated by `ActorSpawner::ProcessWings()` weren't passed on to GfxActor.
Reason: Props were passed on GfxActor creation which  happened  before   `ActorSpawner::ProcessWings()`
Solution: Added `GfxActor::RegisterProps()` which is invoked after `ActorSpawner::ProcessWings()`

### CODE REVIEW

**Comment by tritonas00** [comment]
Seems to works fine!

Although they stop when you get out of the actor, don't know if that's normal.

**Review by tritonas00 — APPROVED** [review]

**Comment by po185021** [comment]
> @tritonas00 Although they stop when you get out of the actor, don't know if that's normal.

Uhh... I bet all other prop animations stop as well when you get out of the vehicle. That's most likely bug with my 'async scene' code, I'm pretty sure I don't update props for non-occupied actors.

**Comment by only-a-ptr** [comment]
> @tritonas00 Although they stop when you get out of the actor, don't know if that's normal.

That's actually a fantastic observation which provoked 2 additional fixes 👍

**Comment by tritonas00** [comment]
Works great except one issue, the blinker lights in the HUD (mygui) are not working now.

**Comment by only-a-ptr** [comment]
Fixed both the blinker HUD lamps and the logged `mp_*` cvars.

**Review by tritonas00 — APPROVED** [review]

**Pull request merged**
