### PR TITLE
[WIP] Greatly simplified GVars and logging

### PR DESCRIPTION
**Pull request by only-a-ptr**
I couldn't resist doodling future scripting concepts, and I ran into actual need to access GVars by name from script/console (I absolutely plan that when I remake console with ImGUI). Also, the code which maps RoR.cfg entries to GVars is silly.

While thinking how to do it, it struck me how bloated the GVars code is for no good reason, except that I sucked at C++ at the time.

### CODE REVIEW

**Comment by only-a-ptr** [comment]
@tritonas00 Buggy string type conversions, I'll fix it.

**Comment by only-a-ptr** [comment]
@siradam7th Could you take a look at this for me?

I have string conversions of `RoR::Str<>` all wrong, the conversion operators sometimes kick in and sometimes not and I don't exactly understand why. I mostly worked it around with explicit `.ToCStr()` calls.

Also, as pointed out by @tritonas00, some `c_str()` conversions are missing.

**Comment by only-a-ptr** [comment]
I couldn't resist...

Idea: instead of mixed legacy logging methods
* LOG() pseudomacro
* Log(), LogFormat() global functions
* LOGSTREAM macros

let's use following practice:
* We log to OGRE log and prefix our messages with [RoR|$TITLE] or at least [RoR] marker
* Code to log single message: `LogStream("logger-test") << "This" << " logger" << " works";`
* Helper function in major classes:
```
LogStream Log() { return LogStream("ClassName"); } // Usage: this->Log() << "stuff";
```

**Comment by ulteq** [comment]
Can we please at least keep the old syntax?

**Comment by only-a-ptr** [comment]
> Can we please at least keep the old syntax?

Which one, and for what area/purpose exactly?

I'd like the RoR.log to contain `[RoR]` entries from us and unprefixed entries from OGRE. Currently it's mixed, I added the prefixes ad-hoc to places, there are outdated prefix formats... Why not unify it?

I was thinking @siradam7th might help us cleaning this up.

**Comment by ulteq** [comment]
> We can keep RoR::Log(const char*) and modify it to add [RoR] prefix automaticallly.

:+1:

**Comment by AnotherFoxGuy** [comment]
> @only-a-ptr UPDATE: Or maybe we could be 😎 and use http://fmtlib.net

It is available on bintray: https://bintray.com/bincrafters/public-conan/fmt%3Abincrafters
So you can add `fmt/5.2.0@bincrafters/stable` to `conanfile.txt`,
run `conan install`
and add this to `source/main/CMakeLists.txt`:
```CMake
# --- fmt - Small, safe and fast formatting library ---
if(CONAN_FMT_ROOT)
  target_link_libraries(${BINNAME} PRIVATE CONAN_PKG::fmt)
  target_include_directories(${BINNAME} PRIVATE CONAN_PKG::fmt)
  target_compile_definitions(${BINNAME} PRIVATE USE_FMT)
else ()
```

And you can start implementing fmt

**Pull request closed without merging**
