### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by Hiradur**
- fixes waves being rendered at wrong height (part of #174, #277)
- fixes sandstorm sky not being loaded on case-sensitive platforms (no ticket)
- fixes performance regression coming from not multithreading beams #1 
- fixes HydraX water appearing black with OpenGL (no ticket)

### CODE REVIEW

**Comment by tritonas00** [comment]
Nice, but the character changed color after those commits :P

**Comment by Hiradur** [comment]
I think that happened before in https://github.com/RigsOfRods/rigs-of-rods/pull/300

**Comment by tritonas00** [comment]
I compiled yesterday and didn't notice the issue.

**Comment by Hiradur** [comment]
max98 may have fixed it in the meantime, my repo is not entirely up to date.

**Comment by tritonas00** [comment]
Ok then :)

**Comment by only-a-ptr** [comment]
@Hiradur :+1: Great work

**Comment by Max98** [comment]
@tritonas00 Try compiling from the upstream, and if it doesn't work, can you post your logs?

**Comment by tritonas00** [comment]
Ok, i m dumb, works fine from upstream

**Pull request merged**
