### PR TITLE
[WIP] Truck format: improve backw. compat., add functional export

### PR DESCRIPTION
**Pull request by only-a-ptr**
This PR signifficantly improves backward compatibility of the truck file parser. The file format itself is not changed. Internal documentation (README) is also improved.

This PR also fixes the internal truck exporter. Currently it has no practical use, but I want to keep it functional for the future. To test it, press "Export current truck" button to TopMenubar/Tools menu. It works only for unzipped mods and saves a truck file "export_{original filename}" generated by exporter.

# Truck configurations (sectionconfig)

Because the word "section" is ambiguous (nodes/beams/stuff are also "sections"), the 'section/end_section' file portions are reffered to as "segments".

The doc.rigsofrods.org description is misleading - Here is an example of how it really works:
```
; Configurations of the truck (case sensitive); player selects one to spawn.
; sectionconfig <version (unused)> <config name>
; -------------
sectionconfig -1 Config_A
sectionconfig -1 Config_B

; Define a segment with list of configurations it belongs to. Case sensitive!
; section <version (unused)> <config names ...>
; -------
section -1 Config_A
     ; nodes, beams, anything...
end_section
section -1 Config_B
     ; nodes, beams, anything...
end_section
; create segment for multiple configurations
section -1 Config_A, Config_B
     ; nodes, beams, anything...
end_section
; continue with 'implicit segment'.
     ; nodes, beams, anything...
; create a segment for all configurations (empty config list)
section -1
    ; nodes, beams, anything...
end_section
```

### CODE REVIEW

**Comment by tritonas00** [comment]
A compiler warning:
```[ 97%] Building CXX object source/main/CMakeFiles/RoR.dir/scripting/GameScript.cpp.o
/home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/scripting/GameScript.cpp:791:8: warning: extra tokens at end of #endif directive [-Wendif-labels]
  791 | #endif USE_CURL```

Other than that it works great. Exported Desperado keeps spinning and stuff but i assume is from the parser issues that this PR will help you to fix.
Also exported desperado misses flexbodies (you can see the difference in the selector by selecting original and exported back and forth)

**Comment by only-a-ptr** [comment]
I fixed the compiler warning.
Crashes should be gone now.
The Desperado export is still broken but I'll fix it along with the parser in next PR, it's closely related.

**Comment by only-a-ptr** [comment]
I jumped ahead and made my planned truck changes in this branch. Originally I wanted to merge this first but I needed to get it out of my head.

DON'T BOTHER RUNNING THE LAST COMMIT - It'll crash when spawning anything.

**Comment by only-a-ptr** [comment]
Closing this as too heavyweight and buggy.

All cleanups were cherrypicked to https://github.com/RigsOfRods/rigs-of-rods/pull/2829. After that's complete, I'll re-apply the corrections invented here in a cleaner fashion.

**Pull request closed without merging**
