### PR TITLE
Added argument 'node_mass' to truckfile/cinecam

### PR DESCRIPTION
**Pull request by only-a-ptr**
This adds a new, optional argument to `cinecam` - mass of the generated node.
```
cinecam
;  x,   y,   z, <---------8 bindings--------->, Optional: spring, damping, node-mass
0.66, 2.0, 1.8, 75, 76, 77, 78, 73, 74, 53, 54,           8000.0,   800.0,        20
```

#closes https://github.com/RigsOfRods/rigs-of-rods/issues/1352

As usual, there are some extra refactors to test 😎

### CODE REVIEW

**Comment by Michael10055** [comment]
Hm. I'm kinda confused here.

Charger's lightweight n/b just explodes now, even without the cinecam.
Gavril MV4S explodes as well. However, the Gavril Omega doesn't. There's no differences between the two vehicle's cinecam sections.

**Comment by only-a-ptr** [comment]
@Michael10055 My fault, sorry. My change was short-sighted. I ignored all the node mass adjustments happening after cinecam processing: https://github.com/RigsOfRods/rigs-of-rods/blob/e053e4a504026e84cada331e34f0294ea1dac5a7/source/main/physics/Beam.cpp#L867-L918. 

Fixing in progress....

**Comment by Michael10055** [comment]
Works!

```
cinecam
0.0, 1.218, 0.0, 0, 0, 1, 40, 2, 2, 3, 3, 4000, 150, 1
```

ror_2017-07-14_11-20-19

All other mods seem to work exactly as before. 👍

**Comment by tritonas00** [comment]
I can't notice any difference either, no crashes so far

**Comment by only-a-ptr** [comment]
Please try changing gravity, too. That's a single moment when node masses get re-calculated. It's also the only possible source of problems I can think of.

**Comment by Michael10055** [comment]
screenshot_2017-07-17_14-36-00_1

No issues with changing the gravity.

**Pull request merged**
