### PR TITLE
Parser corrections (nodes2, forset, sectionconfig)

### LINKED ISSUE #171: Misc. spawn issues
screenshot_1
screenshot_2

### LINKED ISSUE #2881: `sectionconfig` and `nodes2` broken since 2013.
Hello.

About a year ago I studied the truck file parser of v0.4.0.7 (year 2013, before all my changes) and I discovered that `sectionconfig` and `nodes2` were far more powerful than anyone knew. See this example:

```
; this defines a list of configurations the player can select from when spawning.
sectionconfig -1 VanillaSportscar
sectionconfig -1 SportscarWithRearWing
sectionconfig -1 SportscarWithFrontWing
sectionconfig -1 SportscarWithBothWings

; the vanilla car: nodes2, beams

section -1 SportscarWithFrontWing, SportscarWithBothWings
; the front wing: nodes2, beams
end_section

section -1 SportscarWithRearWing, SportscarWithBothWings
; the rear wing: nodes2, beams
end_section

; anything else using named nodes
```

The takeaways:
- Each `section/end_section` could be part of multiple configurations
- Each `section/end_section` could introduce arbitrary number of `nodes2`. Anything that referenced nodes by name could follow and it would not break

Unfortunately this was never documented... I saw a single mod "KickerRamp" in the archive which would use sectionconfig to put additional named nodes in the middle of the truck file. Apparently someone knew about the functionality but most people didn't. Also, it was very difficult to understand from the code itself, so I removed it as part of cleanup efforts. I'm currently working to restore it:

- #2711 - my first attempt, restored everything but was too sloppy and buggy. Abandoned.
- #2829 - Ongoing preparation for the second attempt.

### PR DESCRIPTION
**Pull request by ohlidalp**
I reverted the parser to the original (2013 and earlier) sequential mechanic.
That means things that one worked are back, but so are some restrictions that didn't apply in the time between.

**ALPHA STATUS - Features and restrictions can still change.**

**Returning features:**
* everything `except authors, fileinfo, guid, description` can now be in `section/end_section`.
* you can add various number of nodes2 in each `section/end_section`.
* all elements except `forset` support named nodes (nodes2).
* you can specify multiple configs for a single `section`, like this: 
   ```
   sectionconfig 0 conf1
   sectionconfig 0 conf2

   section 0 conf1, conf2
   ; applies to both!
   end_section
   ```
**Returning restrictions:**
* the `fusedrag autocalc` only takes in consideration nodes defined before it, so by defining them after it you basically instruct the game to exclude them from the autocalculation.
* the `managedmaterials` must be specified before the props/flexbodies/flares which use them, otherwise they will end up all white.
* Essentially all the "A must come before B" restrictions are back.

**Bugfixes:**
* Fixes #171
* Fixes #2881

**Improvements:**
* `forset` is now a regular directive - you can put comments, empty lines or even section in between the `flexbody` proplike-line and the `forset`. 
* in the selector UI, the configuration combobox is now on top and the values below (click the ShowDetails checkbox) are accurately counted for that configuration. The counts are all saved in modcache. Cachefile format version was bumped.
obrazek

### CODE REVIEW

**Comment by tritonas00** [comment]
Issue list (will update as i find more issues)

- https://forum.rigsofrods.org/resources/grave-digger-35.648/ (no wheels)
- https://forum.rigsofrods.org/resources/starbus-concept-bus.373/ (black screen)
- https://forum.rigsofrods.org/resources/1949-ford.283/ (missing one wheel)
- https://forum.rigsofrods.org/resources/1982-di-sportster-390c.252/ (segfault)
- https://forum.rigsofrods.org/resources/gavril-omega-det.591/ (spawns with doors broken)
- https://cdn.anotherfoxguy.com/repo-backup/6684669f7ce10278e45e8dbb16f61016fea2ad3c_Banshee.zip (segfaults when driving)
- Skyvan (spawns with direction up)
- https://forum.rigsofrods.org/threads/sisu-sa-150-240.1352/ (segfault)
- https://cdn.anotherfoxguy.com/repo-backup/802fe52c763c3c7d9c6698a833f3ac21e1e6d137_ple003_Zil135Uragan.zip (segfault)
- https://forum.rigsofrods.org/resources/mitsubishi-pajero-gbv-off-road-caravan.478/ (broken parts)

**Comment by only-a-ptr** [comment]
The cache should automatically update on version bump, but it's bugged in master.
Liebherr13HM spawns fine for me (f1testtrack, skidmarks on) but it's very jumpy at the start - might be a bug in  #2829

**Comment by tritonas00** [comment]
> Liebherr13HM spawns fine for me (f1testtrack, skidmarks on)

Yeah, the skidmarks issue seems to be gone for me also

**Comment by only-a-ptr** [comment]
I'm wrestling a real mystery.... Honda Accord (download: https://forum.rigsofrods.org/resources/honda-accord.281/) blows up, even though all N/B values are exactly the same as in my v0.4.0.7 retro-build. I made a debug dump from both versions (option `diag_actor_dump`) and compared with diff tool... spring, mass, damp, refLen, bounding, short/long bounds... all equivalent.
And it doesn't happen after repair using Backspace key, only at initial spawn.
The GIF is slow-motion with ratio 0.07 btw.
parserRevertHondaAccordMystery-w300
It looks like I'm going to have to take a detour and create a diagnostic tool which would let me inspect the simulation step-by-step.

**Comment by only-a-ptr** [comment]
**Purpose:** My great personal amend - to make the vehicle parsing/spawning work at least as well as in v0.4.0.7 (year 2013, before I started working on it).

**Estimate:** 10 man days. I've got stuck with a glitch: https://github.com/RigsOfRods/rigs-of-rods/pull/2922#issuecomment-1246750364. Otherwise it pretty much works.

**Comment by tritonas00** [comment]
- 1982 Ford Mustang missing textures (https://forum.rigsofrods.org/resources/ford-mustang-1979-1982.712/)
- Austin Mini needs exorcism (https://forum.rigsofrods.org/resources/1965-austin-mini.298/)

**Comment by only-a-ptr** [comment]
The Austin Mini is posessed by `fusedrag autocalc` which is misplaced - it needs to be placed after `nodes`, otherwise it produces garbage. This is a classic limitation of the old parser which wasn't effective in between 2013-2023 but now is back - along with all the other "B must come after A" limitations, actually. The Mini must have been either updated in between 2013-2023 when the order didn't matter, or it may have used old-style fusedrag before. Either way, both the mod and the docs must be corrected:
* Austin Mini https://forum.rigsofrods.org/resources/1965-austin-mini.298/ must be updated to have `fusedrag autocalc` after `nodes`.
* Docs must be updated https://docs.rigsofrods.org/vehicle-creation/fileformat-truck/#fusedrag - the `autocalc` only takes in consideration nodes defined above, so by defining them after you basically instruct the game to exclude them from the autocalc.

**Comment by only-a-ptr** [comment]
The Ford Mustang has `managedmaterials` after the wheels and some flexbodies (rear wing...) that use them. Again, this didn't matter between 2013-2023 but now it's back. I updated the PR summary to mention this.

**Comment by CuriousMike56** [comment]
Current issues I've noticed so far:

- Soundsources are always defined before nodes, this warning is incorrect 
image
- Console spammed with debug info relating to beams
- Vehicle wind sounds from e.g. Gavrils continues playing after deletion
- Ford F-Series Pack (https://forum.rigsofrods.org/resources/ford-f-series-pack.17/) issues:
  - Fusedrag section is also before nodes.
  - Parser claims forsets are defined available node range, which doesn't appear to be true:
  image
- SM V5 monster truck pack (https://sim-monsters.com/files/file/4278-sm-v5/) resets infinitely. Amusingly, the truck travels quite quickly while resetting 😄 https://streamable.com/03mk1j. I assume this is caused by `set_default_minimass` not being parsed correctly (T menu claims the truck weighs 1.71 tons, should be 7.74 tons)
image

**Comment by ohlidalp** [comment]
Closing as stale and no longer mergeable. Also the problem it solves isn't really visible.

**Pull request closed without merging**
