### PR TITLE
Fixed broken actor stream setup

### PR DESCRIPTION
**Pull request by ulteq**
The actor stream setup was never executed due to a flaw in the `ar_uses_networking` logic.

### CODE REVIEW

**Comment by only-a-ptr** [comment]
I never really understood what `ar_uses_networking` is, thanks for investigating, but now with `//...might have...`  I think it's bad design.

⌛️ Looking at it...

**Comment by ulteq** [comment]
`//...might have...` since there won't be any remote actors if you play alone on multiplayer.

**Comment by only-a-ptr** [comment]
Sure, but both the variable name and comment look weird.

I suggest `bool ar_net_transmitting:1; //!< We have a working remote instance`. The desire to setup stream should be implicit when GVar `mp_state == CONNECTED`

**Comment by ulteq** [comment]
I also thought about renaming the variable, but I failed at coming up with a good name.

`ar_net_transmitting` sounds about right.

**Comment by only-a-ptr** [comment]
> Or we remove it and just check the mp_state.

That would be ideal, but can we do that? Don't we need to distinguish ready-to-go actors from stream-setup-in-progress ones?

**Comment by only-a-ptr** [comment]
> what if we wanted to support...

Then we'll code it, like anything else we want to support. 😄 

> ...static actors which don't need to be synced across the net

Sounds like one of many possible distant future continuities 👾 But as long as all RoR's actors are "trucks", "loads" and this sort of stuff, we're fine.

**Pull request merged**
