### PR TITLE
Angelscript update to version 2.26.2

### PR DESCRIPTION
**Pull request by Speciesx**
https://sourceforge.net/u/neorej16/rigsofrods/commit_browser
I've this update from here Commits 061b89 - c7e9ce. Tested on windows build and everything seems to work.

### CODE REVIEW

**Comment by ulteq** [comment]
From Travis:
```
/home/travis/build/RigsOfRods/rigs-of-rods/source/angelscript_addons/debugger/debugger.cpp:484:56: error: no matching function for call to â€˜AngelScript::asIScriptModule::GetGlobalVar(AngelScript::asUINT&, const char**, const char**, int*)â€™
      mod->GetGlobalVar(n, &varName, &nameSpace, &typeId);
```

**Comment by Hiradur** [comment]
> From Travis:

Travis can't build this because it's still using Angelscript 2.22.1.

**Comment by Speciesx** [comment]
@ulteq 
> @Speciesx What's with the newer versions of AngelScript? Could we use the latest stable version 2.31.0?

already tried, i get 44 errors.

**Comment by Speciesx** [comment]
Maybe it's worth to integrate the other 14 commits too?

**Pull request closed without merging**
