### PR TITLE
New key map X_Box_360 with wireless receiver for linux

### PR DESCRIPTION
**Pull request by vido89**
New key map X_Box_360 with wireless receiver for linux

### CODE REVIEW

**Comment by vido89** [comment]
Sony PLAYSTATION R3 Controller Input map for linux

**Comment by paroj** [comment]
you guys really need to switch to SDL2 for the gamepad abstraction, instead of maintaining your own: https://wiki.libsdl.org/CategoryGameController

**Comment by vido89** [comment]
Yep that would be nice to have because and I quote "so you'll know that SDL_CONTROLLER_AXIS_LEFTX is always the X-Axis of the left Analog Stick" so maybe we could implement SDL2 in to RoR when some developer get some free time tnx @paroj for suggestion

**Comment by only-a-ptr** [comment]
I couldn't resist the ":smile:" reaction because this has been in my backlog since... ever. But there were always bugs attracting a lot more attention, so I never even started. But we'll definitely move to SDL2 eventually.

**Pull request merged**
