### PR TITLE
Fixed resetting the camera in first person pointing upwards

### LINKED ISSUE #1516: Resetting camera in first person view points camera upwards
Pressing NUMPAD5 (`CAMERA_RESET`) while in first person causes the camera to point upwards:
screenshot_2018-06-15_11-35-19_1
screenshot_2018-06-15_11-35-23_1

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
Fixes #1516

### CODE REVIEW

**Comment by tritonas00** [comment]
> Should the FOV also be reset when pressing NUMPAD5?

That would be nice

**Comment by Michael10055** [comment]
Now that I've tested this, The FOV shouldn't be reset:
image
image
The camera is too low now also:
image

**Comment by Michael10055** [comment]
Can this be merged? Works fine now.

**Comment by only-a-ptr** [comment]
Sorry for the long wait

**Pull request merged**
