### PR TITLE
Overall engine sound improvements

### PR DESCRIPTION
**Pull request by TechGiga**
Improves the default diesel engine sounds and the default car sounds. Addressing issue #339. Credit for the diesel sounds goes to
zikmester96, from this file:
http://www.rigsofrods.com/repository/view/5515

I modified the default soundscript to accept idle, low, med, and high rpm sounds for default car sounds instead of just idle (sounded awful) and added these V6 sounds: http://www.rigsofrods.com/repository/view/5289

P.S. I'm new to this pulling and pushing thing, so if I did something wrong, pls tell me.

And both authors have either released the sounds under a free licence or gave permission to use in other projects.

### CODE REVIEW

**Comment by Hiradur** [comment]
It's great you are trying to tackle this issue. However, we can't just use sounds from someone else unless they are under a free license (such as CC-BY). I see no license information for the sounds which means they are not freely licensed.

**Comment by gigapouch** [comment]
Oh. I thought that if they are released for Rigs of Rods but don't specify a license, they automatically use the license RoR uses.

**Comment by Hiradur** [comment]
The author probably wouldn't mind if we used it as default sounds but it would still conflict with the GPL RoR is licensed under.
You could ask him to re-release his sounds under a free license (CC-BY preferred). He would only have to include a small line in the readme or a seperate license.txt file what license these sounds are under. In order for them to be included in RoR the license needs to be GPL conform.

**Comment by gigapouch** [comment]
OK, then. However, this new RoR feature cannot be implemented until early September, though. I plan to make a RoR forum account on my 13th birthday, September 6.

**Comment by TechGiga** [comment]
I asked the author of the diesel sounds to release it under the free license, and the normal V6 car sound author already says you can use the sounds with credit.

**Comment by TechGiga** [comment]
Hey guys could you push this to the main branch now?

**Comment by Hiradur** [comment]
- "1" is a very bad commit message
- You don't give credit (commit messages don't count)
  - add the authors to Authors.md

**Comment by TechGiga** [comment]
I did the commit because I changed the sounds in my repo to the better ones, the ones I mentioned here.

I'll add the credit.

**Comment by TechGiga** [comment]
Added credit!

**Comment by Hiradur** [comment]
> I did the commit because I changed the sounds in my repo to the better ones, the ones I mentioned here.

I understand that but I was complaining about the commit message. "1" doesn't describe what you did instead it should've been "replaced diesel engine sounds".
I also don't see the credits in this PR

**Comment by TechGiga** [comment]
That's weird, I synced it and commited it to my repo.

**Comment by TechGiga** [comment]
Github finally recognised the changes in the AUTHORS.md file. Ready to be pushed.

**Comment by TechGiga** [comment]
Could you merge it? :)

**Comment by Hiradur** [comment]
Patience, everything needs to be tested and we have to make sure it meets our quality requirements. 

Here are the reasons why I won't merge it:
- some sounds are too short, making the loop point noticeable (can't be fixed)
- most sounds loop with a click at the loop point (could be fixed: http://www.rigsofrods.com/wiki/pages/How_to_create_a_high_quality_sound%28-loop%29 )
- car idle sound is too dull for my taste (can't be fixed)
- car medium and high are distorted (can't be fixed)
- the diesel sounds don't sound like the heavy diesel engines I'm used to
- your commit messages don't comply with our guidelines

game audio and engine sounds in particular are a very complex topic. As a sound designer you have to be aware of the context, make sure the sounds loop seamlessly, are correctly leveled, the loop is not too short or too long etc... the list could go on forever.

While I approve the idea of offering more default sounds for different RPM levels they have to be very well designed for an authentic experience. There may be some information on the web on how to create engine sounds but I'm sure doing that would take weeks for good results.

**Comment by TechGiga** [comment]
I understand. Maybe I could release the soundscript and the files as an unofficial "patch" on the forums?

**Comment by Hiradur** [comment]
> Maybe I could release the soundscript and the files as an unofficial "patch" on the forums or repository?

sure, go ahead

**Pull request closed without merging**
