### PR TITLE
Gfx wheels refactor (v0.4.8-alpha2)

### PR DESCRIPTION
**Pull request by only-a-ptr**
The first 2 commits here fix an upstream crash (+visual glitch) reported by @tritonas00 here: https://github.com/RigsOfRods/rigs-of-rods/issues/1008#issuecomment-320072484

The other commits are a very significant refactor of wheel meshes/flexbodies/skidmarks handling (read: I'm immediately breaking it again 😛 ).

## Status

builds, runs, it has [glitches](https://github.com/RigsOfRods/rigs-of-rods/pull/1363#issuecomment-321739777) and skidmarks aren't working.

### CODE REVIEW

**Comment by tritonas00** [comment]
will you fix and skidmarks also in this PR?

**Comment by only-a-ptr** [comment]
@tritonas00 Fix what about skidmarks? Is there an issue ticket for it? Post me a link please.

**Comment by tritonas00** [comment]
they don't show up? :smile:

**Comment by only-a-ptr** [comment]
@tritonas00 Eh, details, who'll notice? 😆 

Seriously tho, please start an issue ticket about it and try finding out where it got broken.

**Comment by tritonas00** [comment]
you last touched skidmarks code in #1271

i told you then, and mark my words, that PR will be RoR gravestone

Just kidding :smile:

**Comment by only-a-ptr** [comment]
Allright, it builds and runs, but not quite right
image

**Comment by only-a-ptr** [comment]
One wheel fixed, 3 more to go 😆 
image
As usual, fix later!

**Comment by tritonas00** [comment]
> and there are no glitches

There is an odd gap in flexbodywheels

Before:
2017-08-11-092029_1920x1080_scrot

With this PR:
2017-08-11-092128_1920x1080_scrot

**Comment by only-a-ptr** [comment]
@tritonas00 Thanks for testing!
* What type of wheels cause the "when removed" glitch?
* Also, does RoR.log show any flexbody problems for the "weird gap" glitch?

**Comment by tritonas00** [comment]
> What type of wheels cause the "when removed" glitch?

It happens with every vehicle i tried

> Also, does RoR.log show any flexbody problems for the "weird gap" glitch?

Nope, but it says something interesting about skidmarks:

`12:16:51: OGRE EXCEPTION(5:ItemIdentityException): Unable to derive resource group for skidmarks.cfg automatically since the resource was not found. in ResourceGroupManager::findGroupContainingResource at /home/babis/Downloads/rigsofrods-next-build/ogre/src/ogre_src_v1-8-1/OgreMain/src/OgreResourceGroupManager.cpp (line 1793)
12:16:51: [RoR] Error loading skidmarks.cfg (unknown error)`

**Comment by tritonas00** [comment]
Also i still can reproduce the skidmarks crash using desperado in miniredmars map

**Comment by only-a-ptr** [comment]
> Also i still can reproduce the skidmarks crash using desperado in miniredmars map

That's hard to believe - give me more detailed scenario please.

**Comment by tritonas00** [comment]
Enable skimarks in RoRConfig, load miniredmars (low gravity map) and spawn desperado. As soon you start driving: https://pastebin.com/NVy1CAGY

It's easier to reproduce with Fully manual shift, just start forcefully

**Comment by tritonas00** [comment]
This commit https://github.com/RigsOfRods/rigs-of-rods/pull/1363/commits/356d19fb0a7fbe5b3ff40ffbce3241943be367d0 alone does fix the flexwheel issue and skidmark crash. Can you push only this fix commit to master please?

**Comment by only-a-ptr** [comment]
> This commit 356d19f alone does fix the flexbodywheel issue and skidmark crash #1008 (comment). Can you push only this fix commit to master please?

@tritonas00 Eh, can I not? 😊 Working on it...

**Comment by tritonas00** [comment]
Another #1271 issue, maybe you want to fix it with this PR

Load simple terrain and spawn https://www.dropbox.com/s/u5x8byg55p7kunb/magnum.zip?dl=1
Backup to menu, reload simple terrain and spawn it again

See the wheels :stuck_out_tongue_winking_eye:

**Comment by only-a-ptr** [comment]
Removing this from v0.4.8 milestone. The signifficant changes were already submitted via other PR, the remaining refactors can wait.

**Pull request closed without merging**
