### PR TITLE
[Feature] collcabrate calculation based on collision velocity

### PR DESCRIPTION
**Pull request by ulteq**
What this does:

a) Estimate the maximum relative velocity at which `contacters` and `cabs` collide.

b) Use this estimate to calculate the maximum amount of physics steps (`collcabrate`) that can be skipped without "missing" any collision.

### CODE REVIEW

**Comment by only-a-ptr** [comment]
Minor: Looks like ```rig_t::collcabstype``` is dead code: https://github.com/RigsOfRods/rigs-of-rods/search?utf8=%E2%9C%93&q=collcabstype Clean it up pls.

**Comment by ulteq** [comment]
> Clean it up pls.

Done: https://github.com/ulteq/rigs-of-rods/commit/f61310126747de4732569d7160a956c6af02fd16

> Umm, magic 13 -> magic 80 is not a big win

Gone: https://github.com/ulteq/rigs-of-rods/commit/b1e465f4f50e8322bfa9e710c9ec40d61234a3bd

**Comment by mikadou** [comment]
Could you explain a bit more on lines
https://github.com/ulteq/rigs-of-rods/commit/dfafe84ffa3b11b8d6d614dfefd2d2c0e127568f#diff-abbec6ed672585ca1ea0964858716deeR2611
and
https://github.com/ulteq/rigs-of-rods/blob/dfafe84ffa3b11b8d6d614dfefd2d2c0e127568f/source/main/physics/Beam.cpp#L2629 ?

I think I understood everything else.

**Comment by ulteq** [comment]
> Could you explain a bit more on lines
ulteq@dfafe84#diff-abbec6ed672585ca1ea0964858716deeR2611

I have already changed:
`inter_collcabrate[i].rate = std::min(inter_collcabrate[i].distance, 80);`
into
`inter_collcabrate[i].rate = std::min(inter_collcabrate[i].distance, max_rate);`

> Can't we just do nothing in case of a collision and if no collision is detected then set the rate to the maximum rate possible for the current relative velocities

But I think you are right. That sounds like a much better idea.

**Comment by only-a-ptr** [comment]
Great work. I only have minor comments to code clarity.

**Comment by ulteq** [comment]
> if no collision is detected then set the rate to the maximum rate possible for the current relative velocities

I just tested it, it won't work. The `max_rate` is only valid for the past step, not for the following step.
I would for example fail to properly detect collisions on stacked containers.

**Comment by ulteq** [comment]
> The parser should be updated to treat options 'p' and 'u' as aliases to 'c'. Documentation should be updated to reflect this. Constants OPTION_p_10xTOUGHER and OPTION_u_INVULNERABLE should be removed.

Yes, but please let's do that in another PR and after 0.4.6 is out.

I don't want to break something due to hasty cleanups.

**Comment by only-a-ptr** [comment]
> Yes, but please let's do that in another PR and after 0.4.6 is out.
> I don't want to break something due to hasty cleanups.
Agreed :+1:

**Comment by ulteq** [comment]
Let's delay this until after 0.4.6.

**Pull request closed without merging**
