### PR TITLE
Display all 10 user flares in multiplayer.

### LINKED ISSUE #2664: Ability to see user controlled flares in multiplayer
I'm posting this here because it has been a good while since this issue has been addressed on the git. 

Why limit the amount of user controlled flares on multiplayer? If my assumption is correct, multiplayer displays the first 2 user controlled flares defined, then nothing else. If the ability is already there, why not extend it out to be able to see x amount (a reasonable quantity) of user controlled flares? Why limit it to just 2? Performance?

### PR DESCRIPTION
**Pull request by only-a-ptr**
Continued from #2690
image
Testing vehicle:
[netflare-agoras.zip](https://github.com/RigsOfRods/rigs-of-rods/files/6267505/netflare-agoras.zip)

goes by hand with RigsOfRods/ror-server#109

closes #2664

### CODE REVIEW

**Comment by tritonas00** [comment]
Now tatra custom lights don't open at all, log spams:

```
AngelScript: invalid custom-light ID -1, allowed range is 0-9
```

https://forum.rigsofrods.org/resources/tatra-t813-dakar.145/
ctrl 1 2 3 4 control the custom lights

**Comment by only-a-ptr** [comment]
@tritonas00 I can't reproduce it. Flares seem to work perfectly. I have a freshly downloaded tatra ZIP from your link.
image

**Comment by WillyB1337** [comment]
Have you pushed this update @only-a-ptr?
https://github.com/only-a-ptr/rigs-of-rods/commit/9e5ef23715db0ba7e28b58ecb58ba175ed196a88

**Comment by tritonas00** [comment]
Not on linux, fresh master, applied this PR:

kk

master works

**Comment by tritonas00** [comment]
Found the issue:

I had
kk
It works with
kk

**Comment by Zentro** [comment]
image

Works as expected here.

**Comment by tritonas00** [comment]
Eeeh 

kk

produces the

`AngelScript: invalid custom-light ID -1, allowed range is 0-9`

Master didn't had that issue, It was a bug in master?

**Comment by only-a-ptr** [comment]
With what vehicle? Open the .truck and paste the flares here please. Meanwhile I'll test it.

**Comment by tritonas00** [comment]
With the tatra

```
flares2
;RefNode,X,Y,OffsetX, OffsetY, OffsetZ, Type, ControlNumber, BlinkDelay, size MaterialName
;front
 201, 202, 206, 0.300, 0.179, 1.250, u,  1, 0, 1.5 t813_flare_brights/SOLID/TEX/t813_brights.png
 201, 202, 206, 0.300, 0.200, 0.750, f, -1, 0, 2.9 t813_flare_poslight/SOLID/TEX/t813_poslight.png
 201, 202, 206, 0.665, 0.169, 1.450, u,  2, 0, 2.0 t813_flare_brights/SOLID/TEX/t813_brights.png

 204, 205, 209, 0.333, 0.169, 1.450, u,  2, 0, 2.0 t813_flare_brights/SOLID/TEX/t813_brights.png
 204, 205, 209, 0.700, 0.209, 0.750, f, -1, 0, 2.9 t813_flare_poslight/SOLID/TEX/t813_poslight.png
 204, 205, 209, 0.700, 0.179, 1.250, u,  1, 0, 1.5 t813_flare_brights/SOLID/TEX/t813_brights.png

 123, 124, 134, 0.057, 0.000, 2.750, u,  3, 0, 2.2 t813_flare_brights/SOLID/TEX/t813_brights.png
 125, 127, 135, 0.974, 0.000, 2.750, u,  3, 0, 2.2 t813_flare_brights/SOLID/TEX/t813_brights.png
;rear
 229, 228, 224, 0.759, 0.660, 0.020, b, -1, 0, 1.5 t813_brakelights.png/SOLID/TEX/t813_brakelights.png
 233, 232, 227, 0.241, 0.660, 0.020, b, -1, 0, 1.5 t813_brakelights.png/SOLID/TEX/t813_brakelights.png

 233, 232, 227, 0.714,-1.493, 0.000, u,  4, 0, 3   t813_brakelights.png/SOLID/TEX/t813_brakelights.png

 233, 232, 227, 0.586, 1.720, 1.520, R, -1, 0, 1.5 t813_flare_brights/SOLID/TEX/t813_brights.png

 129, 130, 125, 1.000, 0.000, 0.000, l, -1,-1,-1 tracks/trans
 128, 129, 123, 0.000, 0.000, 0.000, r, -1,-1,-1 tracks/trans
 ```

**Comment by only-a-ptr** [comment]
You're right, reproduced.

**Pull request merged**
