### PR TITLE
[WIP] Improved terrain loading fault tolerance

### PR DESCRIPTION
**Pull request by only-a-ptr**
Improved fault tolerance when loading terrain.

If the terrain can't be loaded for any reason, the player will be returned to menu with a message box "failed to load terrain, see RoR.log for details".

**CAUTION: I didn't test this code yet!**

### CODE REVIEW

**Comment by tritonas00** [comment]
> Fixes #1437

That map worked without crash

**Comment by only-a-ptr** [comment]
@tritonas00 Perhaps, the issue ticket is old and I changed the code in the meantime. Anyway, there was a potential for crashing, so I mitigated it.

**Comment by AnotherFoxGuy** [comment]
If you now have a map with a missing page file, the game loads the map but if you move your character the game crashes with: 
````
Unhandled exception thrown: read access violation.
this->**m_sim_controller** was nullptr. 
````

**Comment by AnotherFoxGuy** [comment]
The game now crashes here: https://github.com/only-a-ptr/rigs-of-rods/blob/d89dc6bcf4cc1b153194d9f1ffe214963f81d22e/source/main/terrain/TerrainGeometryManager.cpp#L528
for some reason ```page.num_layers``` is always a large number such as  2016687660 or 1952541798

------

````
RoR.exe!std::vector<Ogre::Terrain::LayerInstance,Ogre::STLAllocator<Ogre::Terrain::LayerInstance,Ogre::CategorisedAllocPolicy<0> > >::resize(const unsigned int) Line 1531	
RoR.exe!TerrainGeometryManager::SetupLayers(RoR::OTCPage & page, Ogre::Terrain * terrain) Line 528	
RoR.exe!TerrainGeometryManager::configureTerrainDefaults() Line 517	
RoR.exe!TerrainGeometryManager::InitTerrain(std::basic_string<char,std::char_traits<char>,std::allocator<char> > otc_filename) Line 340	
RoR.exe!TerrainManager::LoadAndPrepareTerrain(std::basic_string<char,std::char_traits<char>,std::allocator<char> > filename) Line 165	
RoR.exe!RoRFrameListener::LoadTerrain() Line 2163	
RoR.exe!RoRFrameListener::SetupGameplayLoop() Line 2318	
RoR.exe!main(int argc, char * * argv) Line 333	
RoR.exe!WinMain(HINSTANCE__ * hInst, HINSTANCE__ * __formal, char * strCmdLine, int __formal) Line 428	
````

**Comment by only-a-ptr** [comment]
@AnotherFoxGuy Thanks for the investigation, helped tremendously.
The reason is actually a bug: I didn't initialise the variable in the constructor: https://github.com/RigsOfRods/rigs-of-rods/blob/d00267e150b59fe695c46084e2547160278511f8/source/main/resources/otc_fileformat/OTCFileformat.cpp#L192-L197 - There should also be `num_layers()` there 😊

**Comment by only-a-ptr** [comment]
Closing because it's broken. I already have another branch fixing this better.

**Pull request closed without merging**
