### PR TITLE
[Experimental] Updated AngelScript to version 2.31.0

### PR DESCRIPTION
**Pull request by ulteq**
```
/home/travis/build/RigsOfRods/rigs-of-rods/source/angelscript_addons/datetime/datetime.h:12:60: warning: missing terminating ' character
 #error Sorry, this requires C++11 which your compiler doesn't appear to support
```

### CODE REVIEW

**Comment by Hubbitus** [comment]
@ulteq, why you are close this? Does it work with new angelscript?

**Comment by ulteq** [comment]
I didn't have time to finish it. All I did so far was to make it compile.

**Comment by Hubbitus** [comment]
I did it compilable also in the path, but it segfault just on start unfortunately :(

**Comment by only-a-ptr** [comment]
Reopening because time has come: https://github.com/RigsOfRods/rigs-of-rods/issues/1372

**Comment by Speciesx** [comment]
@only-a-ptr 
> Note: This branch is too old to use directly, I'll use it as a reference and start my own, then I'll close this again.
Maybe this is also useful.
https://sourceforge.net/u/neorej16/rigsofrods/commit_browser

**Comment by only-a-ptr** [comment]
@Speciesx 

> https://sourceforge.net/u/neorej16/rigsofrods/commit_browser
> Maybe this is also useful.

Very interesting, it looks like those are the same commits as in this PR (or at least some of them), did you port it from there?

**Comment by Speciesx** [comment]
@only-a-ptr 

>  did you port it from there?
yes.

**Comment by only-a-ptr** [comment]
Closing as resolved by https://github.com/RigsOfRods/rigs-of-rods/pull/1373 :tada:

**Pull request closed without merging**
