### PR TITLE
Fixes for #2294

### PR DESCRIPTION
**Pull request by only-a-ptr**
Update: all done. Both fixes were tricky.
* 767 airliner: I had to postpone 'airbrake' processing until GfxActor is created, but then GfxActor couldn't initialize the way like before. My first solution was wrong, and it allowed me to discover an existing mistake in 'fixes'.
* the dumper: Medium-size remake of the classic dashboard logic. It was very old and completely global, which couldn't work anymore.

### CODE REVIEW

**Comment by tritonas00** [comment]
https://github.com/RigsOfRods/rigs-of-rods/pull/2341/commits/d1e398df7006495033c8d8cbbc0b0dc6381a901b no love
check pre spawned vehicles on nhelens or neoqueretaro

**Comment by only-a-ptr** [comment]
> @tritonas00 d1e398d no love

The idea was correct, but I accidentally inverted the "if there are no fixes" condition to "if there are fixes" 🙄

Now fixed 😆

**Comment by tritonas00** [comment]
Works fine on simple terrain but load a map with pre spawned vehicles (nhelens, neoqueretaro) then spawn the dumper
kk

**Comment by only-a-ptr** [comment]
The missing-dash glitch also happens on simple2.terrn when I spawn Agora and then RundbauerDumper.
ROR.log: `12:06:05:  == ActorSpawner: ERROR (Keyword props) An unknown exception has occured`

**Comment by only-a-ptr** [comment]
> Although all issues fixed now, we have a massive fps drop (try miniredmars)😕

I'm an idiot, sorry. Fixing...

**Comment by tritonas00** [comment]
Works great now!

**Comment by CuriousMike56** [comment]
I haven't tried this PR yet, but since we're on the topic of the renderdash, could the gear selection display be brought back? e.g. on the Gavril Omega:
0.4.7.0:
image
latest master:
image

**Comment by tritonas00** [comment]
hmm maybe because of
```
01:51:00: Parsing script needles.overlay
01:51:00: Error: ScriptCompiler - object allocation error in needles.overlay(37): Top level components must be containers, but 'TextArea' is an element
01:51:00: Error: ScriptCompiler - object allocation error in needles.overlay(55): Top level components must be containers, but 'TextArea' is an element
01:51:00: Error: ScriptCompiler - object allocation error in needles.overlay(71): Top level components must be containers, but 'TextArea' is an element
01:51:00: Error: ScriptCompiler - object allocation error in needles.overlay(87): Top level components must be containers, but 'TextArea' is an element
01:51:00: Error: ScriptCompiler - object allocation error in needles.overlay(103): Top level components must be containers, but 'TextArea' is an element
01:51:00: Error: ScriptCompiler - object allocation error in needles.overlay(119): Top level components must be containers, but 'TextArea' is an element
```

**Comment by only-a-ptr** [comment]
I created https://github.com/RigsOfRods/rigs-of-rods/issues/2343 because that won't be a quick fix, the log warnings above are not related IMO.

**Pull request merged**
