### PR TITLE
[Codechange] Suppress useless warnings in release mode

### PR DESCRIPTION
**Pull request by ulteq**
**Edit:** Also adds `-fno-omit-frame-pointer` to RelWithDebInfo.

### CODE REVIEW

**Comment by Hiradur** [comment]
I think `-fno-omit-frame-pointer` should stay in RelWithDebInfo for debugging purposes. It's probably included in most distributions' default `CMAKE_CXX_FLAGS` anyway.

**Comment by ulteq** [comment]
This PR adds `-fno-omit-frame-pointer` to RelWithDebInfo.

**Comment by Hiradur** [comment]
oops, I read the diff the other way around :blush:

**Comment by ulteq** [comment]
> Probably because your PR message is misleading

:blush: I changed it.

**Pull request merged**
