### PR TITLE
Restoring input mapping in RoRConfig

### PR DESCRIPTION
**Pull request by only-a-ptr**
I'm working on it.

ror-rorconfig-bindings2017

### CODE REVIEW

**Comment by Michael10055** [comment]
Clicking "end test" on the "Test" screen crashes RoRConfig.

**Comment by only-a-ptr** [comment]
@Michael10055 There's multiple crash scenarios at the moment. I tried to just restore the old code with minimum edits, but it's not working out. I'm currently refactoring RoRConfig in a different branch: https://github.com/RigsOfRods/rigs-of-rods/pull/1281

**Comment by only-a-ptr** [comment]
I rebased it atop the cleansed upstream codebase.
Status: Builds, but key binding doesn't work - the dialog doesn't react to key presses.

**Comment by tritonas00** [comment]
> Status: Builds

http://pastebin.com/xvtZ1Ttk :blush:

**Comment by only-a-ptr** [comment]
Ehh, I need to get a Linux build machine, stupid MSVC automatically workarounds a lot of string handling errors.

@tritonas00 Linux question: Is there a way to know what version of wxWidgets devel-package is the default one for various distributions? I'd like to know whether I still need to support pre-2.8 versions of wxWidgets. And I'm lazy to create a lot of VirtualBox machines for various distros just to find out 😄

**Comment by tritonas00** [comment]
@only-a-ptr i think anything after 2.8 is ok

**Comment by tritonas00** [comment]
Yep, with wxgtk 3.0 it builds fine. Still those -Wwrite-strings warnings with .xpm files though...

**Comment by only-a-ptr** [comment]
Closing this because code got outdated - RoRConfig received other modifications in the meantime.
Also, RoR is ready for implementing controls config directly in the in-game Settings panel.

**Pull request closed without merging**
