### PR TITLE
:wrench: Made content folder building optional

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**

### CODE REVIEW

**Comment by tritonas00** [comment]
Eh why? :laughing:

**Comment by AnotherFoxGuy** [comment]
> Eh why?

Because I use clion, and every time you switch configuration RoR rebuilds the cache
Also for every build you have installed the content folder gets duplicated, so I ended up with 6 simple terrains in the terrain selector

**Comment by AnotherFoxGuy** [comment]
> Still i would suggest ON by default, and you can use OFF when you have multiple configurations, we are the minority having multiple configurations

Yea, that is true
I've updated the PR to have it on by default

**Comment by tritonas00** [comment]
Works fine now :+1:

**Pull request merged**
