### PR TITLE
Fixed resource name conflicts between mods

### LINKED ISSUE #2280: T813 Material/texture issues
- Spawn [Tatra T813 Dakar](https://forum.rigsofrods.org/resources/tatra-t813-dakar.145/)
- Then spawn this after: [Tatra_T813_Kolos.zip](https://github.com/RigsOfRods/rigs-of-rods/files/2877264/Tatra_T813_Kolos.zip)
screenshot_2019-02-18_12-01-01_1
It's mainly the pink texture that's the issue.

### PR DESCRIPTION
**Pull request by only-a-ptr**
Fixes #2280 

Turns out we don't need OGRE's STRICT mode, just one extra flag for resource groups (and no bugs on our end).

### CODE REVIEW

**Comment by ulteq** [comment]
Sounds too good to be true. I'll take a look at it later.

**Comment by ulteq** [comment]
Works great!

**Comment by AnotherFoxGuy** [comment]
meshwheels seems to be broken
https://rigsofrods.cf/vehicle-creation/fileformat-truck/#meshwheels

screenshot_2019-02-24_11-00-21_1

Mod link: http://archives.rigsofrods.net/repo/files/repofiles-4th-batch/Panther.zip

**Comment by AnotherFoxGuy** [comment]
Also wings
screenshot_2019-02-24_11-12-45_1

**Comment by tritonas00** [comment]
same
mm

**Comment by only-a-ptr** [comment]
> and no bugs on our end

What I had in mind was "There must be no bugs on our end", not that there are no more (there indeed are).

Anyway, I think it's ready... even if we observe some glitches later, I'm sure they'll be fixed just as easy as those above.

**Comment by tritonas00** [comment]
will try asap

**Comment by tritonas00** [comment]
hud in pre spawned daf trucks on small island seems to be missing:

before
bef
after
aft

**Comment by tritonas00** [comment]
train valley
kk

**Comment by tritonas00** [comment]
Looks good except everytime i try to load Train Valley i get
```
FATAL ERROR: An internal error occured in Rigs of Rods.

Technical details below: 

FileNotFoundException: File not in archive '/home/babis/.rigsofrods/mods/DemagZKKE.zip' in open at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreZip.cpp (line 265)
```
It happened that before also but when you changed some terrains, now happens everytime.

**Comment by only-a-ptr** [comment]
@tritonas00 DemagZKKE.zip contains file `!!! Demag ZKKE Manual.pdf` which explains everything.

I'm getting all bumpers white for a change
obrazek

**Comment by tritonas00** [comment]
You are right.

I still get white wheels also, not only bumpers...

**Comment by only-a-ptr** [comment]
I don't get it - the bumper material `eu_coupling` is defined everywhere as a managedmaterial, so if anything, they should be bright pink and not white. I'll figure it out tomorrow...

**Comment by only-a-ptr** [comment]
I finally reproduced it... tricky, only happens when certain mods are preloaded
obrazek

**Comment by tritonas00** [comment]
try this http://www.austingratzer.com/rigs/downloads.php?do=file&id=192&act=down&actionhash=guest

**Comment by only-a-ptr** [comment]
Typical... 3 days of bug hunting, 3 seconds of fixing: https://github.com/RigsOfRods/rigs-of-rods/pull/2294/commits/9b8b93025ca35742a840e6881d6ed88453f9de35

**Pull request merged**
