### PR TITLE
New "T-Screen" (vehicle info side-panel)

### PR DESCRIPTION
**Pull request by ohlidalp**
I've merged the fragmented vehicle info windows and settings into one:
* The vehicle stats side-panel (hotkey T)
* The vehicle description and commands window (hotkey Ctrl+T)
* The on-mouse-hover vehicle buttons side panel
* The diagnostic view options from TopMenubar/Tools

**How it behaves now:**
* if you move the mouse to the left, and `ui_show_vehicle_buttons=true` (default), then the T-pane will show up translucent with the 'Basics' tab open by default but remember which tab you selected.
* if you press **`T`**, the T-panel will show opaque and open the 'Stats' tab
* if you press **`Cltr+T`**, the T-panel will show opaque and open the 'Commands' tab, showing the `helptex` texture and commands with descriptions and key combos and an unique in-scene highlight system (both the controls UI and the associated command beams on the vehicle are highlighted bright yellow).
* The T-panel (both opaque and translucent) has an extra tab 'Diag' which contains skeletonview toggles.

The basics view (on mouse hover):
obrazek

Commands view (Hotkey Ctrl+T) - with a highlight:
obrazek

The diagnostic options:
obrazek

### CODE REVIEW

**Comment by ohlidalp** [comment]
Note to self: make the panel narrower for small screens: https://discord.com/channels/136544456244461568/189904947649708032/1263347906501677078
obrazek

**Comment by ohlidalp** [comment]
To accomodate 1024x768, I've narrowed the T-panel and moved it a tad up (I had to shrink down the FPS panel, it now shows Batch count and Tri count on top).
obrazek

**Comment by woagXD** [comment]
looks pretty clean, hope it gets into the game soon!

**Comment by CuriousMike56** [comment]
Commands don't work at all, neither function keys or clicking the menu buttons. 

FPS counter has issues with higher framerates:
RoR_2024-08-19_11-23-11

**Comment by CuriousMike56** [comment]
- Menu width doesn't accommodate longer command names:
RoR_2024-09-22_11-03-38
- Category text on the hover menu should be grey like above instead of black:
RoR_2024-09-22_11-15-27

**Comment by ohlidalp** [comment]
The only way to accomodate the long descriptions without breaking low-res again was to ditch the columns, and automatically move keys to next line if they don't fit (the highlight adjusts automagically). I've also shortened the default label from "unknown function" to "\~unlabeled\~".
obrazek

**Comment by CuriousMike56** [comment]
- Category titles should be hidden if the current actor doesn't feature it (Engine, Traction, Loading etc)
RoR_2024-09-22_21-30-40

-It's possible to drag the column with the mouse: 

https://github.com/user-attachments/assets/a1cba5bb-0324-448a-8883-8d21c6a275d0

Snaps back to its original position, funny though

**Comment by ohlidalp** [comment]
I swear UIs are the worst time hog. So many details to tweak.

Removing the empty sections from Basic tab will be a bit laborous (to factor out visibility check logic from the draw funcs).

The strange column resizing is an imGUI quirk, I've already forced static column width but this remains, there's no option to disable it without killing the tabs and buttons. I guess I'll just ditch the columns as I did with the Commands tab.

**Comment by ohlidalp** [comment]
It now only displays useful categories; also I ditched the columns and right-aligned the keybuttons, like in Commands tab.

obrazek

**Comment by ohlidalp** [comment]
Discord feedback: https://discord.com/channels/136544456244461568/189904947649708032/1288325355303731252

I crammed the lines so that the panel doesn't leak out 1366*768 window, and aligned the values to the right with automatic split to 2 lines when the value is too long (like Current speed: on the screenshot)

obrazek

Note the 0.0 engine outputs aren't a bug, I used mousegrab to attain the velocity.

**Review by CuriousMike56 — APPROVED** [review]

**Pull request merged**
