### PR TITLE
Settings UI now uses actual tabs

### PR DESCRIPTION
**Pull request by only-a-ptr**
image

"Update cache" button moved under "General".
Separated "Simulation settings" from "General" to it's own tab "Gameplay".

### CODE REVIEW

**Comment by tritonas00** [comment]
Nice. Is it possible for the tabs to not scroll with the rest of the body?

**Comment by only-a-ptr** [comment]
> Nice. Is it possible for the tabs to not scroll with the rest of the body?

Yes, I'll change it.

> ... Render System settings to checkboxes instead of dropdowns?

It works by looping over OGRE's settings list and possible values. I'd keep it as is for simplicity.

**Comment by only-a-ptr** [comment]
image

**Review by WillyB1337 — APPROVED** [review]
Nice change!

**Review by Zentro — APPROVED** [review]

**Review by tritonas00 — APPROVED** [review]

**Comment by WillyB1337** [comment]
I just noticed you can scroll the tabs.
05-mai-21-21h01,25

**Pull request merged**
