### PR TITLE
Remade race text overlay with ImGui

### PR DESCRIPTION
**Pull request by tritonas00**
Also lap times color varies depending the time difference, like before.

kk
kkk
kkkk

### CODE REVIEW

**Comment by only-a-ptr** [comment]
I integrated it with top menubar. When you hover mouse over the top it shows like this:
obrazek

**Review by only-a-ptr — APPROVED** [review]
Nice work

**Comment by tritonas00** [comment]
TODO: bring back lap times

**Review by only-a-ptr — APPROVED** [review]
very good

**Pull request merged**
