### PR TITLE
🐛 Fixed building without Conan

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**

### CODE REVIEW

**Comment by tritonas00** [comment]
still no caleum found
>  -- The following OPTIONAL packages have been found:
> * wxWidgets
> * OpenAL
> * SocketW
> * AngelScript
> * CURL
> * PagedGeometry
> * Git
> * PkgConfig

**Comment by AnotherFoxGuy** [comment]
I forgot ```find_package(Caelum)```, should be fixed now

**Comment by tritonas00** [comment]
Now its fine.

Finally, thank you and please don't nuke the build environment again.

**Comment by ulteq** [comment]
Works perfectly fine. Thanks a lot!

**Pull request merged**
