### PR TITLE
[Bugfix] Recovered the old turbo mode

### LINKED ISSUE #392: Too much smoke emitted for default smoke line
The default smoke line emits to much smoke to constantly blocking your view.

screenshot_1

### LINKED ISSUE #428: No turbo sounds or gauges
http://www.rigsofrods.com/threads/120168-No-turbo-sounds-or-gauges?p=1386196#post1386196

### PR DESCRIPTION
**Pull request by ulteq**
Fixes #428

Fixes #392 

@Speciesx, @negativeice, needs to be tested.

### CODE REVIEW

**Comment by disloyalpick** [comment]
What do you mean by "original turbo mode"

**Comment by ulteq** [comment]
Engine type 't': http://www.rigsofrods.com/wiki/pages/Truck_Description_File/#Engoption

**Comment by Speciesx** [comment]
@ulteq 
The old turbo works again.

**Comment by ulteq** [comment]
@Speciesx Awesome, thanks for the quick response!

**Comment by ulteq** [comment]
@disloyalpick I've renamed it into 'old turbo mode'.

**Comment by Hiradur** [comment]
:+1:

**Comment by only-a-ptr** [comment]
:+1:

**Pull request merged**
