### PR TITLE
removed boost from cmake files

### PR DESCRIPTION
**Pull request by tritonas00**
needs #846 #847 #849 and probably https://github.com/RigsOfRods/ogre-caelum/pull/1 first

### CODE REVIEW

**Comment by Speciesx** [comment]
You should also remove OgreProperty.

> If you don't use boost with ogre (I usually can't be bothered) then cmake won't generate a project for the property component. Everything runs fine without it.
http://www.ogre3d.org/forums/viewtopic.php?p=453263#p453263


https://github.com/RigsOfRods/rigs-of-rods/blob/master/cmake/DependenciesConfig.cmake#L85
https://github.com/RigsOfRods/rigs-of-rods/blob/master/cmake/DependenciesConfig.cmake#L92
https://github.com/RigsOfRods/rigs-of-rods/blob/master/cmake/DependenciesConfig.cmake#L101
https://github.com/RigsOfRods/rigs-of-rods/blob/master/cmake/DependenciesConfig.cmake#L111

**Comment by tritonas00** [comment]
Nice. What about 

https://github.com/RigsOfRods/rigs-of-rods/blob/master/cmake/DependenciesConfig.cmake#L91
https://github.com/RigsOfRods/rigs-of-rods/blob/master/cmake/DependenciesConfig.cmake#L109

?

**Comment by Speciesx** [comment]
these too.

**Comment by ulteq** [comment]
What about these:
- https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/configurator/CMakeLists.txt#L40-L41
- https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/configurator/CMakeLists.txt#L76-L77
- https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/configurator/CMakeLists.txt#L101

**Comment by tritonas00** [comment]
Done.

**Pull request merged**
