### PR TITLE
Created vehicle tuning GUI using new .addonpart mod type

### PR DESCRIPTION
**Pull request by ohlidalp**
UPDATE 01/2024: For most up-to-date info, please see the [Wrapping Up](https://github.com/RigsOfRods/rigs-of-rods/pull/3096#issuecomment-1881131907) post below.

The master branch has almost everything you need to create a truck editor script. Almost. This PR will fill the blanks. EDIT: After Discord debate, I steered this PR towards a vehicle configuration/tuning system.

So far I've done the most important bit: I've made `GenericDocument` editable, as originally promised. The `GenericDocReaderClass` was renamed to `GenericDocContextClass` and there are new functions:
```
    bool insertToken(int offset = 0); //!< Inserts `TokenType::NONE`; @return false if offset is beyond EOF
    bool eraseToken(int offset = 0); //!< @return false if offset is beyond EOF

    bool setTokString(int offset, const string&in str);
    bool setTokFloat(int offset, float val);
    bool setTokBool(int offset, bool val);
    bool setTokKeyword(int offset, const string&in str);
    bool setTokComment(int offset, const string&in str);
    bool setTokLineBreak(int offset);
```
To showcase it, I created an example script - you can run it by opening ingame console and typing `loadscript example_GenericDoc_editor.as`. It doesn't edit yet, just lets you select tokens with mouse and prints details. Green text is hovered, red text has focus.
obrazek

### CODE REVIEW

**Comment by CuriousMike56** [comment]
Nice! Hopefully we'll be able to make temporary edits and apply them to the vehicle. Would be fun to mess with, say, engine tunes in real time.

**Comment by ohlidalp** [comment]
@CuriousMike56 💌 I'd like that too, here's facts:
* Ideally game would spawn actors directly from a `GenericDocument`, technically it makes sense but it absolutely requires #2922 (the parser revert) to be completed first. So not doable now.
* I could do the same I did with the script editor - add a `buffer` param to `ActorSpawnRequest`, making game spawn from memory string rather than file on disk. However, spawning is firmly tied with modcache which makes sense because you want to also load the zip/directory where the file lives. I don't want to hack this, I'll instead explore ad-hoc updating modcache.
* Right now you must be in menu to update modcache, and it's synchronous (loading dialog). The single (stupid!) reason for this is that `CacheEntry`-ies are kept in a plan `std::vector<CacheEntry>` and actors have raw pointers to them (updating std::vector breaks raw pointers). If a cache entry was a `RefCountingObject<>`, we could simply flag them 'deleted' and insert new ones on-the-go, even in simulation. RepoUI could be used anytime. Minimum dev work, fantastic implications. I'll go this route.
* Saving the modified actor would best be done directly to 'mods/' directory, possibly to some 'mods/actor_projects' subdir. I'm not going to give users the raw `CreateDirectory()` function, instead I'd do something lie `MSG_EDI_CREATE_PROJECT_REQUESTED` which creates a subdir and possibly pre-populates it with files from a ZIP. And inserts it to modcache while at that. PS: maybe I'll add a whole new 'Rigs of Rods\projects' dir while at it, since async modcache can easily handle it.

**Comment by ohlidalp** [comment]
You can now do this in AngelScript:
```
       // Fetch the current actor cache entry
         CacheEntryClass@ src_entry = cache.findEntryByFilename(LOADER_TYPE_ALLBEAM, /*partial:*/false, actor.getTruckFileName());

       // request project to be created from that cache entry
       string proj_name = "project1";
       game.pushMessage(MSG_EDI_CREATE_PROJECT_REQUESTED, {
           {'name', proj_name},
           {'source_entry', src_entry}
       });
```
The game will create a subdirectory in 'My Games\Rigs of Rods\project' and copy all files from the existing mod ZIP. It will also rename the truck file for you and publish it in modcache. You can look it up under new category "Projects" (catetgory ID 8990). As you can see on the screenshot, the material is glitched but otherwise the project spawns as fully functional actor.
obrazek

The example script does all this. I guess I'm done with this branch for now, if anybody is interested in expanding this, everything can be deduced from docs, demo_script.as or builtin examples.

**Comment by ohlidalp** [comment]
Some interesting thoughts from Discord:
* In-game car configurator using mod types ".addonpart" (truck-like) and ".tuneup" (skin-like): https://discord.com/channels/136544456244461568/189904947649708032/1165055858078646353
* Monster trucks need better tire model: https://discord.com/channels/136544456244461568/409871728597139457/1166348290548310088

**Comment by ohlidalp** [comment]
**STATUS: ALPHA!** Glitchy, only adding a part works, the remove-button is dummy.
addonpartsPrototype

This adds a new mod type "addonpart" (file pattern *.addonpart) which works as a partial truck file - when selected, it adds additional elements to it. Currently supported features are: managedmaterials, props, flexbodies. The point is to automate what users had to do manually before: https://docs.rigsofrods.org/tools-tutorials/addons/

The addon parts receive all usual treatment from modcache: they can have preview images, name + description are always displayed, they can be searched for, the MainSelectorUI can be opened in mode 'LT_AddonPart' to show only addon parts. In addition, the search can be filtered by a vehicle GUID, much like with SkinZips. This is an example addonpart (port of https://forum.rigsofrods.org/resources/heavy-bumper-for-the-chevy-k3500.461/):

```
addonpart_name "Heavy Bumper for the Chevy K3500 (Prop, Black)"
addonpart_description "For use with GMT400 88-98 Chevy Truck Pack"

;addonpart_guid <guid>  ~ multiple GUIDs can be specified
addonpart_guid 057b21c8-cb54-496d-88ce-4855a8d6d43d
; * 1990 Chevy 454ss,  * 1990 Chevy k3500    * 1990 Chevy K3500HD
addonpart_guid 6a53ad83-255d-4d5e-bf14-ca0714e5228d
; * 1990 Chevy k2500 Blazer, -SAS, -Suburban

managedmaterials
    CHeavyBumper		mesh_standard		HeavyBumper.dds		HeavyBumper_s.dds

props
    39, 62, 34,    0.50,    0.32,     -0.5,   0,    180,    180, CHeavyBumper.mesh
```

There's a new menu in TopMenubarUI: "Tuning". It lists already installed addonparts and contains [add parts] button which opens MainSelectorUI in 'LT_AddonPart' mode, with GUID filtering for the current vehicle.

To remember what addonparts user selected, an additional mod type was added: "tuneup" (file pattern *.tuneup) - this works like ".skin for addonparts" and has intentionally similar syntax. There are 2 power tools:
* "use_addonpart <filename>" to install an addonpart on the vehicle (multiple can be used!)
* "remove_prop <meshname>" to strip an existing prop from the vehicle.

Note: An option to replace prop was intentionally not implemented because that would be a duplicate feature with addonparts. It's up to user to remove props if and only if they don't want them together with new parts.

When user uses addonpart with a vehicle for the first time, the game creates a .tuneup file for it  in {Documents\My Games\Rigs of Rods\projects\}. When spawning the vehicle next time, the .tuneup is loaded automatically. In the future the menu will be able to save custom tuneups. Here's an example:

```
Tuned 1990 Chevy 454ss
{
      use_addonpart = CHeavyBumperBlackProp.addonpart
	preview =
	description =
	author_name = ohlidalp
	author_id = -1
	category_id = 8100
	guid = 057b21c8-cb54-496d-88ce-4855a8d6d43d
}
```

Under the hood, applying the addonparts to the vehicle works entirely in system memory, no truck files are modified or written.
* "use_addonpart" works by literally introducing a fake 'section/end_section' to the truck file parsed in memory - see `class RigDef::File::Module` and function `ActorSpawner::ConfigureAddonParts()` for details.
* "remove_prop" works as last-minute check in `ActorSpawner::ProcessProp()`, skipping props which are blacklisted.

**Comment by ohlidalp** [comment]
I added GUI for 'remove_prop' directives in .tuneup:
obrazek

The '.tuneup' on display:
```
// This is a '.tuneup' mod - it's similar to '.skin' mod but deals with '.addonpart' mods.
// See https://github.com/RigsOfRods/rigs-of-rods/pull/3096#issuecomment-1783976601

Tuned 1990 Chevy 454ss
{
	preview = ABCD
	description = EFGT
	author_name = 
	author_id = -1
	category_id = 8100
	guid = 057b21c8-cb54-496d-88ce-4855a8d6d43d

	remove_prop = 454ss_Mirrors.mesh
	remove_prop = Kodiak_Windows.mesh
}
```

**Comment by ohlidalp** [comment]
I made the rusted bumper work, which means texture lookup works for .addonpart mods.

Prop-addons are now fully functional; Flexbody addons report "node not found" for all nodes at the moment.

attached is a test package I created from https://forum.rigsofrods.org/resources/heavy-bumper-for-the-chevy-k3500.461/
[addonpart_CHeavyBumper.zip](https://github.com/RigsOfRods/rigs-of-rods/files/13217390/addonpart_CHeavyBumper.zip)

obrazek

**Comment by ohlidalp** [comment]
I added the concept of 'unwanted props/flexbodies' to addons and 'protected props/flexbodies' to tuneups.

The .addonpart file can now specify "unwanted" props or flexbodies, to simulate swapping of parts. Under the hood, this works by adding the mesh names to "remove" lists, same as if user disabled them from top menu. Example addonpart:

```
  ; Add the stock bumpers to 'tuneup.removed_flexbodies' unless user added it to 'tuneup.protected_flexbodies' first.
  addonpart_unwanted_flexbody "K3500_FBump.mesh"
  addonpart_unwanted_flexbody "454ss_FBump.mesh"```
The .tuneup file now contains lists of "protected" props and flexbodies which cannot be removed by the addonpart and remain "removed" or not as the user wishes. This lets user force default meshes to be kept or addonpart meshes to not be added (may be useful if the addonpart specifies multiple meshes). Example of protected entry in .tuneup file:

```
	protected_flexbody = 454ss_FBump.mesh
	protected_flexbody = K3500_FBump.mesh
```

Meshes can be marked 'protected' via new widget in top menubar:
![obrazek](https://github.com/RigsOfRods/rigs-of-rods/assets/491088/83291fca-415b-4f4f-ad1b-71da1b104ae7)

**Comment by ohlidalp** [comment]
By popular demand, I added 'tweaks' in the addonpart system. These directives let you modify existing elements.

There are 2 new directives in the addonpart format:
* `addonpart_tweak_node <nodenum> <posX> <posY> <posZ>`
* `addonpart_tweak_wheel <wheel ID> <rim mesh> <tire radius> <rim radius>`

My test mod: 
[agoras_monstrwheels.addonpart.zip](https://github.com/RigsOfRods/rigs-of-rods/files/13267420/agoras_monstrwheels.addonpart.zip)

image

**Comment by ohlidalp** [comment]
To be fixed: https://discord.com/channels/136544456244461568/189904947649708032/1171163431018184744

**Comment by ohlidalp** [comment]
I fixed the last big glitch and renamed the PR to advertise the new main feature. Originally the goal was an example truck editing script, which is present, but the main focus became an addon part system with UI, which doesn't use scripting.

# Summary of new features
* New directory under 'Documents\My Games\Rigs of Rods': 'projects'. It's processed by modcache (like 'mods' dir), so putting ZIPs here will work, but it's intended to host directories with unpacked WIP mods.
* New mod type ".addonpart" with syntax similar to .truck. It's processed by modcache like other mods, including mini-image. It can be placed in any ZIP. See above posts for examples.
* New mod type ".tuneup" with syntax intentionally similar to .skin and very similar functionality. It allows you to remove and tweak certain elements. The main purpose is to let player save their tuned configurations, and also remember the last working state after game exits. Again, see above for examples.
* New menu in TopMenubar UI, 'Tuning', which automatically displays the available addon parts and existing props/flexbodies, with checkboxes allowing player to apply/remove them. The game remembers the changes user made across sessions (as a 'working tuneup'), to reset it, press and hold the big 'Reset' button. When loading a previously saved tuneup, it overwrites the working one, so further changes to it do not modify the saved tuneup - the player must save again.

# Summary of scripting extensions:
* New :envelope: `MSG_EDI_CREATE_PROJECT_REQUESTED` which takes an existing mod as parameter. It automatically unpacks it's files to new directory under 'projects', renames the mod file and sets it's category ID to 'Projects' so that it doesn't show among other mods in the selector - the player must select "Projects" category.
* New include script 'gridviewer_utils.as' (_utils is my convention for include scripts) - it's a generic zooming/scrolling 2D viewer which lets you draw anything into it using DearIMGUI's ImDrawList API.
* New script 'example_RigEditor.as' which showcases the GridViewer component and makes use of the new CREATE_PROJECT message to edit existing mods.
* New :envelope: `MSG_EDI_MODIFY_PROJECT_REQUESTED` which is internally used by the TopMenubar 'Tuning' menu to make changes to the working .tuneup file, which is itself placed in the projects dir.

**Comment by ohlidalp** [comment]
To be fixed: https://discord.com/channels/136544456244461568/189904947649708032/1173763986341249084

**Comment by ohlidalp** [comment]
The design agreed on Discord https://discord.com/channels/136544456244461568/189904947649708032/1174499523901534218
1. player spawns a clean car. UI shows each wheel with small "L/R" radio button and an "protected" checkbox on the right, like other things. The radiobutton is set to whatever's in the truckfile.
2. player installs an addonpart with the generic wheels. tweak_wheel records are inserted to the .tuneup file. Radiobutton updates to whatever the addonpart did.
3. player sees the rims are wrong and adjusts the radiobuttons. Internally this means updating the tweak_wheel entries that came from addonpart, which is possible as long as the "protected" flag is set for the wheels. This however also means that when user uninstalls the addonpart, the wheels will stay on. Alternatively I can add `ui_fixups_*` concept to the .tuneup format and scrap the whole "protected" flag system... I'll give it some more thought.

**Comment by ohlidalp** [comment]
**Tuneup format + UI change**
All vehicle elements in the Tuning menu now show with numbers. They represent the order of definition in the truckfile, starting with 0. The removed_/protected_ arrays in the .tuneup file now use these numbers (instead of mesh names), to cover cases where the same mesh is used multiple times.

**New directives:**
```
addonpart_tweak_prop <prop ID> <offsetX> <offsetY> <offsetZ> <rotX> <rotY> <rotZ> <media1> <media2>
addonpart_tweak_flexbody <flexbody ID> <offsetX> <offsetY> <offsetZ> <rotX> <rotY> <rotZ> <meshName>
```

Example:
```
; 'addonpart_tweak_flexbody <flexbody ID> <offsetX> <offsetY> <offsetZ> <rotX> <rotY> <rotZ> <media1> <media2(optional)>'
addonpart_tweak_flexbody    0,             39, 62, 34,                  0.50,    0.32,  -0.5,          CHeavyBumper.mesh
```
[addonpart_SwapTest2_CHeavyBumper.zip](https://github.com/RigsOfRods/rigs-of-rods/files/13468631/addonpart_SwapTest2_CHeavyBumper.zip)

obrazek

**Comment by ohlidalp** [comment]
**Added ability to flip rim meshes via UI**

obrazek

**Comment by ohlidalp** [comment]
## Things to fix in this PR:
* Wheel "protected" state blocks addonparts - actually by design but inconvenient, I'll change it: https://discord.com/channels/136544456244461568/189904947649708032/1180864687399768136
* Prop checkboxes bug: https://discord.com/channels/136544456244461568/189904947649708032/1180865207535403018
* Various: https://discord.com/channels/136544456244461568/189904947649708032/1180873156819439736

## Things for next time:
* Add the possibility to match addonparts by filename: https://discord.com/channels/136544456244461568/189904947649708032/1180872011925434388
* Resolve conflicting managed materials: https://discord.com/channels/136544456244461568/189904947649708032/1181300830519967804 - I think this won't work either way. In the optimal case, there would be one OGRE resource group per spawned actor (containing actor+skin+addonparts ZIPs), which implies that managedmaterial names are unique. Currently actors share a resource group with the actor ZIP so materials must be renamed to "whatever@Actor##" and distributed by custom mesh loading logic, which is not optimal.
* replace the `addonpart_guid <GUID>` directive with `addonpart_target <type: "guid/categoryid/filename/global"> <arg>`

**Comment by ohlidalp** [comment]
## New .tuneup feature + updated UI

All the UI overrides are now separate from any addonpart changes (tweaks or 'unwanted_*'). The 'protected' checkbox on the right just blocks addonpart changes, but isn't necessary for the UI overrides anymore. When you make an UI override, the respective widget will be outlined orange and a 'reset' button will be drawn. Internally, the UI overrides are called "force_*something*".

CAUTION: Top menubar Tuning menu is only corrected for flexbodies, not props yet!

obrazek

**Comment by ohlidalp** [comment]
# Wrapping up

Almost all bugs are fixed, only minor glitches may be left. Below is a draft documentation.

## The .addonpart mod type

There's a new mod type "Addon part" (file extension .addonpart) which automates the process of customizing a vehicle, previously requiring to manually edit files as you can read in https://docs.rigsofrods.org/tools-tutorials/addons/. The addonpart file format is similar to truck file format with added `addonpart_*` directives. In game, player can install addonparts using new menu "Tuning" in top menu bar.

### Organizational info
* `addonpart_name` - display name, shown in "Tuning" menu.
* `addonpart_description` - text displayed in SelectorUI - presently the Tuning menu doesn't let you invoke Selector for addonparts, but it's still possible via scripting and will likely be used in the future.
* `addonpart_guid` - GUID of the target vehicle family, see https://docs.rigsofrods.org/vehicle-creation/fileformat-truck/#guid - this GUID is usually not unique to one vehicle but groups structurally similar vehicles which use the same skins.

Note: Preview images for selector UI (aka mini-images) are also supported.

### Tweaking existing elements

'Tweaking' is the process of modifying existing elements. You use a directive `addonpart_tweak_ABC` followed by the target element's position in the truck file, numbered from 0. This is akin to how `materialflarebindings` work. 

Parameters in `[ ]` are optional, leaving them out results in keeping original values. To omit an argument in between, use `""` for string args or `-1` for numeric args. This doesn't apply to positions and offsets, those are always required.

The 'media' can be meshes/materials (more types may come) depending on what the targeted element accepts.

* `addonpart_tweak_node <nodenum> <posX> <posY> <posZ>` - tweaks `nodes`, all params are required.
* `addonpart_tweak_wheel <wheel ID> <media1> [<media2> <side flag> <tire radius> <rim radius>]` - tweaks `wheels`, `wheels2`, `meshwheels`, `meshwheels2`, `flexbodywheels`. Media1+2 is face+band material in `wheels[2]` and rim mesh+tire material otherwise.
* `addonpart_tweak_prop <prop ID> <offsetX> <offsetY> <offsetZ> <rotX> <rotY> <rotZ> <media1> <media2>` Tweaks `props`, Media1 = prop mesh; Media2: Steering wheel mesh or beacon flare material.
* `addonpart_tweak_flexbody <flexbody ID> <offsetX> <offsetY> <offsetZ> <rotX> <rotY> <rotZ> <meshName>` - Tweaks `flexbodies`, but **does NOT support the `forset` line**. If you need to change the node set, you need to completely replace the flexbody, see below.

Internally, the edits are applied in memory at last moment during spawn, files in mod cache are not affected. 

### Adding new elements

Just use the same syntax as in truck file, anywhere in the .addonpart file. Currently supported elements are `props`, `flexbodies`, `managedmaterials`.

### Supressing existing elements

These accept a single parameter -  the target element's position in the truck file, numbered from 0.

* `addonpart_unwanted_prop <prop ID>`
* `addonpart_unwanted_flexbody <flexbody ID>`

## The .tuneup mod type

This one is intentionally similar to .skin; it has the same structure and serves very similar purpose - applying addonparts and other user changes to a vehicle on spawn. The internal processing is also very similar. The game creates and edits these files automatically as the player uses the Tuning menu. Files are saved to `Documents\My Games\Rigs of Rods\projects` directory which is a newly introduced directory monitored by modcache (like 'mods') but intended for modding and tuning.

There are 2 categories of tuneups:
* 'Auto' tuneups (category ID 8100) - There is always 1 for every installed vehicle, the Tuning menu creates it automatically. Any change done on the UI is immediatelly saved to this file. The file persists across sessions.
* 'User' tuneups (category ID 8101) - Any number can be saved for a vehicle. Only created or modified on user request. When saving, the 'auto' tuneup gets copied to the save; when loading, the 'auto' tuneup gets overwritten by the save.

## The tuning menu

There's a new menu "Tuning" in the top menubar UI, which allows user to pick addonparts. Following paragraphs are a description of the UI, in top down order:

### "Enable tuning" checkbox

Toggles cvar `sim_tuning_enabled` (persisted in RoR.cfg)

### List of saved tuneups

Saved tuneups for current vehicle.  Only created or modified on user request. When saving, the 'auto' (working) tuneup gets copied to the save; when loading, the 'auto' (working) tuneup gets overwritten by the save.
 
### List of installed addonparts

Each comes with a [Reload] button to reload the file from disk if you're modding it.

### User overrides: props/flexbodies/wheels

**Number:** All vehicle elements in the Tuning menu now show with numbers. They represent the order of definition in the truckfile, starting with 0. The removed_/protected_ arrays in the .tuneup file use these numbers (instead of mesh names), to cover cases where the same mesh is used multiple times.

**Override checkbox:** All the UI overrides (removed flexbodies/flipped wheel rims) are separate from any addonpart changes (tweaks or `unwanted_*`). When you make an UI override, the respective widget will be outlined orange and a 'reset' button will be drawn.

**The 'protected' checkbox:** (on the right) - Just blocks addonpart changes, doesn't affect the UI overrides in any way. Translates to `protected_*` directives in the .tuneup file.

In the .tuneup file, the UI overrides are called "force_something", while parts removed via addonparts are called 'unwanted_something'.

# Updated addonparts to test

Mostly by @CuriousMike56 
* [DOWNLOAD: 3096_DBRim_MV4.zip](https://github.com/RigsOfRods/rigs-of-rods/files/13861912/3096_DBRim_MV4.zip)
* [DOWNLOAD: 3096_DesperadoWheel.zip](https://github.com/RigsOfRods/rigs-of-rods/files/13861914/3096_DesperadoWheel.zip)
* [DOWNLOAD: 3096_CHeavyBumper.zip](https://github.com/RigsOfRods/rigs-of-rods/files/13861916/3096_CHeavyBumper.zip)
* [DOWNLOAD: 3096_MV4_RollCage.zip](https://github.com/RigsOfRods/rigs-of-rods/files/13861920/3096_MV4_RollCage.zip)
* [DOWNLOAD: 3096_MV4S_negativeCamber.zip](https://github.com/RigsOfRods/rigs-of-rods/files/13861924/3096_MV4S_negativeCamber.zip)

**Comment by CuriousMike56** [comment]
✅ ✅

**Pull request merged**
