### PR TITLE
Compilation of Linux compilation fixes

### PR DESCRIPTION
**Pull request by Aperion**
This contains many fixes to get RoR compiling on linux and a small adjustment to CMake to print more information for debugging.

### CODE REVIEW

**Comment by Hiradur** [comment]
I don't want to take down your pull request, but if we merged my fixes instead we could easily merge these additional fixes:
https://github.com/Hiradur/rigsofrods-next-stable/commits/additionalfixes

**Comment by only-a-ptr** [comment]
Hi.
First, thanks for your efforts.
Apparently there's qite some overlap in your commits. My impression is that Hiradur's fixes are leaner and solve most of the issues. IMO the best way to merge would be to merge all of Hiradur first and then let

**Comment by only-a-ptr** [comment]
Oops, I pushed [close] button by accident, I'm writing from a smartphone touchscreen. Sorry for the confusion.
 
To finish my last post: Let's merge all commits by Hiradur first an then let's leave Aperion to fill any gaps.

**Comment by Hiradur** [comment]
I started a pull request with my changes, I'm open for further improvements.
I hope you don't take that as an offense Aperion.

**Comment by only-a-ptr** [comment]
I've just merged the other pull request by Hiradur, so I'm closing this one.

@Aperion: Thanks for your commits, I'll review them and port the missing bits later.

**Pull request closed without merging**
