### PR TITLE
Fixed Caelum segmentation fault

### LINKED ISSUE #550: Segmentation fault in Ogre::GpuProgramUsage::getParameters
Hello.
Just run new compiled c10f9ac.

```
#0  0x00007ffff742fb4e in Ogre::GpuProgramUsage::getParameters (this=0x0) at /usr/src/debug/ogre-1.9.0/OgreMain/src/OgreGpuProgramUsage.cpp:113
#1  0x00007ffff7428bf1 in Ogre::Pass::getFragmentProgramParameters (this=0x7fff9a5dafb8) at /usr/src/debug/ogre-1.9.0/OgreMain/src/OgrePass.cpp:1728
#2  0x00007ffff49b99ec in Caelum::Moon::Moon(Ogre::SceneManager*, Ogre::SceneNode*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Ogre::Degree) ()
   from /usr/lib64/OGRE/libCaelum.so
#3  0x00007ffff49a28ff in Caelum::CaelumSystem::autoConfigure(Caelum::CaelumSystem::CaelumComponent) () from /usr/lib64/OGRE/libCaelum.so
#4  0x00007ffff49a4020 in Caelum::CaelumSystem::CaelumSystem(Ogre::Root*, Ogre::SceneManager*, Caelum::CaelumSystem::CaelumComponent) () from /usr/lib64/OGRE/libCaelum.so
#5  0x00000000005e5e1a in SkyManager::SkyManager (this=0x2317d00) at /usr/src/debug/rigs-of-rods-c10f9acd5ccc6147a507ec2baed8f2e564d94bd0/source/main/gfx/SkyManager.cpp:44
#6  0x00000000005aab68 in TerrainManager::initSkySubSystem (this=this@entry=0x22eafd0)
    at /usr/src/debug/rigs-of-rods-c10f9acd5ccc6147a507ec2baed8f2e564d94bd0/source/main/utils/ZeroedMemoryAllocator.h:50
#7  0x00000000005ad20b in TerrainManager::initSubSystems (this=this@entry=0x22eafd0)
    at /usr/src/debug/rigs-of-rods-c10f9acd5ccc6147a507ec2baed8f2e564d94bd0/source/main/terrain/TerrainManager.cpp:281
#8  0x00000000005aedab in TerrainManager::loadTerrain (this=0x22eafd0, filename="simple2.terrn2")
    at /usr/src/debug/rigs-of-rods-c10f9acd5ccc6147a507ec2baed8f2e564d94bd0/source/main/terrain/TerrainManager.cpp:217
#9  0x000000000096e9b1 in RoR::MainThread::LoadTerrain (this=this@entry=0x7fffffffd100, a_terrain_file="simple2.terrn2")
    at /usr/src/debug/rigs-of-rods-c10f9acd5ccc6147a507ec2baed8f2e564d94bd0/source/main/main_sim/MainThread.cpp:1201
#10 0x0000000000970ef8 in RoR::MainThread::SetupGameplayLoop (this=this@entry=0x7fffffffd100, enable_network=enable_network@entry=false, preselected_map="")
    at /usr/src/debug/rigs-of-rods-c10f9acd5ccc6147a507ec2baed8f2e564d94bd0/source/main/main_sim/MainThread.cpp:838
#11 0x000000000097549b in RoR::MainThread::Go (this=this@entry=0x7fffffffd100) at /usr/src/debug/rigs-of-rods-c10f9acd5ccc6147a507ec2baed8f2e564d94bd0/source/main/main_sim/MainThread.cpp:550
#12 0x000000000097799a in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/rigs-of-rods-c10f9acd5ccc6147a507ec2baed8f2e564d94bd0/source/main/main_sim/main.cpp:324
```

Log of run: http://paste.fedoraproject.org/309028/52368701

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
Fixes #550

### CODE REVIEW

**Comment by only-a-ptr** [comment]
Very interesting... how does an extra `technique` cause a segfault? How did you find the cause? And does your change affect the HydraX water effect at all?

**Comment by AnotherFoxGuy** [comment]
The segmentation fault is actually caused by the OpenGL render unable to load the fragment program

```
10:54:13: Compiler error: object unsupported by render system in RoRSkies.os(30): Failed to create component "moon": OGRE EXCEPTION(-1:UnsupportedException): Can't load material "Caelum/PhaseMoon": Pass 0: Fragment program Caelum/PhaseMoonFP cannot be used - not supported.
 in Caelum at /home/anotherfoxguy/Documents/ogre-caelum/main/src/InternalUtilities.cpp (line 102)

```

**Comment by only-a-ptr** [comment]
@AnotherFoxGuy Thanks for info but I'm just more confused... how does your change affect that FP?

Also, please write these explanatory notes right into the commit description ... a commit titled "fixed segfault" containing just material script changes really says "There's something seriously broken around here!"

**Comment by AnotherFoxGuy** [comment]
Caelum tries to get some parameters by using ```material->getBestTechnique ()->getPass (0)->getFragmentProgramParameters ()``` 
But because the Default technique fails to load, the material only has one working technique (HydraxDepth).
So Caelum tries to get the fragment program parameters of a technique that doesn't have any fragment program and just crashes.

**Comment by only-a-ptr** [comment]
@AnotherFoxGuy Tricky! Thanks.

**Pull request closed without merging**
