### PR TITLE
Menu cleanups and improvements

### PR DESCRIPTION
**Pull request by tritonas00**
- Removed `GUI_GamePauseMenu(cpp/h)` and merged code in `GUI_GameMainMenu.cpp`
- Pressing Esc in multiplayer, only the menu is shown now, simulation continues
- Added "Cache updated" notice:
kk

### CODE REVIEW

**Comment by only-a-ptr** [comment]
Works great, just one detail: the "cache updated" notification only shows if cache is actually updated. If it's alredy up-to-date, nothing shows at all. I suggest adding "cache already up-to-date" variant of the notification for this case.

**Comment by tritonas00** [comment]
> notification only shows if cache is actually updated. If it's already up-to-date and user presses "update cache" button, nothing shows at all

this is not the case on linux, it is always shown when i hit the update cache button
i can reproduce the issue on windows, i moved the notice to LoadModCache, also the same

**Comment by only-a-ptr** [comment]
@tritonas00 I don't understand why linux behaves differently, but we definitely have a bug: CACHE_STATE_UNKNOWN and CACHE_NEEDS_UPDATE have the same value. Without this bug, the notification would always display after pressing the button.

**Comment by tritonas00** [comment]
Epic

kk

**Pull request merged**
