### PR TITLE
Fixed multiplayer kick handling

### PR DESCRIPTION
**Pull request by only-a-ptr**
@tritonas00 Thanks for bringing #2309 into my attention, I looked at it with fresh eyes and... 🤢

Status: on Win10 x64, with RoR & rorserver built as Debug/x64:
* Upon server kick, RoR returns to main menu and displays message from server.
* Reconnecting works cleanly
* Exiting game works cleanly

More work is needed, though: When server is abruptly terminated, RoR silently exits. Also `CheckConnectingState()` should not do destructive reading as it does now - there should be separate notification queue instead.

### CODE REVIEW

**Comment by tritonas00** [comment]
works great thanks!

you think it can handle this also? https://github.com/RigsOfRods/rigs-of-rods/issues/1279

**Comment by only-a-ptr** [comment]
I think #1279 is unaffected at the moment, but I'll definitely try fixing it as well.

**Comment by only-a-ptr** [comment]
I think it's perfect now. What I tried:
* Shut down/kill server while user is still in menu: a proper "server down, try later"(shutdown) / "fatal error receiving data"(kill) is displayed, reconnecting works OK.
* The same thing in simulation - works just as well.
* Connect to non-existent IP/port: a "cannot connect" appears, reconnecting works OK.

I haven't been able to reproduce the timeout issue though, I'll try some more.

**Comment by tritonas00** [comment]
le catastrophe with ac2e32ba6c4b08b49947ab66f90f5e1fca83fa25 i can't connect anywhere, RoR just closes

```
[RoR|Networking] Trying to join server '127.0.0.2' on port '12000' ...
[RoR|Networking] Connect(): Creating Send/Recv threads
[RoR|Networking] SendThread started
[RoR|Networking] RecvThread starting... (Thread ID: 140710463031040)
terminate called without an active exception
Aborted (core dumped)
```
```
(gdb) bt
#0  0x00007ffff6c5b755 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff6c46851 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff6fdb81f in __gnu_cxx::__verbose_terminate_handler () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff6fe830a in __cxxabiv1::__terminate (handler=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007ffff6fe8367 in std::terminate () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x0000555555819d16 in std::thread::operator= (__t=..., this=0x555555be8e18 <RoR::Networking::m_connect_thread>)
    at /usr/include/c++/9.1.0/thread:152
#6  RoR::Networking::StartConnecting () at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/network/Network.cpp:455
#7  0x000055555562c803 in RoR::MainMenu::MainMenuLoopUpdate (this=0x7fffffffe230, seconds_since_last_frame=0.0166667849)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/MainMenu.cpp:128
#8  0x000055555562c9a9 in RoR::MainMenu::EnterMainMenuLoop (this=this@entry=0x7fffffffe230)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/MainMenu.cpp:83
#9  0x00005555556031e3 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/main.cpp:342
```

5773c87119c16cc342dd2ddbe5f7317dce27231d works fine

:fearful:

**Comment by only-a-ptr** [comment]
Sorry, my mistake, I'm accidentally launching the connect thread twice. Updated.

**Comment by tritonas00** [comment]
Works fine now.

> I haven't been able to reproduce the timeout issue though, I'll try some more.

Yeah is a bit hard to reproduce that

> safer disconnects

You think it will improve this situation also or that is rorserver issue only? https://github.com/RigsOfRods/ror-server/pull/90#issuecomment-503613231 (happens sometimes)

**Comment by tritonas00** [comment]
One last issue with this PR, the "connecting" window is gone now

**Comment by only-a-ptr** [comment]
> RigsOfRods/ror-server#90 (comment) (happens sometimes)

Not affected.

> the "establishing connection" window is gone now.

I suspected that, but I only tested with local server and I thought it just connects that fast.

> (pressing esc while RoR is trying to connect -> crash)

It's the "ESC killswitch" in main menu, here it breaks the connecting thread.

**Comment by tritonas00** [comment]
Now works great. Thanks for fixing this.
kk

**Pull request merged**
