### PR TITLE
Reimplemented CrashRpt

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
Quote the [OS-X compile wiki page ](https://github.com/RigsOfRods/rigs-of-rods/wiki/Compile-(OS-X))
> Rigs of Rods is a complex beast. It has a 3D engine, physics simulator, water and sky plug-ins, input device system, networking, localisation plug-in module... and so on.

And because of that, it is useful to have a crash reporter because there are allot of things that can go wrong.
It can also help in fixing hard to reproduce crashes such as #1241

### CODE REVIEW

**Comment by only-a-ptr** [comment]
:100: 

I took a quick look at the crashfix installation you did. Login page looks OK, except the homepage (click the logo) yields HTTP 500 for some reason: http://crashfix.rigsofrods.org/index.php - at least for me at work (Win7 Pro SP1, x64, Firefox 40.0.2)

TODO: Port the "policy" page to new docs and fix the http://wiki.rigsofrods.com/pages/Crash_Report_Privacy_Policy link.

Give me a day to check it out.

**Comment by AnotherFoxGuy** [comment]
> TODO: Port the "policy" wikipage to new docs and fix the http://wiki.rigsofrods.com/pages/Crash_Report_Privacy_Policy link.

Done: https://github.com/RigsOfRods/docs.rigsofrods.org/pull/7
> Please make a CrashFix account for me and give me a day to test everything out.

And done :smiley:

**Comment by only-a-ptr** [comment]
Build issue: CrashRpt CMakeLists.txt seems to be hardcoded to generate lib/dll names with version included:
```
if(CRASHRPT_BUILD_SHARED_LIBS)
	set_target_properties(CrashRpt PROPERTIES 
									DEBUG_POSTFIX ${CRASHRPT_VER}d 
									RELEASE_POSTFIX ${CRASHRPT_VER} )
```
For me, this yielded CrashRpt1403.lib/exp/dll, but RoR's CMake is looking for CrashRpt.lib/dll.

Did you observe the same issue? How did you solve it?

**Comment by AnotherFoxGuy** [comment]
>For me, this yielded CrashRpt1403.lib/exp/dll, but RoR's CMake is looking for CrashRpt.lib/dll.
Did you observe the same issue? How did you solve it?

You only have to rename `CrashRpt1403.lib` to `CrashRpt.lib` and put it in `dependencies\libs\x86\CrashRpt\Release`

> CrashRpt requires "CrashSender{VER}.exe" to be present in RoR directory. Our Cmakescripts should pul it from dependencies/CrashRpt/bin, but there's no such logic. I added the EXE manually.

There is, but the path should be `\dependencies\bin\x86\CrashRpt\Release` instead of `dependencies/CrashRpt/bin`

**Comment by only-a-ptr** [comment]
> There is, but the path should be \dependencies\bin\x86\CrashRpt\Release instead of dependencies/CrashRpt/bin

I downloaded the AppVeyor dep-pack from dl.rigsofrods.org and figured that out. And yes, the path is incorrect, it was just an illustration.

One thing still puzzles me - the dep-pack has libs under `dependencies.7z\libs\x86\CrashRpt\*` although Cmake looks under `DEPS\libs\x86\CrashRpt\Release\*`

**Pull request merged**
