### PR TITLE
Deleted AA_DoxygenMainpage/MainPage.h

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
Removed the MainPage.h from the sources

### CODE REVIEW

**Comment by Hiradur** [comment]
To keep the commit history clean from merge commits such as ```Merge remote-tracking branch 'refs/remotes/RigsOfRods/master'``` it would be great if you could use your own master branch only to stay up to date with upstream and work on other branches for patches.

**Comment by Hiradur** [comment]
btw: What's the rationale behind this?

**Comment by only-a-ptr** [comment]
@Hiradur I requested this. Motivation: The directory 'source/source/AA_DoxygenMainpage' was ugly and misplaced - it contained single file 'MainPage.h' which belongs to '/doc' instead (since it's doxygen-only file)

**Comment by only-a-ptr** [comment]
@AnotherFoxGuy Thanks for taking care of the doxy docs. I have further request:
* The 'MainPage.h' is not bad, just misplaced. Instead of deleting it, create directory '/doc/doxygen' and move it there please. Close this PR, do the move in another branch and create new PR please.

**Pull request closed without merging**
