### PR TITLE
Avoid mixing up truckfiles when filename isn't unique.

### LINKED ISSUE #3166: Actors with matching filenames don't spawn correctly
If you have multiple zips containing truck files with the same filenames (common with private mods) only one will spawn correctly.
image
The first mod in the selector spawns OK, any duplicate filenames will fail to load all assets (meshes, materials etc):
screenshot_2024-07-17_16-52-32_1

```
16:52:08: Ogre::ItemIdentityException::ItemIdentityException: Cannot locate a resource group called '' in ResourceGroupManager::resourceExists at C:\Users\runneradmin\.conan2\p\b\ogre30c15d995aab6a\b\OgreMain\src\OgreResourceGroupManager.cpp (line 1566)
16:52:08: [RoR|Actor|Error] (Keyword: managedmaterials) Ogre::ItemIdentityException::ItemIdentityException: Cannot locate a resource group called '' in ResourceGroupManager::resourceExists at C:\Users\runneradmin\.conan2\p\b\ogre30c15d995aab6a\b\OgreMain\src\OgreResourceGroupManager.cpp (line 1566)
16:52:08: Ogre::ItemIdentityException::ItemIdentityException: Cannot find a group named  in ResourceGroupManager::isResourceGroupInitialised at C:\Users\runneradmin\.conan2\p\b\ogre30c15d995aab6a\b\OgreMain\src\OgreResourceGroupManager.cpp (line 1772)
```

### PR DESCRIPTION
**Pull request by ohlidalp**
Fixes #3166

**Problem1:** When spawning an actor, the cache entry was always looked up via truckfile name, even if it was already known from the Selector UI. This potentially caused mixups.

**Fix2:** Use the entry provided by Selector UI.

**Problem2**: in many scenarios, the game selects an actor by truckfile name alone:
 *   savegames
 *   preselected truck in RoR.cfg
 *   preloaded trucks on terrain (.tobj)
 *   Multiplayer spawn notifications

**Fix2**: introduce an optional "Bundle-qualified" syntax, i.e. "mybundle.zip:myactor.truck" (in case of ZIP archive) or "mysubdir:myproject.truck" (in case of subdir) and use it in all the above cases. Because it's optional, it doesn't need a version bump in savegame format or RoRnet protocol. Note that 'bundle' is RoR jargon for a ZIP archive or directory under /mods.

### Testing
Use the attached mods and spawn them using console commands:
[dafsemiMixupTest_hangar.zip](https://github.com/user-attachments/files/16480983/dafsemiMixupTest_hangar.zip)
[dafsemiMixupTest_transred.zip](https://github.com/user-attachments/files/16480984/dafsemiMixupTest_transred.zip)

This uses just filename - it will spawn the first one in your 'mods.cache' JSON file.
```
as game.pushMessage(MSG_SIM_SPAWN_ACTOR_REQUESTED, { {'filename', 'dafsemiMixupTest.truck'}, {'position', game.getPersonPosition()}, {'rotation', quaternion(game.getPersonRotation(), vector3(0,1,0))} });
```
This uses explicit bundle name, so it will spawn the Transred variant.
```
as game.pushMessage(MSG_SIM_SPAWN_ACTOR_REQUESTED, { {'filename', 'dafsemiMixupTest_transred.zip:dafsemiMixupTest.truck'}, {'position', game.getPersonPosition()}, {'rotation', quaternion(game.getPersonRotation(), vector3(0,1,0))} });
```
This uses explicit bundle name and demonstrates case-insensitive lookup - it will spawn the Hangar variant.
```
as game.pushMessage(MSG_SIM_SPAWN_ACTOR_REQUESTED, { {'filename', 'DAFSEMIMIXUPTEST_HANGAR.ZIP:DAFSEMIMIXUPTEST.TRUCK'}, {'position', game.getPersonPosition()}, {'rotation', quaternion(game.getPersonRotation(), vector3(0,1,0))} });
```

### CODE REVIEW

**Review by CuriousMike56 — COMMENTED** [review]
Duplicate files spawn OK now, however trying to load a savegame with them always crashes.

**Comment by ohlidalp** [comment]
Indeed, the savegames only record the filename. Same goes for:
* preselected truck in RoR.cfg
* preloaded trucks on terrain (.tobj)
* AFAIK also RoRnet spawn notifications

I'll try the following solution: in any text field which expects filename, user can also put "zname.zip:tname.truck". On Windows, `:` is already forbidden in filenames so this clearly indicates a special behavior - Linux doesn't have this rule but [it probably should](https://dwheeler.com/essays/fixing-unix-linux-filenames.html), so let's assume nobody puts colons in mod filenames.

**Comment by CuriousMike56** [comment]
Works nicely, though it's probably not a good idea for bundle names to be announced to other players:

Just another opportunity for someone to name the zip/subdir something vile.

**Comment by ohlidalp** [comment]
Very good point, I'll strip the names from the log messages.

**Comment by Zentro** [comment]
Works as intended.

**Pull request merged**
