### PR TITLE
Added  MSG_GUI_[OPEN/CLOSE]` for main menu and selector.

### PR DESCRIPTION
**Pull request by only-a-ptr**
Fixes issue with "Skip main menu" setting not working.
Remake of #2680

### CODE REVIEW

**Comment by tritonas00** [comment]
it opens like

kk

**Comment by only-a-ptr** [comment]
> it opens like

I tried all scenarios. Must be linux-specific. Try adding this before the message loop:
```
// Hack - force rendering image to properly init DearIMGUI
App::GetGuiManager()->GetLoadingWindow()->SetProgress(100, "Hack", /*renderFrame=*/true);
App::GetGuiManager()->SetVisible_LoadingWindow(false);
```

**Comment by tritonas00** [comment]
> Try adding this before the message loop:

worked fine! :+1:

**Review by tritonas00 — APPROVED** [review]
Main Menu and Selector seem to show/hide when they should.

**Pull request merged**
