### PR TITLE
Mission system (.missionzip)

### PR DESCRIPTION
**Pull request by ohlidalp**
**Info:**
https://forum.rigsofrods.org/threads/mission-system-prototype.3846/

**Features:**
* A new mod type is recognized: *.mission - can add terrain objects, procedural roads and races to existing terrain.
* A new archive type is recognized: *.missionzip
* Mission types: "race" and "stunt", more to come in the future.
* To load a mission, use top menubar "Simulation / Load a mission" (opens the Selector UI) or open in-game console and say 'loadmission _fileName_'
* To unload a mission, use top menubar "Missions" menu and click the red "X" letter.

**New scripts:**
* missions.as - like races.as but for missions. An include file. See comments on the top of the file.
* stunts.as - like races.as but for stunt-missions. An include file. See comments on the top of the file.
* mission_default.as - like terrain_default.as but for missions. Does the basic handling of .mission files.
* road_utils.as - an include file, does parsing procedural roads using GenericDocument tokenizer.

**New script API:**
* `array<BeamClass@> game.getAllTrucks()`
* `float game.getElapsedTime()`
* `array<BeamClass@> BeamClass.getAllLinkedTrucks()`
* `int BeamClass.getInstanceId()`
* Callback `eventCallbackEx()` - same as `eventCallback()` but with extra parameters.
* event types `SE_EVENTBOX_ENTER` and `SE_EVENTBOX_EXIT`
* `terrain.addSurveyMapEntity()`, `terrain.delSurveyMapEntities()`

**Example:**
Download the attached file and place it to your 'mods' directory. Note GitHub doesn't allow '.missionzip' extension, so I just used '.zip' - it works the same.
[simple2circuit.zip](https://github.com/RigsOfRods/rigs-of-rods/files/10715214/simple2circuit.zip)
To test, load the "Simple Test Terrain" (simple2.terrn2), open in-game console and say 'loadmission simple2circuit.mission'.
screenshot_2023-02-12_03-43-43_1

### CODE REVIEW

**Comment by only-a-ptr** [comment]
**IMPORTANT: Regenerate your cache! There was a bug and the mission entries are not filled properly.**

I added rudimentary UI for missions:
obrazek
obrazek

**Comment by only-a-ptr** [comment]
@CuriousMike56 suggested creating multiplayer challenges using this system: https://forum.rigsofrods.org/threads/mission-system-prototype.3846/#post-19130
To help with the coding, I added rorserver scripting documentation to https://developer.rigsofrods.org/ 
obrazek

**Comment by only-a-ptr** [comment]
New script function: `BeamClass.getAllLinkedActors()`
obrazek

**Comment by only-a-ptr** [comment]
I added a new mission type: 'stunt'. It uses 2 eventboxes and measures various parameters while travelling between them.
The screenshots shows the demo mission 'Simple Test Ramp' attached below - the start eventbox is at the ramp, the finish eventbox is on the landing ground.
obrazek
[simple2ramp.zip](https://github.com/RigsOfRods/rigs-of-rods/files/10844463/simple2ramp.zip)

**Comment by only-a-ptr** [comment]
Issues:
* selector UI doesn't display mission descriptions, reported on Discord: https://discord.com/channels/136544456244461568/189904947649708032/1089169194169405521

**Comment by xTakedownJnR** [comment]
hey, It's theJesser from discord :) . We definitely need the ability to add icons onto the overview map for missions as suggested by mike on discord https://discord.com/channels/136544456244461568/189904947649708032/1089317783164166266

**Comment by ohlidalp** [comment]
Closing this as stale and mostly obsolete:
* The scripting extensions were meanwhile merged in other PRs.
* The server documentation is also already online: https://developer.rigsofrods.org/d2/d42/group___script_side_a_p_is.html
* The missions implementation needs to be refined, in this order: 
   1. working terrain editor; 
   2. working terrain editor with race editing; 
   3. working terrain editor with race+mission editing (the race system is pretty extensible already)

**Pull request closed without merging**
