### PR TITLE
[cleanup] Separate BeamData.h into smaller header files

### PR DESCRIPTION
**Pull request by Aperion**
[Prepare] This is some cleanup used to integrate the new drivetrain changes

This separates the most commonly used parts of BeamData.h into separate headers. I've included the new headers in BeamData.h to avoid breaking existing code.

### CODE REVIEW

**Comment by Max98** [comment]
//skidmarks v2
bool isSkiding;

You forgot it again. :P

**Comment by Aperion** [comment]
@Max98 I don't know what you're talking about, it's clearly right there in the file! :P

**Comment by Max98** [comment]
Hahahahah you cheated there. :P

**Comment by Aperion** [comment]
Any objects to merging this ?

**Comment by Max98** [comment]
I'm with this.

**Pull request merged**
