### PR TITLE
Fix building without OpenAL/SocketW

### LINKED ISSUE #1442: Code is broken when compile under linux (Fedora 27)
Hi,
this is a bug https://github.com/vbextreme/RigsOfRodsFedora/issues/1 because the code is broken and not compile under linux.
i'm here for more information.

### PR DESCRIPTION
**Pull request by only-a-ptr**
Fixes #1442

### CODE REVIEW

**Comment by tritonas00** [comment]
with this PR, spawn an airplane (767 AA Airliner): engines sound are always on and full

**Comment by only-a-ptr** [comment]
@tritonas00 can you pass me the airplane? If it's not online anywhere at the moment, please upload it to Dropbox or attach it here. Thanks. I'll look into it immediately.

**Comment by tritonas00** [comment]
[767.zip](https://github.com/RigsOfRods/rigs-of-rods/files/1656924/767.zip)

**Comment by only-a-ptr** [comment]
@tritonas00 : got it: 'trigStart()' instead of 'trigStop()' here: https://github.com/RigsOfRods/rigs-of-rods/commit/8d37d839b4b50877410da33ae40b7911b2bb0d5d?diff=unified#diff-7616c633fb9c7e05e33466db62127ee9R262

**Pull request merged**
