### PR TITLE
Replaced JsonCPP with RapidJSON

### LINKED ISSUE #1331: Missing CMake module for Jsoncpp
@only-a-ptr Do we want to add a Find Jsoncpp CMake module or should we replace Jsoncpp with [RapidJSON](https://github.com/only-a-ptr/ror-dependencies/tree/rapidjson)?

### PR DESCRIPTION
**Pull request by only-a-ptr**
I want to use RapidJSON only in the remade multiplayer lobby: https://github.com/RigsOfRods/rigs-of-rods/pull/1333#issuecomment-331213832 To make the transition smoother, I want to make the switch in upstream first.

Fixes #1331

### CODE REVIEW

**Comment by tritonas00** [comment]
https://pastebin.com/xLht5trV

**Comment by only-a-ptr** [comment]
@tritonas00  I know, fixed that in the WIP2 commit - but it's crashing for me while reading the last row of JSON data, dunno why, and my today's time is up.

**Comment by tritonas00** [comment]
Yes, i can see the server list but if i press join it crashes

> terminate called after throwing an instance of 'std::future_error'
  what():  std::future_error: No associated state

**Comment by only-a-ptr** [comment]
> @tritonas00  Yes, i can see the server list but if i select a server and press join it crashes

I didn't even get there 😟

**Comment by tritonas00** [comment]
I don't know if helps but one server's address is missing (ANTest)
2017-09-22-182209_1920x1080_scrot

**Comment by only-a-ptr** [comment]
It's working now. Simple solution.

**Comment by AnotherFoxGuy** [comment]
@only-a-ptr It still crashes when I press the join button

**Comment by tritonas00** [comment]
Yes, same here

`Bad cast from type 'PN3RoR3GUI16MpServerlistData10ServerInfoE' to 'm'
terminate called after throwing an instance of 'MyGUI::Exception'
  what():  MyGUI EXCEPTION : Bad cast from type 'PN3RoR3GUI16MpServerlistData10ServerInfoE' to 'm'
 in MyGUI at /opt/rigsofrods/include/MYGUI/MyGUI_Any.h (line 102)`

**Comment by only-a-ptr** [comment]
Sorry, my bad. Updated the commit, try again.

**Comment by tritonas00** [comment]
Works! Please update travis dependencies also.

**Comment by only-a-ptr** [comment]
> @tritonas00 Please update travis dependencies also.

Updated, hopefully I got it right.

**Comment by only-a-ptr** [comment]
@AnotherFoxGuy I give up... where do you put headers in Travis?

**Comment by tritonas00** [comment]
Arch uses cmake and make install

https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/rapidjson

**Comment by tritonas00** [comment]
I think you need to add `-DCMAKE_INSTALL_PREFIX=$DEPS_INSTALL_DIR`

**Comment by tritonas00** [comment]
ok try this

>cd $DEPS_BUILD_DIR
git clone -q --depth=1 https://github.com/Tencent/rapidjson.git
cd rapidjson
cmake \
  -DRAPIDJSON_BUILD_DOC:BOOL=OFF \
  -DRAPIDJSON_BUILD_EXAMPLES:BOOL=OFF \
  -DRAPIDJSON_BUILD_TESTS:BOOL=OFF \
  -DCMAKE_INSTALL_PREFIX=$DEPS_INSTALL_DIR \
  .
make -s -j2
make install

**Comment by only-a-ptr** [comment]
@tritonas00 I followed the README: https://github.com/Tencent/rapidjson#installation

Trying your script anyway...

**Comment by tritonas00** [comment]
hmm yep probably the same thing... a can't help further

**Comment by only-a-ptr** [comment]
@AnotherFoxGuy Heeelp! 😆

**Comment by only-a-ptr** [comment]
@AnotherFoxGuy I need help. According to [travis-trusty whitelist](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty#L12583), the rapidjson-dev package should be OK to install. But it crashes Travis instead.

**Comment by tritonas00** [comment]
Also this https://github.com/RigsOfRods/rigs-of-rods/blob/08fc230fab0736146b818eb4acbdfebc526a1e7b/cmake/DependenciesConfig.cmake#L8 needs an update?

there is no rapidjson-dev package for trusty
https://packages.ubuntu.com/search?keywords=rapidjson&searchon=names&suite=all&section=all

**Comment by AnotherFoxGuy** [comment]
There is a rapidjson package for ubuntu 16+:
[Packaging status](https://repology.org/metapackage/rapidjson)

but it seems heavily outdated and throws this error when compiling:

```
[ 64%] Building CXX object source/main/CMakeFiles/RoR.dir/gui/panels/GUI_MultiplayerSelectorLayout.cpp.o
/src/source/main/gui/panels/GUI_MultiplayerSelector.cpp: In function 'RoR::GUI::MpServerlistData* RoR::GUI::FetchServerlist(std::__cxx11::string)':
/src/source/main/gui/panels/GUI_MultiplayerSelector.cpp:130:34: error: 'rapidjson::Document {aka class rapidjson::GenericDocument<rapidjson::UTF8<> >}' has no member named 'GetArray'
     size_t num_rows = j_data_doc.GetArray().Size();
                                  ^
```

**Pull request closed without merging**
