### PR TITLE
Updated main character animations: Walk,Run,Idele,Swim,Turn,Sidestep

### PR DESCRIPTION
**Pull request by vido89**
-updated Walk,Run,Swim_loop,Spot_swim,Idle_sway,Driving animation
-Add Sidestep animation
-Updated speed of animations

### CODE REVIEW

**Comment by Hiradur** [comment]
I just tried them and I think they are great. Two things though:
- the sidestep animations look unrealistic. I think the steps should be wider and quicker as well.
- RoRBot's teeth are visible when steering a truck in first person perspective. Same goes for the swimming animations. This needs more discussion for a proper fix (#400)
- the sidestep animations when swimming could be improved, e.g. by making the arm which points to the direction one is going take an "aerodynamic" form.

**Comment by vido89** [comment]
- I could try to inprove sidestep animation
- By movig RoRBot's behind should fix visible teeth. Im not sure how same goes  for the swimming animations or you have camera postion on your mind
- Im not sure what you thinking when you say "sidestep animations when swimming" is it side step animation or swimming animation and what you mean by "aerodinamic form"

**Comment by Hiradur** [comment]
> By movig RoRBot's behind should fix visible teeth. Im not sure how same goes for the swimming animations or you have camera postion on your mind

That would only work well for the land animations, not for the swimming animations. You shouldn't care about visible teeth for now, we need to discuss how to deal with this at another point in time.

For the swimming sideways animation you me be able to draw some inspiraton from https://www.youtube.com/watch?v=WN0eGhrfEs0

**Comment by vido89** [comment]
Oh side swim, yes right, while in water when press A or D animation for that, Im on to it code part is missing for those animations I hope to be able to test those animations in few days or week, cheers!

**Comment by vido89** [comment]
I'm almost done Swim_side animation hope that I could test it soon. Also someone could work on Jump animation implementation sice I did animation itself
Cheers!

**Comment by vido89** [comment]
Now animations should be all good, Im just curious are gone this animations will be used in next stable tnx

**Comment by ulteq** [comment]
@vido89, I will try to test it next week.

**Comment by vido89** [comment]
Ok great

**Comment by only-a-ptr** [comment]
@vido89 :+1:  Great work, I'd like to merge this to upstream.

However, this pull request has become quite messy - there are many revisions of the character mesh/skeleton + just 1 revision to source. Plus, many many commits merged in-between.

Please create a new branch from the top of upstream and re-apply your 1st commit (the source modifications) along with the latest revision of the mesh/skeleton files.

**Comment by vido89** [comment]
Iv just created new pull request, hope that will work like that, Im not very familiar with git

**Pull request closed without merging**
