### PR TITLE
🔧 CMake cleanup

### LINKED ISSUE #1991: Add 'install' target for `make` (so you can run `make install`)
It would be good to be able to run `make install` so that it copies `RoR` into `<installation prefix>/bin`, etc. This makes it easier for packaging, and is fairly standard.

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
### Changes
* Added Conan cmake wrappers
* Simplified CMakeLists
* Fixed #1991

### CODE REVIEW

**Comment by AnotherFoxGuy** [comment]
@tritonas00 
```..../util/domd: line 33: makedepend: command not found```
It seems you are missing makedepend

**Comment by tritonas00** [comment]
ok deps built fine, then i did `make -j7` and got linker errors at the end https://pastebin.com/NdVKNqLA

**Comment by tritonas00** [comment]
update 

`-DCMAKE_BUILD_TYPE=Release` works so the issue is with ois and `RelWithDebInfo` i guess...

**Comment by tritonas00** [comment]
Now it works fine.

**Comment by only-a-ptr** [comment]
I just tried and got this:
```
Found Threads: TRUE  
Conan: checking conan executable in path
Conan: Found program CONAN_CMD-NOTFOUND
Conan: Version found 
Conan: Adding ror-dependencies remote repository (https://api.bintray.com/conan/anotherfoxguy/ror-dependencies)
Conan: Adding bincrafters remote repository (https://api.bintray.com/conan/bincrafters/public-conan)
Conan: Using cmake-multi generator
Conan: Automatic detection of conan settings from cmake
Conan: Detected VS runtime: MD
Conan: Settings= -s;arch=x86_64;-s;build_type=Release;-s;compiler=Visual Studio;-s;compiler.version=15;-s;compiler.runtime=MD
Conan executing: conan install C:/Users/po185021/source/rigs-of-rods/conanfile.txt -s arch=x86_64 -s build_type=Release -s compiler=Visual Studio -s compiler.version=15 -s compiler.runtime=MD -g=cmake_multi --build=missing
CMake Error at cmake/3rdparty/conan.cmake:399 (message):
  Conan install failed='The system cannot find the file specified'
Call Stack (most recent call first):
  cmake/3rdparty/conan.cmake:480 (conan_cmake_install)
  cmake/DependenciesConfig.cmake:32 (conan_cmake_run)
  CMakeLists.txt:101 (include)
```
Not a big deal, just confusing -- missing Conan should be reported as fatal error instead of crashing later.

Platform: win10 x64, conan 1.16, cmake 3.14.5, visual studio 2017.
I used conan the classic way: `conan install ..\..\source\rigs-of-rods -u -s build_type=Debug --build=missing --build=OGRE` - I built OGRE to test some custom settings, unrelated.

**Comment by only-a-ptr** [comment]
Another thing, same system:
```
ERROR: OGRE/1.11.6@demo/testing: Error in build() method, line 70
	cmake.configure()
	ConanException: Error 1 while executing cd C:\Users\po185021\.conan\data\OGRE\1.11.6\demo\testing\build\2d13f0c58bafe8a9fae74369aea9c086e652e9f3 && cmake -G "Visual Studio 15 2017 Win64" -DCONAN_LINK_RUNTIME="/MD" -DCONAN_EXPORTED="1" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="15" -DCONAN_CXX_FLAGS="/MP8" -DCONAN_C_FLAGS="/MP8" -DCMAKE_INSTALL_PREFIX="C:\Users\po185021\.conan\data\OGRE\1.11.6\demo\testing\package\2d13f0c58bafe8a9fae74369aea9c086e652e9f3" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DOGRE_BUILD_DEPENDENCIES="OFF" -DOGRE_BUILD_COMPONENT_CSHARP="OFF" -DOGRE_BUILD_COMPONENT_JAVA="OFF" -DOGRE_BUILD_COMPONENT_PYTHON="OFF" -DOGRE_BUILD_PLUGIN_S
TBI="OFF" -DOGRE_BUILD_SAMPLES="OFF" -DOGRE_BUILD_RENDERSYSTEM_D3D9="ON" -DOGRE_BUILD_RENDERSYSTEM_D3D11="ON" -DOGRE_BUILD_RENDERSYSTEM_GL3PLUS="OFF" -DOGRE_RESOURCEMANAGER_STRICT="0" -DOGRE_INSTALL_SAMPLES="OFF" -D-D_OGRE_FILESYSTEM_ARCHIVE_UNICODE="1" -Wno-dev C:\Users\po185021\.conan\data\OGRE\1.11.6\demo\testing\build\2d13f0c58bafe8a9fae74369aea9c086e652e9f3

CMake Error at cmake/3rdparty/conan.cmake:399 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/3rdparty/conan.cmake:480 (conan_cmake_install)
  cmake/DependenciesConfig.cmake:32 (conan_cmake_run)
  CMakeLists.txt:101 (include)
```

**Pull request merged**
