### PR TITLE
Created flexbody debug view + GUI

### LINKED ISSUE #2923: Flexbody binds to nodes outside 'forset'.
Discord complaint by DannyWerewolf.

If a flexbody is bound to a detachable part and it detaches, the mesh keeps stretching after the vehicle, even though all nodes in the 'forset' have detached.
obrazek
obrazek
obrazek

it's probably because the flexbody binds 3 nodes for each vertex: reference, X and Y, and only the reference nodes are taken from the forset, while the X/Y nodes are searched by distance.

Danny Werewolf has a feeling that it's not a specific node but the center of the truck.

### PR DESCRIPTION
**Pull request by only-a-ptr**
This tool lets you inspect individual vertices and their generated bindings. Just hover mouse pointer over a vertex and see. Click the vertex to toggle persistent visibility.
Closes #2923.
obrazek
Vehicle on display: https://forum.rigsofrods.org/resources/honda-accord.281/

### CODE REVIEW

**Comment by only-a-ptr** [comment]
While looking at the debug view I created, I figured an optimization. Most often, many vertices bind to the same NREF/NX/NY nodes, so for optimal CPU cache usage, they should be processed together. However, currently they are processed in the order of vertices in the mesh, which is random, depending on the modelling tool and exporter. I wanted to actually see it, so I created a visualization:
obrazek
Next step - reorder vertices in the mesh (it's possible on runtime, I've already done it once) to match the nodes. The result will be visible in this graph.

**Comment by only-a-ptr** [comment]
I implemented the "defragmentation" of flexbody meshes. Figuring out the algorithm was a challenge, coding it was extremely prone to mixing things together.

In the image below, the vertex locators are reordered but texcoords aren't (checkbox is off), resulting in an artistic effect.
obrazek
Vehicle on display: Ford Tudor https://forum.rigsofrods.org/resources/1949-ford.283/

**Comment by Zentro** [comment]
No crashes or errors to report.

A minor thing, but when inspecting vertices and picking some with your mouse you can immediately deselect them. However, when unchecking the "Vertices" box after selecting a few vertices, the vertices can no longer be unselected (after rechecking the "Vertices" box) without browsing through the vertex locator table and unselecting them there. 
image

The defragmentation tool works without issue with the defaults, unselecting any or all of the 3 optimizations results in some interesting effects as you've noted in your previous reply. Not sure if this is intended or not.
image

**Comment by only-a-ptr** [comment]
**Purpose**: To visually explain how flexbodies work and help modders diagnose them.

**Estimate**: 1 man day. It all works.

**Comment by CuriousMike56** [comment]
Is the "hide others" option meant to show only the selected flexbody? if so it doesn't work:
image
Upon testing to see if it works with `nodes2`, I found an extreme use case: the high poly count of the [1971 DI Banger Brambler Package](https://www.dropbox.com/sh/x0lsx1ezlci8wx3/AADZsqt7KrAstf3sedLzcSQra/Vehicles/DI_Banger391%2BDI_Brambler391%2BDI_Revair391%2BDI_Tracer391.zip?dl=0) causes the frame rate to plummet when activating the debug views:
image
This most likely can't be "fixed" but could be an easy way to test further optimization. 

Otherwise it seems to work fine.

**Comment by only-a-ptr** [comment]
> @CuriousMike Is the "hide others" option meant to show only the selected flexbody? if so it doesn't work: (Desperado buggy)

It actually works perfectly, but what you're looking at aren't `flexbodies` but `props` :smile: But I admit it's confusing, so I added props to the list, too:
image
Yes, there's a glitch - props outside of `props` (like wheel rims) aren't accounted for, but I'll fix that after this PR.

> @CuriousMike56 the high poly count ... causes the frame rate to plummet when activating the debug views

That's because I'm drawing all those as circles using DearIMGUI (circa 6 triangles each, antialiased). Using raw vertex buffer would be much faster and would look pretty much equivalent in this case. But presently all our debug views work like this, I'll deal with this in the future if it troubles users.

**Comment by CuriousMike56** [comment]
Still can't get the hide others option to work, tried multiple vehicles with plenty of flexbodies 😕 
image

**Comment by only-a-ptr** [comment]
@CuriousMike56 Looks like it doesn't work at all for you... very strange. Try disabling PSSM and setting all visuals to lowest.

**Comment by CuriousMike56** [comment]
@only-a-ptr Turns out realtime reflections breaks it, works fine with it disabled:
image

**Comment by only-a-ptr** [comment]
> @CuriousMike56 Turns out realtime reflections breaks it, works fine with it disabled

Makes sense, all meshes must be hidden when rendering the reflections, otherwise they would obscure the view for the reflection-cameras. I fixed it by pausing reflections while "Hide all" is active, test once more please.

**Comment by CuriousMike56** [comment]
Now enabling "hide other" on the first entry on the list causes all flexbodies to disappear, leaving only the props:
image
image
All other flexbodies appear as normal:
image
Occurs with reflections enabled or disabled.

**Comment by CuriousMike56** [comment]
First flexbody not appearing still persists:
image

**Comment by only-a-ptr** [comment]
> @CuriousMike56  First flexbody not appearing still persists

Fixed.

**Review by CuriousMike56 — APPROVED** [review]
👍

**Review by Zentro — APPROVED** [review]

**Pull request merged**
