### PR TITLE
Truckfile now supports multiple `minimass` sections.

### PR DESCRIPTION
**Pull request by only-a-ptr**
image

Test load: 
[MultiMiniMass_Test_Load.zip](https://github.com/RigsOfRods/rigs-of-rods/files/2875354/MultiMiniMass_Test_Load.zip)

Section minimass got options:
```
; option n = filler, does nothing
minimass
10.0, n

; option d = sets new default value, like `set_node_defaults`
minimass
4.0, d
```

### CODE REVIEW

**Comment by ulteq** [comment]
Looks great! But I hope you tested it.

**Comment by only-a-ptr** [comment]
Testing now, it's not working as it should 🤔 
[MultiMiniMass_Test_Cube.zip](https://github.com/RigsOfRods/rigs-of-rods/files/2875289/MultiMiniMass_Test_Cube.zip)

**Comment by only-a-ptr** [comment]
Works!
image

Test load: 
[MultiMiniMass_Test_Load.zip](https://github.com/RigsOfRods/rigs-of-rods/files/2875354/MultiMiniMass_Test_Load.zip)

**Comment by ulteq** [comment]
> Works! Ready for merge.

The definition of `Works` in RoR is not that new content works, but that old content works.

**Comment by only-a-ptr** [comment]
Ok, it's broken. Desperado buggy (minimass = 1.0) spawns stiff like a rock, you can hardly even move it with mouse.

**Comment by ulteq** [comment]
> it was wheel nodes

Rim nodes to be precise. Tyre nodes are excluded from the regular mass calculation logic.

```
minimass
4.0, d
```
Won't affect rim nodes, right? Bug or feature?

**Comment by only-a-ptr** [comment]
> Won't affect rim nodes, right? Bug or feature?

Right, feature (compatibility) -> rim nodes always use the global minimass

**Comment by ulteq** [comment]
It still breaks 40% of all the mods I have:

Old: https://ptpb.pw/oh54.txt
New: https://ptpb.pw/LkIb.txt

**Comment by ulteq** [comment]
Out of 3490 mods only 7 had multiple `minimass` definitions.

**Comment by only-a-ptr** [comment]
@ulteq I fixed cinecam minimass, this resolved "MCD Skot firetruck" for me, please re-run your dump routine to check the others.

**Comment by ulteq** [comment]
Diff: https://ptpb.pw/9wC-

**Comment by only-a-ptr** [comment]
`wheels2` rim nodes were wrong. Everything seems OK for me now.

**Comment by ulteq** [comment]
https://github.com/RigsOfRods/rigs-of-rods/blob/0741c95157a4a241d31833fa982ec1dd5752f7c1/source/main/physics/RigSpawner.cpp#L4460 and https://github.com/RigsOfRods/rigs-of-rods/blob/0741c95157a4a241d31833fa982ec1dd5752f7c1/source/main/physics/RigSpawner.cpp#L4474 are technically not needed, right?

**Comment by only-a-ptr** [comment]
@ulteq I just removed those the second you posted it 😆

**Comment by ulteq** [comment]
Final issue: https://ptpb.pw/38gW

Download link: http://www.austingratzer.com/rigs/downloads.php?do=file&id=75

**Comment by DODGEcharger** [comment]
May have found a bug with the new minimass logic. 

If you define any node masses using loadweight, any minimass sections with the `d` option will inherit the loadweight above and apply it to subsequent nodes.

```
Original minimass:
minimass
7.08, n

Attempt to reset minimass:
;grp: swaybars
133,   -1.489,    1.007,   -0.456, l 18.82558
134,   -1.489,    1.007,    0.456, l 18.82558
135,   -1.081,    1.181,    0.456, l 18.82558
136,   -1.081,    1.181,   -0.456, l 18.82558
137,   -1.046,    0.996,    0.456, l 18.82558
138,   -1.046,    0.996,   -0.456, l 18.82558
139,   -0.903,    1.118,    0.456, l 18.82558
140,   -0.903,    1.118,   -0.456, l 18.82558
141,    2.092,    1.044,    0.486, l 18.82558
142,    2.092,    1.044,   -0.486, l 18.82558
143,    2.501,    1.217,   -0.486, l 18.82558
144,    2.501,    1.217,    0.486, l 18.82558
145,    2.532,    1.035,   -0.486, l 18.82558
146,    2.532,    1.035,    0.486, l 18.82558
147,    2.678,    1.154,    0.486, l 18.82558
148,    2.678,    1.154,   -0.486, l 18.82558

minimass
2.31, d

nodes 
;grp: cab
149,   -1.185,    2.153,    0.000, n
150,   -1.071,    2.102,    1.075, n
151,   -1.071,    2.102,   -1.075, n
152,   -1.071,    1.229,    1.075, n
153,   -1.071,    1.229,   -1.075, n
154,   -0.795,    2.639,    0.000, n
155,   -0.732,    2.595,   -0.785, n
156,   -0.732,    2.595,    0.785, n
157,   -0.273,    1.229,    0.999, n
158,   -0.273,    2.055,    0.999, n
159,   -0.273,    2.055,   -0.999, n
160,   -0.273,    1.229,   -0.999, n
161,   -0.086,    2.620,    0.785, n
162,   -0.086,    2.620,   -0.785, n
163,   -0.086,    2.664,    0.000, n
164,    0.557,    2.614,   -0.785, n
165,    0.557,    2.614,    0.785, n
166,    0.557,    2.658,    0.000, n
167,    0.589,    1.229,    0.999, n
168,    0.589,    2.007,   -0.999, n
169,    0.589,    1.229,   -0.999, n
170,    0.589,    2.007,    0.999, n
```

In-game result:
screenshot_2019-02-20_00-10-44_1

As you can see the node masses of the body shell are 18.8kg, same as the last load weight definition, instead of the 2.31kg defined by the new minimass.


IMO, it would make more sense if the new minimass option was simply a toggle that allowed node masses to be lighter than what the minimass specifies. It would negate the need for multiple minimass and node sections, and leave the previous weight tuning workflow unchanged.

**Comment by only-a-ptr** [comment]
@DODGEcharger I modified the test cube to reproduce the issue, but everything seems to work. Take a look pls:
[MultiMiniMass_Loadweight_Test.zip](https://github.com/RigsOfRods/rigs-of-rods/files/2884060/MultiMiniMass_Loadweight_Test.zip)

image

**Comment by ulteq** [comment]
> instead of the 2.31kg defined by the new minimass

The node mass will only equal the `minimass` if the automatically calculated mass for that given node would be less than or equal the `minimass`.

**Comment by ulteq** [comment]
> Ca toggle that allowed node masses to be lighter than what the minimass specifies

I would also make that a separate flag.

**Pull request merged**
