### PR TITLE
AngelScript: fixed ref counting, added ProceduralRoad API

### PR DESCRIPTION
**Pull request by only-a-ptr**
## Status (last update 2022-10-14)
Many feats originally developed here got merged in https://github.com/RigsOfRods/rigs-of-rods/pull/2931.
The object ref-counting system, originally created here, got perfected in it's own repo: https://github.com/only-a-ptr/RefCountingObject-AngelScript

## New script features:
* ref types: `TerrainClass, ProceduralRoadClass, ProceduralObjectClass, ProceduralManagerClass, ProceduralPointClass`
* enums: `RoadType, TextureFit`

## Reference counting fix

Previously, if a script kept a pointer (a 'handle' in AngelScript terminology) to `BeamClass` or `VehicleAIClass` after the vehicle was removed, it would crash. I studied how the reference counting system works and added a `RefCountingObject` base class which lets us keep track of the object both inside and outside of the script. It will help registering more objects to the script engine.

### CODE REVIEW

**Comment by only-a-ptr** [comment]
Sneak preview of what's coming. This script tests the new procedural road APIs and will become an useful tool later.
[terrain_editor-alpha1.as.zip](https://github.com/RigsOfRods/rigs-of-rods/files/9295558/terrain_editor-alpha1.as.zip)
I'm not committing the script until final, you can load it manually via RoR.cfg `app_custom_scripts=terrain_editor.as`
obrazek

**Comment by only-a-ptr** [comment]
It's all drawn by the script!
[terrain_editor-alpha2.as.zip](https://github.com/RigsOfRods/rigs-of-rods/files/9330640/terrain_editor-alpha2.as.zip)

obrazek

**Comment by only-a-ptr** [comment]
I added myself utils for easy testing scripts: Reload/Stop buttons and `loadscript` console commands if reloading fails.
obrazek

**Comment by tritonas00** [comment]
getting some gcc warnings:

```
/home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/utils/RefCountingObject.h:100:5: warning: ‘void operator delete(void*)’ called on pointer ‘*(RoR::Actor**)((char*)__first)’ with nonzero offset 8 [-Wfree-nonheap-object]
  100 |     }
```

**Comment by only-a-ptr** [comment]
`free-nonheap-object`? I didn't intend that, must double check.

I didn't expect a problem with calling conventions... But apparently linux x64 is more complicated: https://www.gamedev.net/forums/topic/712220-native-calling-on-linux-x86-64-not-working-for-a-type/

**Comment by only-a-ptr** [comment]
Marking this "ready for review" without the terrain editing script - the procedural road and the documentation updates are working and can be already useful to have in upstream.

**Comment by tritonas00** [comment]
will test soon

im-watching-you-charles-reese

**Comment by tritonas00** [comment]
Deleting actors crashes the game.

`double free or corruption (!prev)`

**Comment by AnotherFoxGuy** [comment]
AngelScript doesn't load anymore:

```
10:42:25: ScriptEngine initializing ...
10:42:25: Type registrations done. If you see no error above everything should be working
10:42:25:  (0, 0): Error = Type 'VehicleAIClass' is missing behaviours
10:42:25:  (0, 0): Info = A reference type must have the addref and release behaviours
10:42:25:  (0, 0): Error = Type 'BeamClass' is missing behaviours
10:42:25:  (0, 0): Info = A reference type must have the addref and release behaviours
10:42:25:  (0, 0): Error = Type 'TerrainClass' is missing behaviours
10:42:25:  (0, 0): Info = A reference type must have the addref and release behaviours
10:42:43:  (0, 0): Error = Invalid configuration. Verify the registered application interface.
10:42:43:  (0, 0): Error = Invalid configuration. Verify the registered application interface.
```

**Comment by only-a-ptr** [comment]
The work is almost done.

The `RefCountingObject` system works, except there's a breaking nuissance AngelScript side - you can't do `game.getPlayerTruck().getTruckName()` because you'll get error 'BeamClassPtr has no functon getTruckName()'. You need to do this instead:
```
BeamClass@ truck = game.getPlayerTruck();
truck.getTruckName(); // now it works!
```
I updated the terrain editor script. To test, just put it to "Documents/My Games/Rigs of Rods/scripts" and in game console, say 'loadscript terrain_editor.as'.

[terrain_editor-alpha4.as.zip](https://github.com/RigsOfRods/rigs-of-rods/files/9815987/terrain_editor-alpha4.as.zip)

**Comment by tritonas00** [comment]
Crashed as soon as i spawned a desperado in f1 testtrack. Also still got massive spam about:
```
In destructor ‘RefCountingObject<T>::~RefCountingObject() [with T = RoR::Actor]’,
    inlined from ‘void RefCountingObject<T>::Release() [with T = RoR::Actor]’ at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/utils/memory/RefCountingObject.h:33:13,
    inlined from ‘void RefCountingObject<T>::Release() [with T = RoR::Actor]’ at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/utils/memory/RefCountingObject.h:28:10,
    inlined from ‘void RefCountingObjectPtr<T>::ReleaseHandle() [with T = RoR::Actor]’ at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/utils/memory/RefCountingObjectPtr.h:198:23,
    inlined from ‘RefCountingObjectPtr<T>::~RefCountingObjectPtr() [with T = RoR::Actor]’ at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/utils/memory/RefCountingObjectPtr.h:190:18,
    inlined from ‘void RoR::GfxActor::UpdateParticles(float)’ at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gfx/GfxActor.cpp:533:25:
/home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/utils/memory/RefCountingObject.h:21:5: warning: ‘void operator delete(void*)’ called on pointer ‘<anonymous>.RefCountingObjectPtr<RoR::Actor>::m_ref’ with nonzero offset 8 [-Wfree-nonheap-object]
   21 |     }
```

**Comment by only-a-ptr** [comment]
**Purpose:** To do AngelScript right - currently the object refcounting is dummy and prone to crash.

**Estimate:** 8 man days. This is hard work but it's an once-and-for-all fix which needs to be done at some point.

**Work to be done:**
1. backport changes made here to https://github.com/only-a-ptr/RefCountingObject-AngelScript
2. replicate the problem there
3. get help from AngelScript author

**Comment by only-a-ptr** [comment]
I'm closing this because it got stale and it was too invasive to begin with. I'll start a new PR with less code and more added value.

**Pull request closed without merging**
