### PR TITLE
Created test harness (using GoogleTest)

### PR DESCRIPTION
**Pull request by only-a-ptr**
Hello RoR fans.

I'm proud to announce I've developed an environment for automated testing for RoR. This means it's possible, without much hassle, to create short programs which load a portion of RoR, feed it with some predefined data, run RoR and check the data are modified correctly. This provides 2 advantages:
1. Developer will quickly find out that he accidentally broke something (if it's an intentional change, s/he must modify the test).
2. Developer can read the test to find out what exactly are RoR features supposed to do - because figuring it out directly from the codebase can be quite hard.

Why now? Because we've just had a textbook example of a regression bug which could have been avoided by tests: #2334. It doesn't look like a big deal, but it's actually pretty sneaky:
1. It didn't affect trucks which have node#0 on position 0,0,0 - it's not required, but apparently some trucks are made that way (for example ScaniaWrecker on NHelens). This is too tricky for a human tester to figure out.
2. While the bug was in upstream, one of the affected maps (NHelens with misplaced bridge) actually got updated to curb the problem! I didn't know it and I actually thought there is another bug. So much for finding regressions using content.

And so, to preserve RoR's backward compatibility (and my sanity), I decided the time has come to accept some good programming manners and start testing. I've never written tests before, so I had to learn as I go - that's why all the test stuff comes in a single commit, the development history was simply too messy. Also, the spawn-positions test is quite convoluted because setting up RoR + Ogre without any resources or rendering was a challenge, and calculating the node positions for verifications is simply as complicated as the spawning itself. As soon as I add another test, I'll give it a proper 'fixture' shape.

### CODE REVIEW

**Comment by tritonas00** [comment]
`-DROR_USE_GOOGLETEST=FALSE` builds fine, things spawn correctly now

`-DROR_USE_GOOGLETEST=TRUE` needs package gtest, installed but got

```[  9%] Building CXX object test/suites/UtilsTestSuite/CMakeFiles/UtilsTestSuite.dir/__/__/__/source/main/utils/SHA1.cpp.o
In file included from /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/utils/Utils.h:30,
                 from /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/utils/Utils.cpp:22:
/home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/RoRPrerequisites.h:24:10: fatal error: OgrePrerequisites.h: No such file or directory
   24 | #include <OgrePrerequisites.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.```

**Comment by tritonas00** [comment]
i think its time to have https://github.com/RigsOfRods/rigs-of-rods/pull/2397/commits/6b9fe563d0788de7eda2849da23965cabdb66db2 on master please

**Comment by tritonas00** [comment]
@only-a-ptr there is no conan package OIS https://github.com/RigsOfRods/rigs-of-rods/blob/master/conanfile.txt, ois lib is included in OGREdeps conan package

**Comment by only-a-ptr** [comment]
@tritonas00 Thanks. That's all I can do for today 💤

**Comment by only-a-ptr** [comment]
A linking error, Travis? I give up for today :zzz:

**Comment by CuriousMike56** [comment]
Works fine on Windows 👍

**Comment by only-a-ptr** [comment]
Closing as out of date, should be revisited later - automated testing is a good thing to have!

**Pull request closed without merging**
