### PR TITLE
⬆️ Upgrade OGRE to 1.12

### LINKED ISSUE #2351: Upgrade to OGRE 1.12
https://github.com/OGRECave/ogre/releases/tag/v1.12.0

## TODO

- [ ] Update conan package
- [ ] Update ogre-caelum
- [ ] Update pagedgeometry

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
Fixes #2351
Status: Builds, but images don't load 

TODO
------------------------

- [x] Add Media/ShadowVolume (See https://github.com/OGRECave/ogre/blob/master/Docs/1.12-Notes.md#stable-media-files)
- [x] ~Fix MyGUI~ #2460 instead

### CODE REVIEW

**Comment by tritonas00** [comment]
reminder https://github.com/RigsOfRods/rigs-of-rods/issues/2351#issuecomment-488066550

**Comment by tritonas00** [comment]
> but images don't load

what images? if you mean the terrain/vehicle selector images they seem to worn fine her with 1.12.2

**Comment by AnotherFoxGuy** [comment]
> What images? If you mean the terrain/vehicle selector images they seem to work fine here with 1.12.2

The background images and MyGUI isn't loading anymore

**Comment by tritonas00** [comment]
Did you use latest mygui or `07da0620e0d835346452b02b7b1ba7c583429736` ?

**Comment by AnotherFoxGuy** [comment]
> Did you use latest mygui or `07da0620e0d835346452b02b7b1ba7c583429736` ?

The MyGUI testing package uses https://github.com/MyGUI/mygui/commit/0726ed4ae70b3479677a794a6a3dd5d6cc48ed62
(See https://github.com/AnotherFoxGuy/conan-MyGUI/blob/testing/3.2.3/conanfile.py)

**Comment by tritonas00** [comment]
`07da0620e0d835346452b02b7b1ba7c583429736` works here so maybe you want to give it a try

**Comment by AnotherFoxGuy** [comment]
The issue with MyGUI seems to only occur with Dx9, GL and Dx11 work fine

**Comment by only-a-ptr** [comment]
@AnotherFoxGuy Please update our conan-Caelum package: https://github.com/OGRECave/ogre-caelum/commit/d8175189d07fcee1081064287e997629982795d0

**Comment by only-a-ptr** [comment]
@AnotherFoxGuy I'm testing on Win10 (x64, Debug build) and RoR crashes on startup because it can't read PNG format. The only available image codecs (I looked with a Debugger) are: dds, ktx, pkm (whatever those are). Apparently something didn't build right in the {conan + OGRE.12 + Debug} combo (Release works fine). Can you take a look please?

**Pull request closed without merging**
