### PR TITLE
Make GFX match physics speed

### PR DESCRIPTION
**Pull request by Miner34dev**
Progress:

- [x] HydraX waves
- [ ] Particles (WIP)
- [ ] Other effects (like water godrays)
- [ ] Cleanup

### CODE REVIEW

**Comment by Miner34dev** [comment]
It may take a bit more than i expected since dustpool.cpp is not able to be slowed down/sped up at all and will require to be modified.

**Comment by ohlidalp** [comment]
Hello there, this is an unusually ambitious project for a guest developer, I like it.

To be honest I don't know how OGRE's particle system is used properly - our dustpool seems to literally reserve a pool of 100 `Ogre::ParticleSystem` instances and then 'allocate' them as needed. However, this might do the trick: https://ogrecave.github.io/ogre/api/1.11/class_ogre_1_1_particle_system.html#afd8ec707603e16d1b0eec2e734486947

If you use Discord, come visit our #dev channel: https://discord.com/channels/136544456244461568/189904947649708032

**Comment by Miner34dev** [comment]
> However, this might do the trick:  https://ogrecave.github.io/ogre/api/1.11/class_ogre_1_1_particle_system.html#afd8ec707603e16d1b0eec2e734486947 - basically it should be an one-liner inside the `DustPool::update()` loop:
> 
> ```
> pss[i]->setSpeedFactor(App::GetGameContext()->GetActorManager()->GetSimulationSpeed());
> ```
It works only partially. The smoke follows physics speed but doesn't stop when you stop them, sparks seem to be slowed down but something looks wrong (don't know what exactly) and all the other particles are completely unaffected. I'm trying to figure out why.

**Comment by ohlidalp** [comment]
Hmm, I guess we must do this:
```
const float speedFactor = (App::sim_state->GetEnum<SimState>() == SimState::PAUSED) ? 0.f : App::GetGameContext()->GetActorManager()->GetSimulationSpeed();
// .. 
pss[i]->setSpeedFactor(speedFactor);
```
or just `pss[i]->setSpeedFactor(0.f);` once when pausing.

**Comment by Miner34dev** [comment]
> Hmm, I guess we must do this:
> 
> ```
> const float speedFactor = (App::sim_state->GetEnum<SimState>() == SimState::PAUSED) 
>     ? 0.f 
>     : App::GetGameContext()->GetActorManager()->GetSimulationSpeed();
> // ~~~~~~~
> pss[i]->setSpeedFactor(speedFactor);
> ```
> 
> or just `pss[i]->setSpeedFactor(0.f);` once when pausing.

I have no idea why, but it has no effect.

**Comment by Miner34dev** [comment]
Found the problem. GFXScene only updates the particles if the physics aren't stopped.

**Comment by ohlidalp** [comment]
Closing in favor of #3170

**Pull request closed without merging**
