### PR TITLE
🔧 Replaced NSIS with WiX 

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
Screenshots of the new installer: 

msiexec_2019-08-27_13-47-46
msiexec_2019-08-27_13-47-58

### CODE REVIEW

**Comment by only-a-ptr** [comment]
Wow, CPack is mighty, I know how complex WiX is.

I don't like the orange, though (or is that your desktop setting?). Since we got our new dark logo, let's go for darker UI, too.

**Comment by AnotherFoxGuy** [comment]
The orange is from my windows theme 

This is what it looks like with blue windows theme 

msiexec_2019-08-27_14-55-27

**Comment by AnotherFoxGuy** [comment]
Fixed

image

**Comment by AnotherFoxGuy** [comment]
> Is this intended to replace mine?

No, this replaces this installer: http://prdownloads.sourceforge.net/rigs-of-rods/Rigs-of-Rods-0.4.8.0-RC5.exe

image

**Pull request merged**
