### PR TITLE
Fixed air dashboard showing previous vehicle's state

### LINKED ISSUE #1560: Transmission indicators freeze in some vehicles when going back to menu
~Load simple terrain and spawn this http://archives.rigsofrods.net/repo/files/repofiles-3rd-batch/df0ec67470bf500641d7f05f1a47cf0a7631b9ab_Mercedes-Benz-Actros-8x8-wrecker.zip~

~Switch to first person view (dashboard view) and drive: transmission indicators work fine~

~Press Back to menu, reload simple terrain and respawn it again: transmission indicators are stuck~

FIXED

### PR DESCRIPTION
**Pull request by only-a-ptr**
Fixes #1560

UPDATE: Original solution scrapped, see https://github.com/RigsOfRods/rigs-of-rods/pull/2403#issuecomment-518029318

### CODE REVIEW

**Comment by tritonas00** [comment]
Great but the reset values should be like the first spawn: GPWS ON and the four levers visible like this

kk

Instead its
kk

**Comment by tritonas00** [comment]
For some strange reason even with https://github.com/RigsOfRods/rigs-of-rods/pull/2403/commits/35712b27ae69c0649097688334253a9f4faf9489 sliders still disappear :confused:

**Comment by only-a-ptr** [comment]
Updated and tested. I had to open C++ reference manual to find the problem :smile:

**Comment by tritonas00** [comment]
:+1: 

Any idea why
> spawn airplaine-> turn off GPWS -> backspace: GPWS becomes on as it should but it takes two presses to turn it off

?

**Comment by only-a-ptr** [comment]
Doh! That's because I'm just resetting the button texture to ON but apparently the vehicle remembers the state.

**Comment by tritonas00** [comment]
> All the issues are valid again.

Not all, all four throttle sliders are now resetted into the correct position :+1:

**Comment by only-a-ptr** [comment]
Finished. Whole aero dashboard is now updated from SimBuffer on every render, and thus impervious to the lingering outdated values.

**Comment by tritonas00** [comment]
Works like a charm!

**Comment by tritonas00** [comment]
one minor issue GPWS gets off when you reset (backspace or i)

**Comment by only-a-ptr** [comment]
Updated. Turned out the ad-hoc updating of the overlays was a real cancer 🤢 

The backspace (COMMON_REPAIR_TRUCK) works as intended - it keeps the autopilot as-is.

The reset-to-initial-pos (COMMON_RESET_TRUCK) was buggy - it updated the dashboard GUI directly, but not the actual state. Fixed.

**Comment by tritonas00** [comment]
works now!

other issue: this section is wrongly updated comparing master and this PR
kk

just spawn the antonov12 or the skyvan start the engines and raise throttle levers

**Comment by tritonas00** [comment]
now its epic :heart:

**Pull request merged**
