### PR TITLE
[Codechange] Allow anything but spaces in the command options

### PR DESCRIPTION
**Pull request by ulteq**
This would fix the Chinook: http://www.rigsofrods.com/repository/download/1426

Alternative would be fallback to ParseUnsafe

### CODE REVIEW

**Comment by only-a-ptr** [comment]
This would fail if there's a delimiter comma without any whitespace between options and description.
A working solution should be using ```E_STRING_ANYTHING_BUT_DELIMITER```

**Comment by ulteq** [comment]
> A working solution should be using E_STRING_ANYTHING_BUT_DELIMITER

That doesn't work, the regex fails because of that trailing comma.

> This would fail if there's a delimiter comma without any whitespace between options and description.

I know. How common is this case?

> The Chinook above contains invalid trailing commas in "commands", so the above commit should report "invalid character <,> "

It reports something like: "ignoring invalid option ','"

**Comment by ulteq** [comment]
So we just add `ParseCommandsUnsafe` and `ParseCommands2Unsafe` and be done with it?

**Comment by only-a-ptr** [comment]
> That doesn't work, the COMMANDS regex fails because of that trailing comma.
Oh, right. It needs:
```
capture(contract)
capture(delim)
capture(expand)
capture(delim)
capture_opt(
  capture(delim)
  capture_opt(
    capture(options!)
    capture_opt(
      capture(delim)
      capture_opt(
        capture(desc)
      )
    )
  )
)
```

**Comment by ulteq** [comment]
Yeah, that's something we should do everywhere. Will you do it? :grin:

**Comment by only-a-ptr** [comment]
> Yeah, that's something we should do everywhere. Will you do it? :grin: 

We can only do that if we add ```ParseAbcUnsafe()``` everywhere. The current regexes are tuned to 
tolerate per-section-specific quirks, correcting all of them would break content. I have less annoying things to do :tired_face: I'll just fix the commands[2]

**Comment by ulteq** [comment]
> I'll just fix the commands[2]

Fair enough. :+1:

**Pull request closed without merging**
