### PR TITLE
Serverlist UI - doubleclick and tabs

### PR DESCRIPTION
**Pull request by only-a-ptr**
image

### CODE REVIEW

**Comment by AnimosusTheWolf** [comment]
https://user-images.githubusercontent.com/10286567/117165862-189a0480-ad83-11eb-9bd8-167cb1880580.mp4

**Comment by tritonas00** [comment]
Great!

Always wondering if `Passwd?` column name is a typo, chaging to `Password` will break anything?:laughing:

**Review by WillyB1337 — APPROVED** [review]
Nice addition!

**Comment by only-a-ptr** [comment]
> wondering if Passwd? column name is a typo

No, I just tried to narrow down the column header. We may as well remove the column and put an icon in front of server name:
lock
lock_open

**Comment by tritonas00** [comment]
That would be nice also.

**Comment by only-a-ptr** [comment]
I like this best.
image

**Review by WillyB1337 — APPROVED** [review]

**Comment by tritonas00** [comment]
Epic

**Review by tritonas00 — APPROVED** [review]

**Review by Zentro — APPROVED** [review]

**Pull request merged**
