### PR TITLE
[Codechange] Overhauled the network code

### PR DESCRIPTION
**Pull request by ulteq**
Fixes the following bugs:
* Character moves twice as fast in multiplayer
* Game script messages cause stuttering
* Network congestion causes severe stuttering
* Sending outdated stream data when newer data is already available
* Random crashes / freezes when trucks are removed (Fixes: #962, #963)
* `Texture 'us.png' not found` warning in the main menu
* Player list not updated in the main menu
* Heavy stuttering of remote trucks

Features:
* Fully asynchronous network communication

Needs a code review and some in-depth testing.

### CODE REVIEW

**Comment by Hotrod55** [comment]
Gives these build errors:
```
3>c:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.h(47): error C2039: 'unique_ptr': is not a member of 'std' (compiling source file C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp)
3>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\iterator(14): note: see declaration of 'std' (compiling source file C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp)
3>c:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.h(47): error C2065: 'unique_ptr': undeclared identifier (compiling source file C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp)
3>c:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.h(47): error C2275: 'Character': illegal use of this type as an expression (compiling source file C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp)
3>  c:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\Character.h(28): note: see declaration of 'Character' (compiling source file C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp)
3>c:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.h(47): error C2974: 'std::vector': invalid template argument for '_Ty', type expected (compiling source file C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp)
3>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(682): note: see declaration of 'std::vector' (compiling source file C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp)
3>c:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.h(47): error C2059: syntax error: '>' (compiling source file C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp)
3>c:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.h(47): error C2238: unexpected token(s) preceding ';' (compiling source file C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp)
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(41): error C2065: 'm_characters': undeclared identifier
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(41): error C2228: left of '.push_back' must have class/struct/union
3>  C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(41): note: type is 'unknown-type'
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(41): error C2039: 'unique_ptr': is not a member of 'std'
3>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\iterator(14): note: see declaration of 'std'
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(41): error C2065: 'unique_ptr': undeclared identifier
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(41): error C2275: 'Character': illegal use of this type as an expression
3>  c:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\Character.h(28): note: see declaration of 'Character'
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(46): error C2065: 'm_characters': undeclared identifier
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(46): error C2228: left of '.begin' must have class/struct/union
3>  C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(46): note: type is 'unknown-type'
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(46): error C3536: 'it': cannot be used before it is initialized
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(46): error C2228: left of '.end' must have class/struct/union
3>  C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(46): note: type is 'unknown-type'
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(48): error C2100: illegal indirection
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(48): error C2227: left of '->getSourceID' must point to class/struct/union/generic type
3>  C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(48): note: type is 'int'
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(50): error C2100: illegal indirection
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(50): error C2228: left of '.reset' must have class/struct/union
3>  C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(50): note: type is 'int'
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(51): error C2065: 'm_characters': undeclared identifier
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(51): error C2228: left of '.erase' must have class/struct/union
3>  C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(51): note: type is 'unknown-type'
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(62): error C2065: 'm_characters': undeclared identifier
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(63): error C3312: no callable 'begin' function found for type 'unknown-type'
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(63): error C3312: no callable 'end' function found for type 'unknown-type'
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(64): error C2065: 'c': undeclared identifier
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(64): error C2227: left of '->update' must point to class/struct/union/generic type
3>  C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(64): note: type is 'unknown-type'
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(65): error C2065: 'c': undeclared identifier
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(65): error C2227: left of '->updateLabels' must point to class/struct/union/generic type
3>  C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(65): note: type is 'unknown-type'
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(85): error C2065: 'm_characters': undeclared identifier
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(85): error C3312: no callable 'begin' function found for type 'unknown-type'
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(85): error C3312: no callable 'end' function found for type 'unknown-type'
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(87): error C2065: 'c': undeclared identifier
3>C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(87): error C2227: left of '->receiveStreamData' must point to class/struct/union/generic type
3>  C:\ror-dev\rigs-of-rods\rigs-of-rods\source\main\gameplay\CharacterFactory.cpp(87): note: type is 'unknown-type'
```

**Comment by ulteq** [comment]
> Gives these build errors

Should be fixed now.

**Comment by only-a-ptr** [comment]
Yess! You did it, man! :100: :clap: :smiley: 
I'll need a while to make a thorough review, but just by the looks of the `RoR::Network` API + the changelog vs. +/- statistics, it looks awesome.
You should add yourself to the Network.{h/cpp} license blocks, you earned it.

**Comment by mikadou** [comment]
@ulteq Comments are in random order and none of them are particular issues. Just thoughts I had while going through the code.

* I still can't get to like the implementation of using free functions in a namespace as interface and using static global variables inside the module to represent internal state. First, initialization order of these variables is undefined. It doesn't matter in this case and likely never will. Still, it is a potential gotcha that could be really nasty to track down, if it bites us in the future. The second thing that irks me, is that while intialization order itself is undefined, all global statics are guaranteed to be initialized on startup before entering main. Sure, this won't cause any noticable difference in startup time, however, it still bothers me, that even when not playing over network, memory is being used for network stuff.

* Use named enum type instead of `int` for message type in `SendMessage`. Also return `bool` instead of `int`

* Style suggestion: Replace

        header_t head;
        memset(&head, 0, sizeof(header_t));
        head.command = type;
        head.source = m_uid;
        head.size = len;
        head.streamid = streamid;

  with

        header_t head = {
            .command = type,
            .source = m_uid,
            .size = len,
            .streamid = streamid
        };

* https://github.com/ulteq/rigs-of-rods/blob/network-revamp/source/main/network/Network.cpp#L171-L172 Redundant `memset`

* BTW is `SendMessageRaw` threadsafe (that is, is SocketW threadsafe)? It dosent't matter here if I see it correctly. Just curious.

* What is the rational of sleeping here https://github.com/ulteq/rigs-of-rods/blob/network-revamp/source/main/network/Network.cpp#L256 ? Other than that threading looks fine to me.

* https://github.com/ulteq/rigs-of-rods/blob/network-revamp/source/main/network/Network.cpp#L256 Are these basically unused? Also `NETQUALITY` stuff doesn't seem to be really used?

* Another style suggestion:

        auto user = std::find_if(begin(m_users), end(m_users), [&](auto &u){ return static_cast<int>(u.uniqueid) == header.source; });
        if (user != end(m_users)) {
            Ogre::UTFString msg = RoR::ChatSystem::GetColouredName(user->username, user->colournum) + RoR::Color::CommandColour + _L(" left the game");
            const char *utf8_line = msg.asUTF8_c_str();
            header_t head = {
                .command = MSG2_UTF_CHAT,
                .source  = -1,
                .size    = (int) strlen(utf8_line)
            };
            QueueStreamData(head, (char *)utf8_line);
            LOG(Ogre::UTFString(user->username) + _L(" left the game"));
            m_users.erase(user);
        }

**Comment by ulteq** [comment]
> Also `NETQUALITY` stuff doesn't seem to be really used?

Yes, it was also unused in the old code. But it seemed to be useful enough to not just remove it.

**Comment by only-a-ptr** [comment]
@mikadou Thanks for the comments

> I still can't get to like...

* I'm not really opposed to transforming this into a class sometime in the future. But in current codebase, the global functions work best IMO. Or would you prefer a dynamic object in `gEnv`? Passing a pointer around is not an option right now.
* Is it the always-reserved memory that bothers you, or it's potentially useless initialization? In principle, you're right about this, but in practice, we have a lot bigger issues with our startup.

**Comment by mikadou** [comment]
> Is it the always-reserved memory that bothers you, or it's potentially useless initialization?

Both :smile:  I agree this is not really an issue here, though.

Can we merge this then? It seems to me that @ulteq has tested this enough to include it.

**Comment by only-a-ptr** [comment]
> Can we merge this then? It seems to me that @ulteq has tested this enough...

:+1:

**Comment by ulteq** [comment]
All right.

**Pull request merged**
