### PR TITLE
[Bugfix] Fixes tracked vehicles

### PR DESCRIPTION
**Pull request by ulteq**
Fixes: #381

### CODE REVIEW

**Comment by ulteq** [comment]
This would be a better solution than this: https://github.com/RigsOfRods/rigs-of-rods/pull/1145, if it works as good.

**Comment by only-a-ptr** [comment]
I can't figure anything from the code. If testing shows an improvement, let's take it in.

**Comment by AnotherFoxGuy** [comment]
This also fixes the Mercedes-Benz Atego w/ Comax rear flaps from spazzing out.

**Comment by ulteq** [comment]
> I can't figure anything from the code.

This decreases the chance of overlooking a `contacter` <--> `cab` collision by introducing a 10 second (20000 physics steps) cool-down time for frequently hit `cabs`.

This effectively disables the `collcabrate` optimization for those cabs.

**Pull request merged**
