### PR TITLE
Fixed ControlsUI not showing built-in defaults

### PR DESCRIPTION
**Pull request by only-a-ptr**
only entries actually present in 'input.map' were shown, other controls were missing.

If you edit an entry which wasn't present in 'input.map' before, it will be added.

### CODE REVIEW

**Comment by tritonas00** [comment]
With this controls panel indeed show all keys but it confusing things. Purpose of controls panel is to show, edit and preserve values in input.map, not hardcoded values.

**Comment by only-a-ptr** [comment]
@tritonas00 The way you describe it, overriding a default means the user must first manually add the entry to input.map and only then they are allowed to use the editing capability of the Settings UI. This makes no sense to me - I'd expect it to display everything and add modified entries to input.map.

**Comment by tritonas00** [comment]
So if i make a change on one of those extra controls it will be preserved in input.map? If yes then its good.

**Comment by CuriousMike56** [comment]
I don't see any problems with this change besidss the hardcoded text already mentioned. However I did just notice `CHARACTER_RUN` (https://github.com/RigsOfRods/rigs-of-rods/blob/master/resources/skeleton/config/input.map#L72) has two keys assigned in `input.map` which results in the second key name being blank:
image
This isn't a problem introduced by this PR, but I figured it makes sense for it be fixed here.

**Comment by only-a-ptr** [comment]
@CuriousMike56 What seems to you like a blank line is actually single row with double vertical size. But yes, it's confusing, so I added small numbers to make it obvious:
obrazek
I didn't figure any solution to the hardcoded hotkeys in top menubar, but I'd let it pass for now.

**Review by CuriousMike56 — APPROVED** [review]

**Review by Zentro — APPROVED** [review]

**Pull request merged**
