### PR TITLE
[Cleanup] truckCollision code cleanup

### PR DESCRIPTION
**Pull request by ulteq**
* Removed redundant intraPointCD objects

* Combined the Prepare, Compute and Final methods

Positive side effect: The interPointCD->update() method is now executed in the thread pool

[Before: ~ 20 fps](https://cloud.githubusercontent.com/assets/9437207/11934059/f8eab4e2-a7ff-11e5-90b1-cbba2281066c.jpg)
[After: ~ 40 fps](https://cloud.githubusercontent.com/assets/9437207/11934057/f3bb504e-a7ff-11e5-80e3-27a2539d9f44.jpg)

### CODE REVIEW

**Comment by Hiradur** [comment]
:+1:

**Comment by ulteq** [comment]
Fixed it, thanks.

**Comment by only-a-ptr** [comment]
:+1:

**Comment by ulteq** [comment]
Closed, because all changes are part of this: https://github.com/RigsOfRods/rigs-of-rods/pull/496

**Pull request closed without merging**
