### PR TITLE
[WIP] UI update

### PR DESCRIPTION
**Pull request by tritonas00**
- Moved notification panel on top center, added text shadows
- Prevents notifications overlapping with minimap and client list
- Moved best lap time beside the timer
- Updated chat, client list and notifications background to match imgui theme
(thanks to @CuriousMike56 )

after

### CODE REVIEW

**Comment by CuriousMike56** [comment]
Last lap time slightly overlaps: (just complete a lap of the mud race on F1)
image

**Comment by tritonas00** [comment]
fixed

**Comment by CuriousMike56** [comment]
Looks good now 👍

**Comment by tritonas00** [comment]
lets wait for the full imgui port

**Pull request closed without merging**
