### PR TITLE
✨ Added PMM

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
https://vector-of-bool.github.io/2018/10/15/pmm.html

### CODE REVIEW

**Comment by only-a-ptr** [comment]
> https://vector-of-bool.github.io/2018/10/15/pmm.html

I :heart: that guy.

**Comment by ulteq** [comment]
I think we can merge this. @only-a-ptr

**Comment by only-a-ptr** [comment]
One more day, please

**Comment by only-a-ptr** [comment]
Testing and not working so well, getting zillion errors. Attached is a VisualStudio build log
[03 - VS build2, failing.txt](https://github.com/RigsOfRods/rigs-of-rods/files/2640959/03.-.VS.build2.failing.txt)

**Comment by AnotherFoxGuy** [comment]
@only-a-ptr That issue has been fixed: https://github.com/vector-of-bool/pmm/issues/10

**Pull request closed without merging**
