### PR TITLE
Build system cleanup

### PR DESCRIPTION
**Pull request by mikadou**
Some cleanup and improvements related to the build system.
Also addresses #739

### CODE REVIEW

**Comment by Hiradur** [comment]
Can you also fix #560?

**Comment by mikadou** [comment]
I just had another idea. How about enabling _true_ out-of-source builds? Currently the generated executables are placed in the `bin` directory inside the source tree.

**Comment by tritonas00** [comment]
Compiled fine but when i run RoRConfig or RoR i get

`/opt/rigsofrods/RoR: error while loading shared libraries: libversion_info.so: cannot open shared object file: No such file or directory`

**Comment by mikadou** [comment]
@tritonas00 could you share the output of `ldd /opt/rigsofrods/RoR`?

Does it work if you change https://github.com/RigsOfRods/rigs-of-rods/pull/758/files#diff-1d2543acbb7cf406daae3cc83a507a09R28 to
`add_library( version_info STATIC ${VERSION_INFO_CPP} )` and recompile?

**Comment by tritonas00** [comment]
I use custom path for most of the libs so it asks it there:

`libversion_info.so => /opt/rigsofrods/lib/libversion_info.so (0x00007f807f815000)`

If i copy it there, it works. I will try the code change tomorrow, thanks!

**Comment by tritonas00** [comment]
The static works fine.

**Comment by mikadou** [comment]
@tritonas00 Thanks for testing. Simply linking statically is probably better anyway.

**Comment by mikadou** [comment]
* #560 is addressed and `sudo` is no longer used (see #267).
* Further cleanup of cmake files
* RoR executable is now created inside the build directory instead of the source tree

@Hiradur Could you please review once again?

**Comment by Hiradur** [comment]
Can't comment on the Windows part but I think the cleanup looks nice.

I don't know how far Travis CI have come with upgrading their OS to Ubuntu 14.04 but if it's available now you could ditch the installation of gcc 4.8.
If Ogre 1.9 is available from the repository we could also use that instead of compiling it manually.

**Comment by mikadou** [comment]
> ressources: typo?

> missing closing } bracket

Yes, sorry about these two. This is work in progress. I comitted the changes before rebooting into Windows without testing.

Building works now for me on Windows, however, git is not found. Therefore no commit information is presented in the version string.

I'll clean up the commit history later and ask @Speciesx to test once again. If it also works for him I'm going to merge into master.

**Comment by ulteq** [comment]
@mikadou, @Speciesx What's the status of this?

**Comment by Speciesx** [comment]
@ulteq 
When I tested the last time it worked.

**Comment by mikadou** [comment]
@ulteq This should be ready for merging.

**Comment by AnotherFoxGuy** [comment]
I'm unable to build this with VS12 & Ogre 1.9
Full log: http://pastebin.com/K9mW4TT3

**Comment by mikadou** [comment]
@AnotherFoxGuy Thanks for reporting. I believe you are actually trying to build #824 , because you are getting an error about ` <OGRE/OgreVector3.h>` not being found which was introduced in that latest PR. Could you change that line in source/main/datatypes/node_t.h to `#include <OgreVector3.h>` and post your log again if it still fails?

**Comment by mikadou** [comment]
@AnotherFoxGuy In addition you will probably need your own changes from #779

**Comment by Speciesx** [comment]
@mikadou @AnotherFoxGuy 
https://github.com/RigsOfRods/rigs-of-rods/blob/102144c75aeb0be8a178b4bbf9ebd35c1d400b2d/source/main/datatypes/node_t.h#L11

**Pull request merged**
