### PR TITLE
[Codechange] Thomas HDX relies on fast_normalise rounding errors

### PR DESCRIPTION
**Pull request by ulteq**

### CODE REVIEW

**Comment by Hiradur** [comment]
what is this supposed to fix?

**Comment by only-a-ptr** [comment]
@Hiradur From our Gitter chatroom:

> **Ulteq:**
> @only-a-ptr You were right: https://github.com/RigsOfRods/rigs-of-rods/pull/863#issuecomment-216215268 :smile:
> The little change I did, screwed the Thomas HDX up again.
> I looks like some trucks rely on the rounding errors that fast_normalise produces. :disappointed:
> I fixed it, and I won't ever touch fast_normalise again. ^^

**Comment by Hiradur** [comment]
ok, but we didn't have a corresponding issue ticket for that, right?

**Comment by only-a-ptr** [comment]
@Hiradur No ticket, just an issue :smile: 
https://github.com/RigsOfRods/rigs-of-rods/pull/863

**Comment by Hiradur** [comment]
ok, I got it now, I was confusing this with #844

**Pull request merged**
