### PR TITLE
Procedural road editing using AngelScript

### PR DESCRIPTION
**Pull request by only-a-ptr**
This introduces scripting API for full procedural road management and also bundled script "road_editor.as" which allows interactive road editing!

screenshot_2022-11-28_12-26-39_1

To start the editor script, open console and say "loadscript road_editor.as".

**Features:**
* add or remove roads
* add or remove road points
* move existing points using mouse
* add new points at character position
* export a specific range of road points as AI waypoints
* import a specific range of AI waypoints as road points
* export roads in the 'editor_out.txt' file
* road smoothing by specifying number of extra splits
* Hotkeys: ROAD_EDITOR_{POINT_ADD, POINT_DELETE, POINT_SET_POS, POINT_GOTO, REBUILD_MESH} - all shown in the UI.
* select road segment type (pillars, borders...)
* edit all available parameters, see https://docs.rigsofrods.org/terrain-creation/old-terrn-subsystem/#procedural-roads
* adjustable min height above terrain
* editable point height above terrain

You can also script custom meshes using `addQuad()` and `addCollisionQuad()`. AngelScript API documentation will be available at https://developer.rigsofrods.org/d4/d07/group___script2_game.html once this PR is merged.

### CODE REVIEW

**Comment by CuriousMike56** [comment]
Very nice! Hopefully later on it'll be possible move road points the same way as other objects, (Character freezes in place, use arrow keys to adjust position + press `R` to switch rotation axis)

**Comment by only-a-ptr** [comment]
@tritonas00 requested an option to export road points as AI waypoints. I added 2 sliders to specify a range, and an export button:
screenshot_2022-11-29_01-07-15_1
While at it, I also implemented an import of AI waypoints as procedural road points, with the same controls:
screenshot_2022-11-29_00-59-10_1

**Comment by only-a-ptr** [comment]
> @CuriousMike56 Hopefully later on it'll be possible move road points the same way as other objects

Eventually, but not in this PR. That logic is hardcoded and somewhat dirty (reuses existing hotkeys), I don't want to extend it any further.

**Comment by only-a-ptr** [comment]
Road smoothing is real!
smoothing!
Currently this can't be enabled from TOBJ file format, just previewed using the editor script.
I actually developed this a year ago and it's been collecting dust in my git fork, I'm happy I finally integrated it.

**Comment by only-a-ptr** [comment]
It's complete. Not perfect but helpful.
Hotkeys:
```
    // Road editing
    {"ROAD_EDITOR_POINT_INSERT",      ,      "Keyboard EXPL+INSERT",         _LC("InputEvent", "insert road point") },
    {"ROAD_EDITOR_POINT_GOTO",        ,        "Keyboard EXPL+G",              _LC("InputEvent", "go to road point") },
    {"ROAD_EDITOR_POINT_SET_POS",     ,     "Keyboard EXPL+M",              _LC("InputEvent", "set road point position") },
    {"ROAD_EDITOR_POINT_DELETE",      ,      "Keyboard EXPL+DELETE",         _LC("InputEvent", "delete road point") },
    {"ROAD_EDITOR_REBUILD_MESH",      ,      "Keyboard EXPL+B",              _LC("InputEvent", "regenerate road mesh") },
```
finished

**Review by tritonas00 — APPROVED** [review]

**Pull request merged**
