### PR TITLE
Unlimited nodes & beams

### PR DESCRIPTION
**Pull request by only-a-ptr**
I made a test branch which doesn't limit number of nodes/beams. See this discussion: https://github.com/RigsOfRods/rigs-of-rods/issues/1336

Update (saturday 24.6.2017): I threw away my friday's code and re-coded it properly. Everything is working! Go ahead and test!

### CODE REVIEW

**Comment by only-a-ptr** [comment]
BUMP!

I remade this branch from scratch - MUCH less invasive change, everything is working perfectly! Go ahead and test!

**Comment by tritonas00** [comment]
This https://www.dropbox.com/s/wai9uytcru95d4m/Desperado.zip?dl=1 segfaults

**Comment by only-a-ptr** [comment]
@tritonas00 Reproduced, thanks. I'll need some time to track this one down though...

**Comment by fidoj** [comment]
screenshot_2017-06-25_01-55-28_1
seems to be working well

**Comment by fidoj** [comment]
yes this throws the same error with my gooseneck trailer
05:34:32: FLEXBODY ERROR on mesh fgns_head.mesh: VX node not found

**Comment by Michael10055** [comment]
ror_2017-06-24_15-03-05
👍

**Comment by only-a-ptr** [comment]
@fidoj @tritonas00 I'm under impression those flexbody issues actually come from current upstream rather than this branch. I'm getting similar issues elsewhere. Can you check it out?

**Comment by only-a-ptr** [comment]
Debugging notes (in progress):

This callstack stuffs invalid beam into RailBuilder - node 2 is pointer to invalid memory.
```
>	RoR.exe!RailBuilder::pushBack(beam_t * next) Line 118	C++
 	RoR.exe!RigSpawner::CreateRail(std::vector<RigDef::Node::Range,std::allocator<RigDef::Node::Range> > & node_ranges) Line 3042	C++
 	RoR.exe!RigSpawner::ProcessSlidenode(RigDef::SlideNode & def) Line 2904	C++
 	RoR.exe!RigSpawner::SpawnRig() Line 339	C++

```

**Comment by only-a-ptr** [comment]
@tritonas00 can you re-test this please?

**Comment by tritonas00** [comment]
Desperado still crashes, and now nhelens too while loading Monorail

**Comment by tritonas00** [comment]
https://pastebin.com/SikeG9n7

**Comment by tritonas00** [comment]
yes Auriga, here is nhelens: https://www.dropbox.com/s/ismshmhcyxaluc1/nhelens.zip?dl=1

**Comment by tritonas00** [comment]
ok i will strip down this PR to find what commit broke it

**Comment by only-a-ptr** [comment]
@tritonas00 That's really weird because that commit is very simple and doesn't change anything related to OGRE. And the crash trace you've posted is from OGRE's scene nodes.

Try OGRE 1.9 please.

**Comment by tritonas00** [comment]
Still crashes with 1.9, i can't even load the map...

**Comment by only-a-ptr** [comment]
I miscounted beams again... too few for 'wheels' and I missed one extra for each node with "h" flag. Updated.

**Comment by tritonas00** [comment]
Now nhelens and desperado work fine :simple_smile:

**Comment by only-a-ptr** [comment]
> But still crashes while loading scaniawreckers, (autoloads with nhelens)

I'll test.

> Edit, yep, everything with 'wheels' (like agora) crashes

Always update your local repo - I often modify the existing commits. At this point, wheels are fixed.

**Comment by only-a-ptr** [comment]
Now this is just great 😠

The commit `no more MAX_SHOCKS` broke loading Auriga map for me - I started getting nonsense crashes. I restored the previous commit and tried a simple thing - I resized the shocks array from 5000 items to 1000 items (and nothing else). Guess what - Auriga went :boom: with a nonsense trace! I put 5000 back - Auriga worked! 💢 

What does this mean? This means that **RoR had actually been broken for a very long time (bad memory management)** and it only shows up now when I'm re-organizing things in RAM.

**Comment by tritonas00** [comment]
Everything works fine now for me. Auriga crashed for me also with ogre 1.9

with ogre 1.8 and this PR spawns fine

**Comment by only-a-ptr** [comment]
Strange. The message above I deleted was wrong, my mistake.

However, the Auriga crash still doesn't make sense, I'll keep testing.

**Comment by only-a-ptr** [comment]
.... miscounted shocks (I left out one for each 'trigger') 😊

**Comment by tritonas00** [comment]
Everything runs fine here also

**Comment by tritonas00** [comment]
fix  appveyor also?:stuck_out_tongue_closed_eyes:

**Comment by only-a-ptr** [comment]
@tritonas00 AppVeyor is currently broken itself somehow. I just ignored it for the time being.

**Pull request merged**
