### PR TITLE
🔧 Update OGREdeps to 2019-04 

### LINKED ISSUE #2407: OIS.dll segfault after PMM 'update'
Since https://github.com/RigsOfRods/rigs-of-rods/pull/2402 I can't run RoR in Debug configuration... it will segfault when calling `OIS::InputManager::createInputSystem()`. 
```
Exception thrown at 0x00007FFACF58B391 (OIS.dll) in RoR.exe: 0xC0000005: Access violation reading location 0x0000000000000019.
```

Release configuration works OK. 

I'm baffled why and how it's hapenning. The libs used are the same as before. I made a clean cmake setup and collected all the logs I thought of. Platform: Windows10 x64, Visual Studio 2015, cmake 3.14.5, conan 1.16.0 (installed via PiP)
[Logs.zip](https://github.com/RigsOfRods/rigs-of-rods/files/3477352/ror.PMM.fail.zip)

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
This also should fix #2407

### CODE REVIEW

**Comment by only-a-ptr** [comment]
Let me see...

**Comment by AnotherFoxGuy** [comment]
The MyGUI debug build fails, working on a fix

**Comment by only-a-ptr** [comment]
MyGUI seems to have built fine for me, but I received a different error:
```
conanfile.txt imports(): 
Copied 46 '.dll' files
conanfile.txt imports(): Copied 6 '.exe' files

CMake Error at C:/Users/po185021/Builds/rigs-of-rods/conanbuildinfo_multi.cmake:478 (message):
  No conanbuildinfo_debug.cmake, please install the Debug conf first
Call Stack (most recent call first):
  C:/Users/po185021/Builds/rigs-of-rods/_pmm/1.5.1/conan.cmake:513 (include)
  C:/Users/po185021/Builds/rigs-of-rods/_pmm/1.5.1/conan.cmake:658 (_pmm_conan_install)
  C:/Users/po185021/Builds/rigs-of-rods/_pmm/1.5.1/main.cmake:32 (_pmm_conan)
  C:/Users/po185021/Builds/rigs-of-rods/_pmm/1.5.1/main.cmake:47 (_pmm_project_fn)
  cmake/DependenciesConfig.cmake:20 (pmm)
  CMakeLists.txt:99 (include)
```
[cmake-log.txt](https://github.com/RigsOfRods/rigs-of-rods/files/3478715/cmake-log.txt)

**Comment by AnotherFoxGuy** [comment]
@only-a-ptr That is caused by the failing MyGUI build, it should be fixed now

**Comment by AnotherFoxGuy** [comment]
Everything should be fixed now

**Comment by tritonas00** [comment]
This includes ogre with patches from ptr repo also. So this PR with https://github.com/RigsOfRods/rigs-of-rods/pull/2373 fixes https://github.com/RigsOfRods/rigs-of-rods/issues/2353 i guess. Nice.

I tried Release and Debug conan/pmm build without ninja with this PR, no OIS issues.

Release works, but Debug gave me
```
InternalErrorException: Error decoding image in FreeImageCodec::decode at /home/babis/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/ca29784d0a8597d724777a4027cf051e5cbb0e7c/PlugIns/FreeImageCodec/src/OgreFreeImageCodec.cpp (line 405)
```
when launched RoR

**Comment by only-a-ptr** [comment]
Works smoothly on my Win10-x64 laptop (conan 1.18, cmake 3.14.5)
But on my Win7-x64 desktop (conan 1.18, cmake 3.15.2) I get:
```
WARN: libcurl/7.61.1@bincrafters/stable requirement OpenSSL/latest_1.0.2x@conan/stable overridden by your conanfile to OpenSSL/1.0.2o@conan/stable 

WARN: MyGUI/3.2.3-OGRE-1.11.6-with-patches@anotherfoxguy/stable requirement OGREdeps/[20.x]@anotherfoxguy/stable overridden by your conanfile to OGREdeps/2019-04@anotherfoxguy/stable 

ERROR: Version range '20.x' required by 'MyGUI/3.2.3-OGRE-1.11.6-with-patches@anotherfoxguy/stable' not valid for downstream requirement 'OGREdeps/2019-04@anotherfoxguy/stable'
```
[cmake-newdeps-win7.txt](https://github.com/RigsOfRods/rigs-of-rods/files/3487211/cmake-newdeps-win7.txt)

**Comment by tritonas00** [comment]
Now `Release` broke too here. It wants `zziplib`. Installed and got 
```
ItemIdentityException: Can not find codec for 'png' image format.
Supported formats are: dds ktx pkm. in Codec::getCodec at /home/babis/.conan/data/OGRE/1.11.6-with-patches/anotherfoxguy/stable/build/dfe2c959761ac11a1b854db19439f3576ba4b371/OgreMain/src/OgreCodec.cpp (line 63)
```
<details>
<summary>Spoiler</summary>

`ror-dependencies` doesn't have those issues
troll
</details>

**Comment by AnotherFoxGuy** [comment]
@tritonas00 You now need to have these packages installed on Linux: https://github.com/AnotherFoxGuy/conan-OGRE/blob/stable/1.11/conanfile.py#L16-L26

**Comment by tritonas00** [comment]
Had them all except `zziplib` and `freeimage`. Re trying now

**Comment by tritonas00** [comment]
cmake under windows broke

**Comment by tritonas00** [comment]
Ok is this good now? It needs re-build or something? Because of
https://github.com/RigsOfRods/rigs-of-rods/pull/2373#issuecomment-520837273

Please bring those PRs to master so windows people can easily test https://github.com/RigsOfRods/rigs-of-rods/issues/2353

**Pull request merged**
