### PR TITLE
Added physics pause/unpause notification

### PR DESCRIPTION
**Pull request by tritonas00**
Requested from discord

### CODE REVIEW

**Comment by CuriousMike56** [comment]
The message should stay displayed for the length of time physics is paused and have the message say "Physics paused. Press `COMMON_TOGGLE_PHYSICS` to unfreeze)"

**Comment by tritonas00** [comment]
yeah , i tried to change the timer value but still lasts 2 sec

@only-a-ptr @AnotherFoxGuy can make it probably

**Comment by only-a-ptr** [comment]
The joy of debug builds.... 🙄 
image
Hapenned after I pressed [J]

**Comment by only-a-ptr** [comment]
Closing in favor of #2481

**Pull request closed without merging**
