### PR TITLE
Revert "📐 Removed CrashRpt leftovers"

### PR DESCRIPTION
**Pull request by ulteq**
This reverts commit cba1035cec49874d3dbecd56f57847246510f4ae.

No idea how this works, but people seem to want it back.

### CODE REVIEW

**Comment by AnotherFoxGuy** [comment]
CrashRpt doesn't work anymore with VS 2017, the last version it supported was 2013

**Comment by only-a-ptr** [comment]
Might be a good alternative: https://chromium.googlesource.com/breakpad/breakpad/+/master/docs/getting_started_with_breakpad.md

**Comment by AnotherFoxGuy** [comment]
Or maybe https://www.bugsplat.com ?

https://www.bugsplat.com/docs/platforms/cplusplus

**Comment by only-a-ptr** [comment]
Bugsplat doesn't have non-commercial plan: https://www.bugsplat.com/pricing

**Comment by ulteq** [comment]
Or we simply leave everything as is? I don't really see the point in having something like `CrashRpt` to be honest.

**Comment by only-a-ptr** [comment]
There's never enough stack traces when reporting a bug, but we manage very well without.

I'd leave everything as-is for now and look into Breakpad later.

**Pull request closed without merging**
