### PR TITLE
Update sky input events in free cam mode

### PR DESCRIPTION
**Pull request by tritonas00**
Reported from discord:

> You can't advance time while in free cam mode anymore

### CODE REVIEW

**Comment by only-a-ptr** [comment]
This way you'll make all these active in free-camera mode:
```
EV_COMMON_GET_NEW_VEHICLE
EV_COMMON_ENTER_OR_EXIT_TRUCK
EV_COMMON_ENTER_NEXT_TRUCK
EV_COMMON_ENTER_PREVIOUS_TRUCK
EV_COMMON_RESPAWN_LAST_TRUCK
EV_SKY_*
EV_COMMON_TOGGLE_TERRAIN_EDITOR
```
It's not a big deal but it never worked like that before.

The nicest solution would be to create `GameContext::UpdateSkyInputEvents()` and put both SKY* blocks there.

**Comment by tritonas00** [comment]
Oops you are right, will try to do it that way

**Comment by tritonas00** [comment]
moved sky input events in `UpdateSkyInputEvents` and updated `main.cpp` accordingly

**Review by only-a-ptr — APPROVED** [review]
Looks good

**Pull request merged**
