### PR TITLE
⬆️ Updated conan packages for conan V2

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
Note the new remote requires conan to have revisions enabled
You can enable it by running `conan config set general.revisions_enabled=1`

### CODE REVIEW

**Comment by only-a-ptr** [comment]
I get an error building OIS. Do I need DirextX SDK?
```
ois/1.4.1@rigsofrods/custom: Configuring sources in C:\Users\Petr\.conan\data\ois\1.4.1\rigsofrods\custom\source\.
ois/1.4.1@rigsofrods/custom: Copying sources to build folder
ois/1.4.1@rigsofrods/custom: Building your package in C:\Users\Petr\.conan\data\ois\1.4.1\rigsofrods\custom\build\294a41a00eb9659ac71d43f8ae66d3f04fec23e6
ois/1.4.1@rigsofrods/custom: Generator txt created conanbuildinfo.txt
ois/1.4.1@rigsofrods/custom: Calling generate()
ois/1.4.1@rigsofrods/custom: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
ois/1.4.1@rigsofrods/custom: Preset 'default' added to CMakePresets.json. Invoke it manually using 'cmake --preset default'
ois/1.4.1@rigsofrods/custom: If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=C:\Users\Petr\.conan\data\ois\1.4.1\rigsofrods\custom\build\294a41a00eb9659ac71d43f8ae66d3f04fec23e6\build\generators\conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW'
ois/1.4.1@rigsofrods/custom: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
ois/1.4.1@rigsofrods/custom: Aggregating env generators
ois/1.4.1@rigsofrods/custom: Calling build()
ois/1.4.1@rigsofrods/custom: CMake command: cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/Petr/.conan/data/ois/1.4.1/rigsofrods/custom/build/294a41a00eb9659ac71d43f8ae66d3f04fec23e6/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/Petr/.conan/data/ois/1.4.1/rigsofrods/custom/package/294a41a00eb9659ac71d43f8ae66d3f04fec23e6" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\Users\Petr\.conan\data\ois\1.4.1\rigsofrods\custom\build\294a41a00eb9659ac71d43f8ae66d3f04fec23e6\."
-- Using Conan toolchain: C:/Users/Petr/.conan/data/ois/1.4.1/rigsofrods/custom/build/294a41a00eb9659ac71d43f8ae66d3f04fec23e6/build/generators/conan_toolchain.cmake
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.32.31332.0
-- The CXX compiler identification is MSVC 19.32.31332.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at CMakeLists.txt:7 (find_package):
  By not providing "FindDirectX9.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "DirectX9",
  but CMake did not find one.

  Could not find a package configuration file provided by "DirectX9" with any
  of the following names:

    DirectX9Config.cmake
    directx9-config.cmake

  Add the installation prefix of "DirectX9" to CMAKE_PREFIX_PATH or set
  "DirectX9_DIR" to a directory containing one of the above files.  If
  "DirectX9" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring done
CMake Error at CMakeLists.txt:160 (target_link_libraries):
  Target "OIS" links to:

    directx-sdk::directx-sdk

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
-- Generating done
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_POLICY_DEFAULT_CMP0091


CMake Generate step failed.  Build files cannot be regenerated correctly.
ois/1.4.1@rigsofrods/custom: ois/1.4.1@rigsofrods/custom: ERROR: Package '294a41a00eb9659ac71d43f8ae66d3f04fec23e6' build failed

ois/1.4.1@rigsofrods/custom: WARN: Build folder C:\Users\Petr\.conan\data\ois\1.4.1\rigsofrods\custom\build\294a41a00eb9659ac71d43f8ae66d3f04fec23e6\build
ERROR: ois/1.4.1@rigsofrods/custom: Error in build() method, line 41
        cmake.configure()
        ConanException: Error 1 while executing cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/Petr/.conan/data/ois/1.4.1/rigsofrods/custom/build/294a41a00eb9659ac71d43f8ae66d3f04fec23e6/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/Petr/.conan/data/ois/1.4.1/rigsofrods/custom/package/294a41a00eb9659ac71d43f8ae66d3f04fec23e6" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\Users\Petr\.conan\data\ois\1.4.1\rigsofrods\custom\build\294a41a00eb9659ac71d43f8ae66d3f04fec23e6\."
CMake Error at cmake/conan.cmake:638 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/DependenciesFunctions.cmake:245 (conan_cmake_install)
  cmake/DependenciesFunctions.cmake:255 (_conan_install)
  CMakeLists.txt:121 (resolve_conan_dependencies)


-- Configuring incomplete, errors occurred!
See also "C:/Users/Petr/builds/rigs-of-rods/CMakeFiles/CMakeOutput.log".

c:\Users\Petr\source\_scripts>pause
Press any key to continue . . .
```
My system is Win10, latest cmake/conan, conan was purged, ror build directory was clean.

**Comment by only-a-ptr** [comment]
I tried patching my DependenciesConfig.cmake to use `ois/1.5.1@anotherfoxguy/stable`. I've been doing this silently ever since we downgraded to 1.4 anyway. Now I get a different error.
```
ERROR: ogre3d-caelum/0.6.3.1@anotherfoxguy/stable: Error in build() method, line 44
        cmake.configure()
        ConanException: Error 1 while executing cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/Petr/.conan/data/ogre3d-caelum/0.6.3.1/anotherfoxguy/stable/build/189e5ad16abffca76d59d421b63293b8938ae017/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/Petr/.conan/data/ogre3d-caelum/0.6.3.1/anotherfoxguy/stable/package/189e5ad16abffca76d59d421b63293b8938ae017" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\Users\Petr\.conan\data\ogre3d-caelum\0.6.3.1\anotherfoxguy\stable\build\189e5ad16abffca76d59d421b63293b8938ae017\."
```
Full logs and specs, including cmake generated files:
[rigsofrods-2965-ois151.zip](https://github.com/RigsOfRods/rigs-of-rods/files/10017022/rigsofrods-2965-ois151.zip)

**Comment by only-a-ptr** [comment]
I'll explore how much work it would be to finally port to SDL2, OIS is becoming more and more of a nuissance.

**Comment by AnotherFoxGuy** [comment]
It seems that it still using the old packages from `rigs-of-rods-deps-V2`
try removing the old remote by running `conan remote remove rigs-of-rods-deps-V2`, then you can update the packages by running `conan install . -u -b missing` in the build folder

**Comment by only-a-ptr** [comment]
I removed the remote, purged Conan data and re-ran cmake. Same problem it seems.
[rigsofrods-2965-deletedV2deps.zip](https://github.com/RigsOfRods/rigs-of-rods/files/10026583/rigsofrods-2965-deletedV2deps.zip)

`conan install . -u -b missing` yielded something different entirely:
[rigsofrods-2965-u-b-missing.zip](https://github.com/RigsOfRods/rigs-of-rods/files/10026619/rigsofrods-2965-u-b-missing.zip)

**Comment by AnotherFoxGuy** [comment]
From the log it still adds the old remote: `Conan: Adding rigs-of-rods-deps-V2 remote repository (https://artifactory.anotherfoxguy.com/artifactory/api/conan/rigs-of-rods) verify ssl (True)`  
and fetches the old ois package: `ois/1.4@rigsofrods/custom from 'rigs-of-rods-deps-V2' - Downloaded`

Are you sure that you checked out this PR?

**Comment by only-a-ptr** [comment]
> @AnotherFoxGuy Are you sure that you checked out this PR?

I tried again and it turns out I haven't, sorry. Now it configures and builds fine.

Just on side note, `ois/1.4.1@rigsofrods/custom` crashes for me on startup, as it always has since we downgraded to it. Patching DependenciesConfig.cmake to `ois/1.5.1@anotherfoxguy/stable` fixes it. I'll explore SDL2.

**Comment by only-a-ptr** [comment]
On my laptop I get this:
```
ogre3d/1.11.6.1@anotherfoxguy/stable: Not found in local cache, looking in remotes...
ogre3d/1.11.6.1@anotherfoxguy/stable: Trying with 'conancenter'...
ogre3d/1.11.6.1@anotherfoxguy/stable: Trying with 'ror-conan'...
ERROR: Unable to find 'ogre3d/1.11.6.1@anotherfoxguy/stable' in remotes
CMake Error at cmake/conan.cmake:638 (message):
  Conan install failed='1'
```
I have no idea why it happens. Conan+cmake are latest, conan data were clean, so was ROR builddir. Internet works of course. I'll attach full logs in a bit.

**Comment by AnotherFoxGuy** [comment]
@only-a-ptr I forgot to mention it, but the new remote requires conan to have revisions enabled
You can enable it by running `conan config set general.revisions_enabled=1`

**Review by only-a-ptr — APPROVED** [review]
Builds and runs on both my machines (Desktop w/visualstudio2022, Laptop w/visualstudio2019). Also tested on ArchLinux by Tritonas. Clear for merge.

However there's one more nuissance which had existed for about a year: plugins_d.cfg always have RenderSystem_GL commented out even though it's present, and there's 'Caelum' instead of 'Caelum_d'. It would be great if that coud be fixed here as well.

**Comment by AnotherFoxGuy** [comment]
> However there's one more nuissance which had existed for about a year: plugins_d.cfg always have RenderSystem_GL_d commented out even though it's present

That has been done on purpose, since the `RenderSystem_GL.dll` file will cause the game to crash on AMD GPUs as soon as the DLL is loaded

**Pull request merged**
